### PR TITLE
Fix bug when brushing

### LINKED ISSUE #3345: brushing in volume mode when zoomed in throws error
When zoomed in very much and trying to brush I get the following error: 

``` TypeError: Cannot read property '0' of undefined
    at new VoxelIterator (VM3788 volumelayer.js:72)
    at VolumeLayer.getCircleVoxelIterator (VM3788 volumelayer.js:255)
    at editVolumeLayerAsync (VM3787 volumetracing_saga.js:88)
    at editVolumeLayerAsync.next (<anonymous>)
    at next (VM3679 proc.js:321)
    at Object.currCb [as cont] (VM3679 proc.js:398)
    at end (VM3679 proc.js:366)
    at Object.task.cont (VM3679 proc.js:109)
    at next (VM3679 proc.js:331)
    at currCb (VM3679 proc.js:398)```

### PR DESCRIPTION
**Pull request by MichaelBuessemeyer**
This bug disables a bug that occurs when trying to brush but the brush is so small that it does not paint any voxels. How to reproduce: zoom in as far as you can and set the brush size to the minimum. Now try to brush (works not for very dataset).

### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- Try the steps that reproduce the bug on a few datasets. The bug should not occur anymore 

### Issues:
- fixes #3345 

------
- ~~[ ] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)~~
- ~~[ ] Updated [migration guide](../blob/master/MIGRATIONS.md#unreleased) if applicable~~
- ~~[ ] Updated [documentation](../blob/master/docs) if applicable~~
- ~~[ ] Needs datastore update after deployment~~
- [x] Ready for review

### CODE REVIEW

File: app/assets/javascripts/oxalis/model/volumetracing/volumelayer.js [hunk 1]
```diff
@@ -46,11 +46,15 @@ export class VoxelIterator {
     this.minCoord2d = minCoord2d;
     this.get3DCoordinate = get3DCoordinate;
     this.boundingBox = boundingBox;
-    const firstCoordinate = this.get3DCoordinate(this.minCoord2d);
-    if (this.map[0][0] && this.isCoordinateInBounds(firstCoordinate)) {
-      this.next = firstCoordinate;
+    if (!this.map || !this.map[0]) {
+      this.hasNext = false;
```
Comment (philippotto) [inline app/assets/javascripts/oxalis/model/volumetracing/volumelayer.js]: Can we add a `return` statement after this line and hoist the following else-block one level up?

**Comment by philippotto** [comment]
@MichaelBuessemeyer On a second thought, do think it makes sense to simply not paint anything when zooming that far in? I guess, I'd find it more plausible if you cannot set the brush size so small in the first place.
