### PR TITLE
In zarr streaming chunk response, answer 503 if dataset is missing

### LINKED ISSUE #8640: Tracingstore zarr streaming yields zeroes if fallback layer cannot be loaded due to server outage
Datastore was down, and then re-initializing its datasource registry.

During that time, it seems that the tracingstore zarr streaming yielded chunks with zeroed data instead of properly failing as the fallback layer chunks could not be fetched.

Instead the request should fail.

Initial report https://scm.slack.com/archives/C143WEU77/p1747657341073999?thread_ts=1747211202.420449&cid=C143WEU77

### PR DESCRIPTION
**Pull request by fm3**
Zarr clients will fall back to zeroed chunks on 404, so in this particular case we should raise 503 so that the clients will escalate the error instead.

Previously, on datastore restarts, the datasourceRepository was empty before the full directory scan, leading to unexpected temporary 404 responses.

I changed the RPC code to forward response status in ParamFailure. This way, RPCs failing with a specific error code will also escalate that error code to their own request.

### Steps to test:
- Request zarr chunk outside the data range, should still reply with 404 (both for annotations and datasets)
- Request zarr chunk for a non-existing dataset (or annotation with non-existing fallback dataset), should reply with 503. To make the dataset “missing” on the datastore, comment out the line `_ <- dataSourceRepository.updateDataSources(foundInboxSources)` in DataSourceService line 85

### Issues:
- fixes #8640

------
- [x] Updated [changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)
- [x] Considered [common edge cases](../blob/master/.github/common_edge_cases.md)
- [x] Needs datastore update after deployment

### CODE REVIEW

**Comment by fm3** [comment]
I only visited the chunk URIs in the browser (created a zarr link via annotation menu, pasted it and added the chunk coordinates. Something like `http://localhost:9000/data/annotations/zarr/73xW_VD-FqmDpqnq/segmentation/1/0.0.0.0`

File: webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/ZarrStreamingController.scala [hunk 1]
```diff
@@ -265,7 +265,7 @@ class ZarrStreamingController @Inject()(
     for {
       (dataSource, dataLayer) <- dataSourceRepository.getDataSourceAndDataLayer(organizationId,
                                                                                 datasetDirectoryName,
-                                                                                dataLayerName) ~> NOT_FOUND
+                                                                                dataLayerName) ~> BAD_REQUEST
```
Comment (MichaelBuessemeyer) [inline webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/ZarrStreamingController.scala:268]: Hmmm honestly on a conceptual level 404 makes more sense here IMO instead of 400. Is it maybe possible to refill the datasourceRepository upon such an initial request instead? 

Sorry to bump against this fix. Or maybe first add a check whether the datasourceRepository is not yet filled and in case it is still empty return 400?

Moreover, this code runs on the datastore. So it should have all the needed information for the dataset when `organizationId, datasetDirectoryName, dataLayerName` are correct? Thus, I could fill in the needed info on demand, can't it?

**Review by MichaelBuessemeyer — COMMENTED** [review]
Left a comment about the approach. Will test soon

File: webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/ZarrStreamingController.scala (hunk 1 above)
Comment (normanrz) [reply webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/ZarrStreamingController.scala:268]: I agree that 400 is a bit weird. Maybe these requests should return 503 as long as the initialization is not complete? That would cause the zarr libraries to retry.

Comment (fm3) [reply webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/ZarrStreamingController.scala]: Good Idea, 503 sounds about right. I changed it. I also wrote https://github.com/scalableminds/webknossos/issues/8649 to track avoiding this problem during the normal datastore operation.

Filling in the needed info on demand could also be possible, but ideally not necessary.
