### PR TITLE
Fix inactive users showing in teams list

### LINKED ISSUE #9074: Team user list shows inactive users. They should be marked as such
Team list teams can be expanded to show user list. This list includes inactive users. They should be marked as such (or be skipped entirely).

### PR DESCRIPTION
**Pull request by hotzenklotz**
A small fix for filtering inactive users from the team list view.

### Steps to test:
- Disable a user
- Navigate to Admin > Teams
- Expand the default team
- Double-check that the disabled user is not listed

### Issues:
- fixes #9074

------
(Please delete unneeded items, merge only when none are left open)
- [ ] Added changelog entry (create a `$PR_NUMBER.md` file in `unreleased_changes` or use `./tools/create-changelog-entry.py`)
- [ ] Added migration guide entry if applicable (edit the same file as for the changelog)
- [ ] Updated [documentation](../blob/master/docs) if applicable
- [ ] Adapted [wk-libs python client](https://github.com/scalableminds/webknossos-libs/tree/master/webknossos/webknossos/client) if relevant API parts change
- [ ] Removed dev-only changes like prints and application.conf edits
- [ ] Considered [common edge cases](../blob/master/.github/common_edge_cases.md)
- [ ] Needs datastore update after deployment

### CODE REVIEW

File: frontend/javascripts/viewer/model/sagas/saving/save_queue_draining_saga.tsx [hunk 1]
```diff
@@ -1,7 +1,7 @@
-// /*
-//  * This module contains the sagas responsible for sending the contents of the save queue
-//  * to the back-end (thus, draining the queue).
-//  */
+/*
```
Comment (hotzenklotz) [inline frontend/javascripts/viewer/model/sagas/saving/save_queue_draining_saga.tsx:1]: This is unrelated to the issue and just formatting
