### PR TITLE
fix volume mode and trigger update action when creating a new cell

### LINKED ISSUE #1889: Volume tracing: Creating new cell does not trigger tracing update
steps to reproduce:
1) create exploratory volume tracing
2) create multiple new cells without moving around!
3) save tracing and reload
4) try to create new cell -> the new cell will use an already existing ID
This is because creating a new cell does not trigger an update of the tracings JSON on the server, which contains the nextCellId, activeCellId etc. This information thus gets lost on reload.

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1889/create?referer=github" target="_blank">Log Time</a>

### PR DESCRIPTION
**Pull request by daniel-wer**
This PR fixes the volume mode that was broken by the webpack3 PR earlier and also properly triggers update actions in volume mode (when creating a cell, activating a cell).

### Steps to test:
- Open volume mode and create multiple cells using "c" without moving. The save icon should switch to unsaved and waiting or triggering a save should lead to an updated activeCellId once the page is refreshed.

### Issues:
- fixes #1889

------
- [x] Ready for review

### CODE REVIEW

File: app/assets/javascripts/oxalis/view/right-menu/dataset_info_tab_view.js [hunk 1]
```diff
@@ -108,7 +106,7 @@ class DatasetInfoTabView extends Component {
 
 function mapStateToProps(state: OxalisState): DatasetInfoTabProps {
   return {
-    skeletonTracing: enforceSkeletonTracing(state.tracing),
```
Comment (philippotto) [inline app/assets/javascripts/oxalis/view/right-menu/dataset_info_tab_view.js]: Sorry about that. I introduced that change. The fact that there was a "skeletonTracing" prop led me to believe that this view will only be rendered if there is a skeleton tracing. I should have double checked that.

Comment (daniel-wer) [inline app/assets/javascripts/oxalis/view/right-menu/dataset_info_tab_view.js]: No problem, I think I would have guessed the same :D
