### PR TITLE
Fix rare callstack overflow when annotating large areas

### LINKED ISSUE #6074: Maximum stack size exceeded when brushing large areas very fast
## Context
Volume Annotation.

## Current Behavior
Crashes with maximum call stack size exceeded error.

Also see https://github.com/scalableminds/webknossos/pull/6055#issuecomment-1048057756

## Steps to Reproduce the bug

- [ ] Cannot reproduce the bug anymore / needs deeper investigation.

Unfortunately, the repro is not 100% reliable:
1. Open new volume annotation
2. Brush large areas very fast and click save in between

## Your Environment for bug

- Browser name and version: e.g. Chrome 39
- Operating System and version: e.g. Windows 10
- Version of WebKnossos (Release or Commit):
- [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
- [ ] Specific to webKnossos.org (set `isDemoInstance=true` in `application.conf`)

### PR DESCRIPTION
**Pull request by philippotto**
I suspect that redux-saga uses too much recursion as suggested here https://github.com/redux-saga/redux-saga/issues/605. Let's say whether the workaround really helps.

### URL of deployed dev instance (used for testing):
- https://fixstackoverflow.webknossos.xyz

### Steps to test:
- brush a lot very fast
- saga shouldn't crash

### Issues:
- fixes #6074

------
(Please delete unneeded items, merge only when none are left open)
- [x] Updated [(unreleased) changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)
- [ ] Updated [(unreleased) migration guide](../blob/master/MIGRATIONS.unreleased.md#unreleased) if applicable
- [ ] Updated [documentation](../blob/master/docs) if applicable
- [ ] Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes
- [ ] Adapted [wk-libs python client](https://github.com/scalableminds/webknossos-libs/tree/master/webknossos/webknossos/client) if relevant API parts change
- [ ] Needs datastore update after deployment
- [X] Ready for review

### CODE REVIEW

File: frontend/javascripts/oxalis/model/sagas/save_saga.js [hunk 1]
```diff
@@ -224,7 +224,12 @@ export function* collectUndoStates(): Saga<void> {
     "REDO",
   ]);
 
+  window.counter = 0;
   while (true) {
+    window.counter++;
+    if (window.counter % 100 === 0) {
+      yield _delay(0);
+    }
```
Comment (philippotto) [inline frontend/javascripts/oxalis/model/sagas/save_saga.js:232]:
```suggestion
  let loopCounter = 0;
  while (true) {
    loopCounter++;
    if (loopCounter % 100 === 0) {
      yield _delay(0);
    }
```

**Review by daniel-wer — COMMENTED** [review]
I wasn't able to provoke a call stack overflow on this branch. However, I also wasn't able to produce one on master :see_no_evil: 
Are you still able to reproduce the original error on the deployed master or was this possibly fixed in an unrelated PR in the mean time?
