### PR TITLE
Fix expanding the sidebar preventing hotkeys from working immediately

### LINKED ISSUE #5827: Keyboard shortcuts don't work after using button to collapse/expand sidebars
a `blur()` is probably needed when clicking these buttons.

## Steps to Reproduce the bug

- [ ] Cannot reproduce the bug anymore / needs deeper investigation.

1. expand/collapse sidebar via button
2. press f to move across a dataset (this does not work currently; a click on the data viewport is necessary first)
3.
4.

## Your Environment for bug

- Browser name and version: e.g. Chrome 39
- Operating System and version: e.g. Windows 10
- Version of WebKnossos (Release or Commit):
- [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
- [ ] Specific to webKnossos.org (set `isDemoInstance=true` in `application.conf`)

### PR DESCRIPTION
**Pull request by hotzenklotz**
This PR fixes a bug whereby expanding/collpasing the sidebar using the little icon buttons would make the main XYZ viewports lose focs/not respond to keyboard inputs anymore. Instead of having to click in the viewport to restore focs and continue using the keyboard hotkeys this now should work without any addtional click/refocusing.

Techical details:
- It seems to me that the first `blur()` call only every blurred the <div> element of the icon itself. For some reasons, the surround button element still retained focus/control. By also calling `blur()`onthe parent button element the issue resolved itself.

### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- Expand/Collapse sidebar via button
- Press any hotkey, e.g. f or SPACE, and observe that the intended behavior, e.g. movement, occurs

### Issues:
- fixes #5827

------
(Please delete unneeded items, merge only when none are left open)
- [x] Updated [(unreleased) changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)
- [ ] Updated [(unreleased) migration guide](../blob/master/MIGRATIONS.unreleased.md#unreleased) if applicable
- [ ] Updated [documentation](../blob/master/docs) if applicable
- [ ] Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes
- [ ] Adapted [wk-libs python client](https://github.com/scalableminds/webknossos-libs/tree/master/webknossos/webknossos/client) if relevant API parts change
- [ ] Needs datastore update after deployment
- [x] Ready for review

### CODE REVIEW

File: frontend/javascripts/oxalis/view/components/border_toggle_button.tsx [hunk 1]
```diff
@@ -46,7 +46,9 @@ function BorderToggleButton(props: Props) {
         onClick={(event) => {
           if (event != null) {
             // @ts-expect-error ts-migrate(2339) FIXME: Property 'blur' does not exist on type 'EventTarge... Remove this comment to see the full error message
-            event.target.blur();
```
Comment (philippotto) [inline frontend/javascripts/oxalis/view/components/border_toggle_button.tsx:49]: I think this blur() can be removed, as it probably doesn't do anything. As far as I know, only one blur will have an effect, since only one element can have the page focus. I also just tested it and the second blur seems to be enough to solve the issue :tada:

**Review by philippotto — COMMENTED** [review]
thanks for digging into this!

File: frontend/javascripts/oxalis/view/components/border_toggle_button.tsx (hunk 1 above)
Comment (philippotto) [reply frontend/javascripts/oxalis/view/components/border_toggle_button.tsx:49]: ah, it seems like it depends on where the user clicks exactly. sometimes the inner element gets the focus and sometimes the outer element. this is why both blurs make sense (however, with a slightly differing explanation than in your PR :)).

**Review by philippotto — APPROVED** [review]
