### PR TITLE
Fix segmentation opacity in recommended tasktype

### LINKED ISSUE #4546: Can’t edit task type due to segmentation opacity
[Link to Discuss](https://discuss.webknossos.org/t/cant-edit-task-type/1589)

### PR DESCRIPTION
**Pull request by philippotto**
### URL of deployed dev instance (used for testing):
- https://fixsegmentationopacityinrecommendedtasktype.webknossos.xyz

### Steps to test:
- edit the existing task type to use recommended settings
- edit the segmentation opacity in the recommended settings to another value X
- create a task
- get that task
- ensure that the segmentation opacity is listed there
- accept the settings
- check that the opacity was set to X

### Issues:
- fixes #4546

------
- [X] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)
- [ ] ~Updated [migration guide](../blob/master/MIGRATIONS.md#unreleased) if applicable~
- [ ] ~Updated [documentation](../blob/master/docs) if applicable~
- [ ] ~Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes~
- [ ] ~Needs datastore update after deployment~
- [X] Ready for review

### CODE REVIEW

File: frontend/javascripts/oxalis/view/new_task_description_modal.js [hunk 1]
```diff
@@ -23,9 +23,12 @@ export default class NewTaskDescriptionModal extends React.Component<Props, Stat
...
 
   componentDidMount() {
-    this.timeoutId = setTimeout(() => {
-      this.allowClose();
-    }, 10000);
+    this.timeoutId = setTimeout(
+      () => {
+        this.allowClose();
+      },
+      process.env.NODE_ENV === "production" ? 10000 : 2000,
```
Comment (daniel-wer) [inline frontend/javascripts/oxalis/view/new_task_description_modal.js:30]: :pray:

File: frontend/javascripts/admin/tasktype/recommended_configuration_view.js [hunk 2]
```diff
@@ -31,6 +31,7 @@ const recommendedConfigByCategory = {
   dataset: {
     fourBit: false,
     interpolation: true,
+    segmentationOpacity: 80,
```
Comment (daniel-wer) [inline frontend/javascripts/admin/tasktype/recommended_configuration_view.js:34]:
```suggestion
    segmentationOpacity: 0,
```

The previous default was 0 according to git and https://discuss.webknossos.org/t/settings-via-task-type/1173/4.
