### PR TITLE
in task-from-file creation, allow multiple files in formData

### LINKED ISSUE #3175: Support uploading multiple files in task creation (both NML and Zip)
see https://discuss.webknossos.org/t/task-creation-failed-but-no-warning/1098

### PR DESCRIPTION
**Pull request by fm3**
### URL of deployed dev instance (used for testing):
- https://taskmultifiles.webknossos.xyz

### Steps to test:
- in create task form, select »Upload NML file«, drag in multiple files (you may mix nmls and zips)
- single file should also still work

### Issues:
- fixes #3175 

------
- [ ] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)
- ~~[ ] Updated [migration guide](../blob/master/MIGRATIONS.md#unreleased) if applicable~~
- ~~[ ] Updated [documentation](../blob/master/docs) if applicable~~
- ~~[ ] Needs datastore update after deployment~~
- [x] Ready for review

### CODE REVIEW

**Comment by fm3** [comment]
@daniel-wer could you have a look if the front-end code needs changes for this? It works with the current code, but I don’t know if some things should be handled differently. Also, we should probably change the wording on the form. Maybe we should also rename the route :)

File: app/assets/javascripts/admin/task/task_create_form_view.js [hunk 1]
```diff
@@ -311,27 +313,27 @@ class TaskCreateFormView extends React.PureComponent<Props, State> {
...
                     valuePropName: "fileList",
                     getValueFromEvent: this.normFile,
                   })(
                     <Upload.Dragger
                       accept=".nml,.zip"
-                      name="nmlFile"
+                      name="nmlFiles"
                       beforeUpload={file => {
-                        this.props.form.setFieldsValue({ nmlFile: [file] });
+                        this.props.form.setFieldsValue({ nmlFiles: [file] });
```
Comment (daniel-wer) [inline app/assets/javascripts/admin/task/task_create_form_view.js]: @philippotto `beforeUpload` is called for every file that is dragged onto the upload section of the form. I would have suspected that the forms fieldValue `nmlFiles` would be overwritten by subsequent "drags" of files, but it is not, although `setFieldsValue` is called repeatedly with different files. Do you know why this works?

Comment (philippotto) [reply app/assets/javascripts/admin/task/task_create_form_view.js]: Hmm, seems definitely wrong. The antd documentation lists an example like this:

```
      beforeUpload: (file) => {
        this.setState(({ fileList }) => ({
          fileList: [...fileList, file],
        }));
        return false;
      },
```

However, this sets the state (as that is needed for some special rendering). 

My assumption is that we can remove the entire `beforeUpload` hook, since antd manages this by itself, anyway? And that's why it works at the moment?

**Comment by daniel-wer** [comment]
Frontend should be good :)
