### PR TITLE
Better find data support for segmentation layer

### LINKED ISSUE #4204: "Find my data" does not work for segmentation in volume tracings
Might need differentation between with/without fallback. In both ways, it would be nice to have that feature. Searching for data in a volume tracing should be easy for the backend, right?
Otherwise, we should at least disable the button to avoid ugly errors.

### PR DESCRIPTION
**Pull request by MichaelBuessemeyer**
This PR improves the support of the `find data`-feature for segmentation layers. If the layer is a segmentation layer and includes a volume tracing, the maybe existing fallback layer is used for this feature. If there is no fallback layer, this feature is disabled.

### URL of deployed dev instance (used for testing):
- https://finddataforsegmentation.webknossos.xyz/

### Steps to test:
- Open a tracing with and without fallback layer and test the `find data`-feature. If there is a fallback layer, the feature/button should be enabled and work. If there is none, the feature/button should be disabled and the tooltip should shortly explain why.

### Issues:
- fixes #4204

------
- ~~[ ] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)~~
- ~~[ ] Updated [migration guide](../blob/master/MIGRATIONS.md#unreleased) if applicable~~
- ~~[ ] Updated [documentation](../blob/master/docs) if applicable~~
- ~~[ ] Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes~~
- ~~[ ] Needs datastore update after deployment~~
- [x] Ready for review

### CODE REVIEW

**Comment by MichaelBuessemeyer** [comment]
@philippotto I still need your review on this PR :slightly_smiling_face:

File: frontend/javascripts/oxalis/view/settings/dataset_settings_view.js [hunk 1]
```diff
@@ -306,6 +330,7 @@ class DatasetSettings extends React.PureComponent<DatasetSettingsProps, State> {
 
   getSegmentationPanel() {
     const segmentation = Model.getSegmentationLayer();
+    console.log(segmentation);
```
Comment (philippotto) [inline frontend/javascripts/oxalis/view/settings/dataset_settings_view.js]: Please remove :)

Comment (MichaelBuessemeyer) [reply frontend/javascripts/oxalis/view/settings/dataset_settings_view.js]: 🙈
