### PR TITLE
Auto correct dataset name in view URL

### LINKED ISSUE #8238: Update dataset name in url when incorrect upon loading dataset in view mode
## Detailed Description

Due to the new renamable DS and new URI DS addressing schema it is possible to have valid links like https://webknossos.org/datasets/blablabla-<id>/view. WEBKNOSSOS should take care of setting the correct name after long such a dataset in view mode (and other links that use this addressing schema :))

For reference: https://scm.slack.com/archives/C5AKLAV0B/p1732718191614449?thread_ts=1732717609.114699&cid=C5AKLAV0B

### PR DESCRIPTION
**Pull request by MichaelBuessemeyer**
This PR adds changes so that the model init auto corrects wrong / outdated dataset names in view URLs. 

Moreover, the new `selectiveSegmentVisibility` setting is now supported in the settings and thus not listed as "undefined" in the "Save view configuration as default" modal.

Reason: The changes in `frontend/javascripts/messages.tsx` are responsible for the following auto generated text in the "Save view configuration as default" modal no longer containing an "undefined" as a last element of `additionalData`. See where `settings["selectiveSegmentVisibility"]` is used:
https://github.com/scalableminds/webknossos/blob/403e751310ac6341726b93af6872cf1b3c7d6bfc/frontend/javascripts/oxalis/view/left-border-tabs/layer_settings_tab.tsx#L1359-L1377

### URL of deployed dev instance (used for testing):
- https://fixdefaultviewconfigs.webknossos.xyz

### Steps to test:
- View a dataset. In the left settings click the "Save view configuration as default" button. In the modal there should no longer be undefined at the end of the listed properties which are saved.
- View a dataset. In the URL change the part that is the dataset name to something else like `wrong_name` or so and load this link. After wk is loaded, the URL should be adjusted to have the correct dataset name in it. Compare with master. This behavior should not happen there 
- Do the same again with a name including a  `-` like `wrong-name`. This should still work.

### Issues:
- fixes #8238

------
(Please delete unneeded items, merge only when none are left open)
- [x] Updated [changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)

### CODE REVIEW

**Comment by MichaelBuessemeyer** [comment]
@philippotto I switched to request a review from @daniel-wer as you seem to currently have a lot of work already. Hope that's alright

File: frontend/javascripts/messages.tsx [hunk 1]
```diff
@@ -81,6 +82,8 @@ export const settingsTooltips: Partial<Record<keyof RecommendedConfiguration, st
   antialiasRendering: "Antialias rendering (can impact performance)",
   colorLayerOrder:
     "Set the order in which color layers are rendered. This setting is only relevant if the cover blend mode is active.",
+  selectiveSegmentVisibility:
+    "When enabled, only the active segment the the hovered segments are visible.",
```
Comment (daniel-wer) [inline frontend/javascripts/messages.tsx:86]:
```suggestion
    "When enabled, only the active and hovered segments are visible.",
```

File: frontend/javascripts/test/model/model.spec.ts [hunk 2]
```diff
@@ -37,6 +38,37 @@ const ErrorHandling = {
 mockRequire("libs/toast", {
   error: _.noop,
 });
+/*const viewLocation = {
```
Comment (daniel-wer) [inline frontend/javascripts/test/model/model.spec.ts:41]: Can this be removed?

**Review by daniel-wer — COMMENTED** [review]
Mostly looks good, but I'd love to see a unit test for the url extraction logic.

Also, I remember there being sandbox urls - do we need to worry about those as well?

File: frontend/javascripts/oxalis/controller/url_manager.ts [hunk 3]
```diff
@@ -76,6 +76,30 @@ function mapMeshInfoToUrlMeshDescriptor(meshInfo: MeshInformation): MeshUrlDescr
...
+export function getUpdatedPathnameWithNewDatasetName(
+  location: (typeof window)["location"],
+  dataset: APIDataset,
+): string {
+  const pathnameParts = location.pathname.split("/").slice(1); // First string is empty as pathname start with a /.
+  const newNameAndIdPart = `${dataset.name}-${dataset.id}`;
+  const newPathname = `/${pathnameParts[0]}/${newNameAndIdPart}/${pathnameParts.slice(2).join("/")}`;
+  return newPathname;
+}
+
```
Comment (MichaelBuessemeyer) [inline frontend/javascripts/oxalis/controller/url_manager.ts:102]: Not sure where to put these extracted functions. Do you have a suggestion?

**Review by MichaelBuessemeyer — COMMENTED** [review]
Thanks for your feedback :pray: 

I extracted the functionallity into two functions and tested them. Please give it another look :eyes:

File: frontend/javascripts/oxalis/controller/url_manager.ts [hunk 4]
```diff
@@ -76,6 +76,30 @@ function mapMeshInfoToUrlMeshDescriptor(meshInfo: MeshInformation): MeshUrlDescr
   }
 }
 
+// extracts the dataset name from view or sandbox the URLs.
+export function getDatasetNameFromLocation(
+  location: (typeof window)["location"],
+): string | undefined {
+  // URL format: /datasets/<dataset-name>-<dataset-id>/<view|sandbox/type>...
+  const pathnameParts = location.pathname.split("/").slice(1); // First string is empty as pathname start with a /.
+  const endOfDatasetName = pathnameParts[1].lastIndexOf("-");
```
[the remark this answers is not in the document]
Comment (MichaelBuessemeyer) [reply frontend/javascripts/oxalis/controller/url_manager.ts:83]: Yes, that's how it should be :+1:. For safety I just double checked the code and can confirm it.

**Review by MichaelBuessemeyer — COMMENTED** [review]
Nice, thanks for the feedback and being picky regarding the test cases. I was a litlle lazy there :see_no_evil: 

Should be better now :D

**Review by daniel-wer — APPROVED** [review]
Thank you, LGTM! :+1:
