### PR TITLE
Fix some sql queries: update tracing reference and update user dataset config

### LINKED ISSUE #2417: user dataset configurations: duplicate key
…was found in mhlab logs, should be investigated

### PR DESCRIPTION
**Pull request by fm3**
* fixed updating an annotation’s tracing reference (used e.g. for revertToBase)
* running the queries for changing user dataset configurations transactionally, hopefully avoiding race conditions that lead to duplicate key errors
* removed an unused method

### Steps to test:
- change user dataset configuration (like dataset brightness), reload, should still be there
- reset an annotation to its base (`/api/annotations/:typ/:id/reset`), should now work

### Issues:
- fixes #2417

------
- [x] Ready for review

### CODE REVIEW

File: app/models/user/User.scala [hunk 1]
```diff
@@ -253,12 +253,12 @@ object UserDataSetConfigurationsSQLDAO extends SimpleSQLDAO {
   def updateDatasetConfigurationForUserAndDataset(userId: ObjectId, dataSetId: ObjectId, configuration: Map[String, JsValue])(implicit ctx: DBAccessContext): Fox[Unit] = {
     for {
       _ <- UserSQLDAO.assertUpdateAccess(userId)
-      _ <- run(
-        sqlu"""delete from webknossos.user_dataSetConfigurations
-               where _user = ${userId.id} and _dataSet = ${dataSetId.id}""")
-      _ <- run(
-        sqlu"""insert into webknossos.user_dataSetConfigurations(_user, _dataSet, configuration)
-               values(${userId.id}, ${dataSetId.id}, '#${sanitize(Json.toJson(configuration).toString)}')""")
+      _ <- Fox.successful(println("delete"))
```
Comment (jfrohnhofen) [inline app/models/user/User.scala]: do you want to keep this in production?

File: app/models/annotation/AnnotationService.scala [hunk 2]
```diff
@@ -189,14 +189,6 @@ object AnnotationService
     } yield true
   }
 
-  def updateAnnotationBase(task: Task, newTracingRefernce: TracingReference)(implicit ctx: DBAccessContext) = {
```
Comment (jfrohnhofen) [inline app/models/annotation/AnnotationService.scala]: Is this dead code?

File: app/models/annotation/Annotation.scala [hunk 3]
```diff
@@ -247,7 +247,7 @@ object AnnotationSQLDAO extends SQLDAO[AnnotationSQL, AnnotationsRow, Annotation
   def updateTracingReference(id: ObjectId, tracing: TracingReference)(implicit ctx: DBAccessContext): Fox[Unit] =
     for {
       _ <- assertUpdateAccess(id)
-      _ <- run(sqlu"update webknossos.annotations set tracingId = ${tracing.id}, tracingTyp = '#${tracing.typ.toString}' where _id = ${id.id}")
+      _ <- run(sqlu"update webknossos.annotations set tracing_id = ${tracing.id}, tracingTyp = '#${tracing.typ.toString}' where _id = ${id.id}")
```
Comment (jfrohnhofen) [inline app/models/annotation/Annotation.scala]: Don't we have to update the schema as well?

Comment (fm3) [reply app/models/annotation/Annotation.scala]: no, it only now matches the schema, this was a bug in the code

File: app/models/annotation/AnnotationService.scala (hunk 2 above)
Comment (fm3) [reply app/models/annotation/AnnotationService.scala]: yes, no usages found

File: app/models/user/User.scala (hunk 1 above)
Comment (fm3) [reply app/models/user/User.scala]: oops, fixed
