### PR TITLE
Turning off recording when leaving arbitrary modes

### LINKED ISSUE #4164: BUG Flight Mode not resetting to "Watching"
### Problem Description
If switching from flight mode (while recording status = True) to orthogonal mode, moving view port some distance away from original point and coming back to flight mode (while recording status still True) nodes are created automatically.

### Way to reproduce
1. Set some nodes in flight mode. (Recording = True)
2. Switch to orthogonal mode.
3. Move viewport some nanometers away from original point.
4. Switch back to orthogonal mode. --> a new node appears in the middle of view port.
If this procedure is done while flight mode is in watching mode (not recording), then no new nodes are created.

See https://discuss.webknossos.org/t/flight-mode-auto-recording-after-switching-from-orthogonal-mode/1508/2

### PR DESCRIPTION
**Pull request by MichaelBuessemeyer**
This PR automatically turns off recording when switching from arbitrary mode to orthogonal mode.
This solves the issue when having recording enabled and then switching to orthogonal, moving around and then switching back to any arbitrary view mode a new node is created instantly.
Now the user has to turn on the recording on changing back to any arbitrary mode.

### URL of deployed dev instance (used for testing):
- https://turnoffrecordinginorthogonal.webknossos.xyz

### Steps to test:
- Open a skeleton capable tracing and go to any arbitrary view mode. 
- Try out whether the bug still exists. A way to reproduce is (copied from issue #4164):
1. Set some nodes in flight mode. (Recording = True)
2. Switch to orthogonal mode.
3. Move viewport some nanometers away from the original point.
4. Switch back to orthogonal mode. --> a new node appears in the middle of the viewport.
If this procedure is done while flight mode is in watching mode (not recording), then no new nodes are created.

### Issues:
- fixes #4164

------
- [x] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)
- ~~[ ] Updated [migration guide](../blob/master/MIGRATIONS.md#unreleased) if applicable~~
- ~~[ ] Updated [documentation](../blob/master/docs) if applicable~~
- ~~[ ] Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes~~
- ~~[ ] Needs datastore update after deployment~~
- [x] Ready for review

### CODE REVIEW

File: frontend/javascripts/oxalis/view/action-bar/view_modes_view.js [hunk 1]
```diff
@@ -1,26 +1,46 @@
...
+type Props = {| ...StateProps, ...DispatchProps |};
+
 class ViewModesView extends PureComponent<Props, {}> {
   blurElement = (event: SyntheticInputEvent<>) => {
     event.target.blur();
   };
 
   handleChange = (mode: ViewMode) => {
+    // If we switch back from any arbitrary mode we stop recording.
+    // This prevents that when the user switches back to any flightmode,
```
Comment (daniel-wer) [inline frontend/javascripts/oxalis/view/action-bar/view_modes_view.js]:
```suggestion
    // This prevents that when the user switches back to any arbitrary mode,
```

File: frontend/javascripts/oxalis/view/action-bar/view_modes_view.js [hunk 2]
```diff
@@ -1,26 +1,46 @@
...
+    // a new node is instantly created at the screens center.
```
Comment (daniel-wer) [inline frontend/javascripts/oxalis/view/action-bar/view_modes_view.js]:
```suggestion
    // a new node is instantly created at the screen's center.
```

File: CHANGELOG.md [hunk 3]
```diff
@@ -17,6 +17,7 @@ For upgrade instructions, please check the [migration guide](MIGRATIONS.md).
 ### Changed
 - Volume project download zips are reorganized to contain a zipfile for each annotation (that in turn contains a data.zip and an nml file). [#4167](https://github.com/scalableminds/webknossos/pull/4167)
 - Team managers and admins can now get tasks that they had previously cancelled. [#4088](https://github.com/scalableminds/webknossos/pull/4088)
+- Automatically turning off recording for arbitrary modes when switching to orthogonal mode to prevent accidental creation of nodes when switching back to any arbitrary mode. [#4211](https://github.com/scalableminds/webknossos/pull/4211)
```
Comment (daniel-wer) [inline CHANGELOG.md]: `Arbitrary mode` is probably hard to understand for our users, let's use the terms they know from the UI :)

```suggestion
- Recording is now automatically turned off when switching from flight/oblique to orthogonal mode to prevent accidental node creation when switching back later. [#4211](https://github.com/scalableminds/webknossos/pull/4211)
```
