### PR TITLE
Fix skeleton name width while editing 

### LINKED ISSUE #8417: Renaming a tree (or segment) shows text box that is too small
## Context
Renaming a tree or segment with a long name.
https://scm.slack.com/archives/C5AKLAV0B/p1740681574704059
https://discuss.webknossos.org/t/new-ui-for-editing-tree-names/1900

## Expected Behavior
After double clicking a tree, the text box should at least be of the same size as the label that was shown before.

## Current Behavior
the text box is too small.

## Steps to Reproduce the bug

- [ ] Cannot reproduce the bug anymore / needs deeper investigation.

1. create a tree with a long name
2. double click it

### PR DESCRIPTION
**Pull request by hotzenklotz**
Fixed an issue where the text input while renaming a skeleton tree or segment did not use the full width of the right-hand sidebar. This made it really hard to edit long names.

Tested with:
- Chrome on Mac
- FireFox on Mac
- Safari on Mac

Screenshot 2025-03-25 at 15 44 50
Screenshot 2025-03-25 at 15 45 04
Screenshot 2025-03-25 at 15 45 15
Screenshot 2025-03-25 at 15 45 56

### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
1. Create an annotation
2. Create some trees
3. Rename the tree name to something really long. 
    - The text input when editing should be fully width
    - The tree name should text wrap when not editing
4. Create some segments and renamed them. Should have the same behavior as trees.
5. Resize your right-hand sidebar and check for responsiveness

### Issues:
- fixes #8417

------
(Please delete unneeded items, merge only when none are left open)
- [ ] Updated [changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)
- [ ] Updated [migration guide](../blob/master/MIGRATIONS.unreleased.md#unreleased) if applicable
- [ ] Updated [documentation](../blob/master/docs) if applicable
- [ ] Adapted [wk-libs python client](https://github.com/scalableminds/webknossos-libs/tree/master/webknossos/webknossos/client) if relevant API parts change
- [ ] Removed dev-only changes like prints and application.conf edits
- [ ] Considered [common edge cases](../blob/master/.github/common_edge_cases.md)
- [ ] Needs datastore update after deployment

### CODE REVIEW

File: frontend/javascripts/oxalis/view/components/editable_text_label.tsx [hunk 1]
```diff
@@ -163,31 +163,27 @@ class EditableTextLabel extends React.PureComponent<EditableTextLabelProp, State
...
-            </React.Fragment>
-          ) : (
-            <MarkdownModal
-              source={this.state.value}
-              isOpen={this.state.isEditing}
-              onChange={this.handleInputChange}
-              onOk={this.handleOnChange}
-              label={this.props.label}
+      return this.props.rows === 1 ? (
+        <Space.Compact block>
```
Comment (hotzenklotz) [inline frontend/javascripts/oxalis/view/components/editable_text_label.tsx:167]: replace outer `<span>` and `<React.Fragement>` with `<Space>`. The rest is identical.

**Review by philippotto — APPROVED** [review]
great, works very well :candy:
