### PR TITLE
Fix the floodfill notification dismissal

### LINKED ISSUE #9176: Dismissing floodfill notification does not work
## Context
When doing a flood fill operation in annotation, there is a small UI notification to let users know about the progress and result of the operation. In some cases this notification must be explicitly dismissed by the user, e.g. when a flood fill operation terminates but did not finish due too size constraints. Clicking on the `Close` "button" does not work.

Image

## Expected Behavior
Clicking close should dismiss the notification

## Current Behavior
Clicking close does not dismiss the notification. Rather it triggers a browser page navigation because the `Close` link adds a `#` to the URI.

## Steps to Reproduce the bug
1. Open annotation
2. Trigger a large flood fill operation that exceeds the size constrains. Notification will show
3. Click "Close" to dismiss
4. Kaboom

### PR DESCRIPTION
**Pull request by hotzenklotz**
PR fixes an issue where notification during a flood fill operation could not be dismissed.

### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- Open annotation
- Do a huge flood-fill that prematurely finishes and displays a notification
- Dismiss the notification by clicking the "Close" button

### Issues:
- fixes #9176 

------
(Please delete unneeded items, merge only when none are left open)
- [x] Added changelog entry (create a `$PR_NUMBER.md` file in `unreleased_changes` or use `./tools/create-changelog-entry.py`)
- [ ] Added migration guide entry if applicable (edit the same file as for the changelog)
- [ ] Updated [documentation](../blob/master/docs) if applicable
- [ ] Adapted [wk-libs python client](https://github.com/scalableminds/webknossos-libs/tree/master/webknossos/webknossos/client) if relevant API parts change
- [ ] Removed dev-only changes like prints and application.conf edits
- [ ] Considered [common edge cases](../blob/master/.github/common_edge_cases.md)
- [ ] Needs datastore update after deployment

### CODE REVIEW

File: frontend/javascripts/viewer/view/novel_user_experiences/welcome_toast.tsx [hunk 1]
```diff
@@ -6,7 +6,7 @@ import UserLocalStorage from "libs/user_local_storage";
 import defaultsDeep from "lodash/defaultsDeep";
 import { ColorWKBlueZircon, getAntdTheme } from "theme";
 
-const lightThemeWithCyanButton = defaultsDeep(
+const darkThemeWithCyanButton = defaultsDeep(
```
Comment (hotzenklotz) [inline frontend/javascripts/viewer/view/novel_user_experiences/welcome_toast.tsx:9]: Unrelated change. Just a renaming. I overlooked a comment in in PR #9174 about that.

**Review by philippotto — APPROVED** [review]
🥇
