### PR TITLE
Fix sorting in antd dataset table

### LINKED ISSUE #4292: Sorting in tables seems to be broken
At least, the datasets table in the dashboard cannot be sorted anymore under Chrome and Firefox.

### PR DESCRIPTION
**Pull request by philippotto**
### URL of deployed dev instance (used for testing):
- https://fixsort.webknossos.xyz

### Steps to test:
- sort dataset table and also make use of the expand/collapse feature (the sticky action column should turn un-sticky if something is expanded)

### Issues:
- fixes #4292 

------
- [x] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)
- ~[ ] Updated [migration guide](../blob/master/MIGRATIONS.md#unreleased) if applicable~
- ~[ ] Updated [documentation](../blob/master/docs) if applicable~
- ~[ ] Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes~
- ~[ ] Needs datastore update after deployment~
- [X] Ready for review

### CODE REVIEW

File: frontend/javascripts/oxalis/view/action-bar/tracing_actions_view.js [hunk 1]
```diff
@@ -287,7 +287,7 @@ class TracingActionsView extends React.PureComponent<Props, State> {
               key="sandbox-tooltip"
             >
               <Button disabled type="primary" icon="code-sandbox">
-                Sandbox
+                <span className="hide-on-small-screen">Sandbox</span>
```
Comment (daniel-wer) [inline frontend/javascripts/oxalis/view/action-bar/tracing_actions_view.js]: :+1:
