### PR TITLE
Fix tree sorting in tracing view

### LINKED ISSUE #2376: Tree sequence inconsistent
https://discuss.webknossos.org/t/tree-sequence-inconsistent/755

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2376/create?referer=github" target="_blank">Log Time</a>

### PR DESCRIPTION
**Pull request by philippotto**
Apparently, antd's menu only works with onClick even though the documentation says otherwise :thinking: 

It's not clear whether this completely resolves #2376, since the inconsistency could not be reproduced yet (I think it was always sorted by creation time).

### Mailable description of changes:
 - Sorting trees by creation time or name works again

### Steps to test:
- Load a tracing with a few trees and sort them by creation time and name

### Issues:
- contributes to #2376 

------
- [X] Ready for review

### CODE REVIEW

File: app/assets/javascripts/oxalis/view/right-menu/trees_tab_view.js [hunk 1]
```diff
@@ -130,9 +130,9 @@ class TreesTabView extends React.PureComponent<Props, State> {
     const activeMenuKey = this.props.userConfiguration.sortTreesByName
       ? "sortByName"
       : "sortByTime";
-
+    console.log("activeMenuKey", activeMenuKey);
```
Comment (normanrz) [inline app/assets/javascripts/oxalis/view/right-menu/trees_tab_view.js]: console?
