### PR TITLE
Fix S3 deletion for buckets/endpoints other than what’s configured for upload

### LINKED ISSUE #9043: s3 dataset delete should work on all buckets with global credentials
Currently it works only for the credentials that match the selected `s3Upload.credentialName`

### PR DESCRIPTION
**Pull request by fm3**
We can have multiple managed s3 stores. Only one is selected for upload but dataset deletion should work for all of them. This PR refactors the ManagedS3Service a bit and selects the correct client with endpoint/credential for each path.

### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
(I already tested locally, no need to re-test)
- In application.conf, insert multiple dataVaults.credentials for s3 endpoints. Set s3Upload.credentialName to the first of them
- Upload a small dataset
- set the s3Upload.credentialName to another of them
- make sure both datasets can be loaded
- delete both datasets from their respective settings views.
- backend logging should show they were deleted from their respective s3 buckets

### Issues:
- follow-up for #8924 
- fixes #9043

------
- [x] Added changelog entry (create a `$PR_NUMBER.md` file in `unreleased_changes` or use `./tools/create-changelog-entry.py`)
- [x] Removed dev-only changes like prints and application.conf edits
- [x] Considered [common edge cases](../blob/master/.github/common_edge_cases.md)
- [x] Needs datastore update after deployment

### CODE REVIEW

File: webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/ManagedS3Service.scala [hunk 1]
```diff
@@ -25,24 +29,44 @@ import scala.concurrent.ExecutionContext
...
+class ManagedS3Service @Inject()(config: DataStoreConfig) extends FoxImplicits with LazyLogging {
 
-  private lazy val s3UploadCredentialsOpt: Option[(String, String)] =
-    dataStoreConfig.Datastore.DataVaults.credentials.flatMap { credentialConfig =>
+  def pathIsInManagedS3(path: UPath): Boolean =
+    path.getScheme.contains(PathSchemes.schemeS3) && globalCredentials.exists(c =>
+      UPath.fromString(c.name).map(path.startsWith).getOrElse(false))
+
+  def findGlobalCredentialFor(pathOpt: Option[UPath]): Option[S3AccessKeyCredential] =
+    pathOpt.flatMap(findGlobalCredentialFor)
```
Comment (MichaelBuessemeyer) [inline webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/ManagedS3Service.scala:39]: just a suggestion: Maybe move this next to the other findGlobalCredentialFor implementation?

File: webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/ManagedS3Service.scala [hunk 2]
```diff
@@ -89,13 +113,19 @@ class ManagedS3Service @Inject()(dataStoreConfig: DataStoreConfig) extends FoxIm
       implicit ec: ExecutionContext): Fox[Unit] =
     for {
       bucket <- bucketOpt.toFox ?~> "Could not determine S3 bucket from UPath"
-      s3Client <- s3ClientBox.toFox ?~> "No managed s3 client configured"
+      firstPath <- paths.headOption.toFox // groupBy of the caller guarantees that this is not called with empty list.
+      credential <- findGlobalCredentialFor(firstPath).toFox // Convention is that the credentials are per bucket, so we can reuse this for all paths
+      endpoint = endpointForCredentialName(credential.name)
+      s3client <- buildClient(endpoint, credential).toFox
```
Comment (MichaelBuessemeyer) [inline webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/ManagedS3Service.scala]: mini typo: `s3client` -> `s3Client`. Or was this on purpose? At least the old code used  `s3Client`

**Review by MichaelBuessemeyer — APPROVED** [review]
Testing went well :+1:

> - In application.conf, insert multiple dataVaults.credentials for s3 endpoints. Set s3Upload.credentialName to the first of them
> - Upload a small dataset
> - set the s3Upload.credentialName to another of them
> - make sure both datasets can be loaded
> - delete both datasets from their respective settings views.
> - backend logging should show they were deleted from their respective s3 buckets


regarding: 
> - delete both datasets from their respective settings views.

I didn't delete on the second bucket but made this manually as this wasn't a testing bucket. I felt safer this way. But deleting on the not aas upload configured bucket worked. So imo the whole PR works :+1:

Thanks for fixing this :)
