### PR TITLE
Dont brush outside viewport

### LINKED ISSUE #3128: Don't draw outside of viewport in volume tracing
Currently it is possible to draw beyond the boundary of a plane with the brush tool in volume tracing. 
Additionally when moving the brush/cursor out of the plane into the direction of another plane it "resets its position". => for XY it is moving to the right and bottom, for YZ to the left and for XZ it is moving the brush to the top

=> How to reproduce: open volume tracing and select the brush tool. Then paint in the e.g. XY plane a line to the left and move the cursor to the left border of the YZ plane. The brush should reset to the left border of the XY plane when you reach the right border of the XY plane. 
After that follow the line you just drew -> it should go "far" beyond the border of the XY plane. I think this is unintended behavior.

=> maybe split this into two issues, but these bugs seem related.

### PR DESCRIPTION
**Pull request by MichaelBuessemeyer**
This PR disables drawing out of bounds of a viewport

### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- open volumetracing
- draw with the brush around the boundaries 
- move around to check that drawing stopped when drawing out of bounds
- there should not be noticeable difference in performance compared to the previous drawing 

### Issues:
- fixes  #3128

------
- [x] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)
- ~~~[ ] Updated [migration guide](../blob/master/MIGRATIONS.md#unreleased) if applicable~~~
- ~~~[ ] Updated [documentation](../blob/master/docs) if applicable~~~
- ~~~[ ] Needs datastore update after deployment~~~
- [x] Ready for review

### CODE REVIEW

File: app/assets/javascripts/oxalis/model/volumetracing/volumelayer.js [hunk 1]
```diff
@@ -35,29 +37,59 @@ export class VoxelIterator {
...
   ) {
     this.map = map;
     this.width = width;
     this.height = height;
     this.minCoord2d = minCoord2d;
     this.get3DCoordinate = get3DCoordinate;
-    if (!this.map[0][0]) {
+    this.boundingBox = boundingBox;
+    const firstCoordinate = this.get3DCoordinate([this.minCoord2d[0], this.minCoord2d[1]]);
+    if (!this.map[0][0] || !this.isCoordinateInBounds(firstCoordinate)) {
```
Comment (philippotto) [inline app/assets/javascripts/oxalis/model/volumetracing/volumelayer.js]: Can you invert the if condition and switch the body and else block. In my opinion, that's easier to read. So, it would be something like:

```
if (map[0][0] != null && isInBounds...) {
  this.next = firstCoordinate;
} else {
  this.getNext();
}
```

**Comment by MichaelBuessemeyer** [comment]
@philippotto This PR is ready for another review :smiley:
