### PR TITLE
in task deletion, also delete its annotations

### LINKED ISSUE #2873: task deletion should delete its annotations
when you delete a task that a user has already worked on, the user can’t list their task annotations anymore because the lookup fails.
This behavior was apparently lost in #2676

### PR DESCRIPTION
**Pull request by fm3**
### URL of deployed dev instance (used for testing):
- https://deletetaskannotations.webknossos.xyz

### Steps to test:
- create task
- request it, leave it active
- delete the task in the admin view
- task list in dashboard should not throw error, but rather show your other tasks, but no longer that one

### Issues:
- fixes #2873

------
- [x] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)
- [x] Updated [migration guide](../blob/master/MIGRATIONS.md#unreleased) if applicable
- [x] Ready for review

### CODE REVIEW

File: app/controllers/TaskController.scala [hunk 1]
```diff
@@ -223,7 +223,7 @@ class TaskController @Inject() (val messagesApi: MessagesApi)
       task <- TaskSQLDAO.findOne(taskIdValidated) ?~> Messages("task.notFound")
       project <- task.project
       _ <- ensureTeamAdministration(request.identity, project._team) ?~> Messages("notAllowed")
-      _ <- TaskSQLDAO.deleteOne(task._id)
```
Comment (philippotto) [inline app/controllers/TaskController.scala]: Is the `deleteOne` method defined by some abstraction? From my understanding, this method would always lead to inconsistencies, right? Can we forbid it or bake the functionality of `removeOneAndItsAnnotations` in?
