### PR TITLE
Fix single file uploads 

### LINKED ISSUE #4963: Error uploading dataset zip: directory exists
when uploading a dataset zip (for conversion in this case) I got “is a directory” errors. I think ZipIO.unzipToFolder creates the directory, but there’s a `ensureDirectory` before that in `finishUpload` – why did that ever work? Do you have an idea @youri-k ?

### PR DESCRIPTION
**Pull request by youri-k**
### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- upload zip with only file and no empty directories => should now work

### Issues:
- fixes #4963 

------
- [x] Updated [(unreleased) changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)
- ~~[ ] Updated [(unreleased) migration guide](../blob/master/MIGRATIONS.unreleased.md#unreleased) if applicable~~
- ~~[ ] Updated [documentation](../blob/master/docs) if applicable~~
- ~~[ ] Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes~~
- [x] Needs datastore update after deployment
- [x] Ready for review

### CODE REVIEW

File: webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/UploadService.scala [hunk 1]
```diff
@@ -125,6 +124,8 @@ class UploadService @Inject()(dataSourceRepository: DataSourceRepository, dataSo
             dataSourceRepository.updateDataSource(
               dataSourceService.dataSourceFromFolder(dataSourceDir, dataSourceId.team))
         case e =>
+          // TODO check whether this is too aggressive
+          PathUtils.deleteDirectoryWithContents(dataSourceDir)
```
Comment (youri-k) [inline webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/UploadService.scala:128]: While testing this PR, I noticed that the Dataset is still reported to wk because of the empty directory that remains after the unsuccessful unzipping. Therefore, I created this method to delete the erroneous `dataSourceDir`, but maybe this too aggressive :thinking:

Comment (youri-k) [reply webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/UploadService.scala:128]: I think this could already solve #4971. I will move the code there and another request to wk to remove the dataset from the db if the unzipping fails. Additionally, we should think about "reserving" the name already for the first request, so similar named datasets fail early and not only in the `finishUpload` request.

File: util/src/main/scala/com/scalableminds/util/io/ZipIO.scala [hunk 2]
```diff
@@ -169,30 +165,35 @@ object ZipIO extends LazyLogging {
...
     val commonPrefix = if (truncateCommonPrefix) {
       val commonPrefixNotFixed = PathUtils.commonPrefix(zipEntries.map(e => Paths.get(e.getName)))
-      val strippedPaths = excludeFromPrefix.getOrElse(List()).flatMap(stripPathFrom(commonPrefixNotFixed, _))
-      strippedPaths.headOption match {
-        case Some(path) => path
-        case None       => commonPrefixNotFixed
+      val strippedPrefix = stripPathFrom(commonPrefixNotFixed, excludeFromPrefix.getOrElse(List.empty))
+      // if only one file is in the zip and no layer name is given as prefix, do not remove file name as common prefix
+      zipEntries match {
+        case head :: tl if tl.isEmpty && strippedPrefix.endsWith(Paths.get(head.getName).getFileName) =>
```
Comment (fm3) [inline util/src/main/scala/com/scalableminds/util/io/ZipIO.scala:194]: Maybe this logic can be extracted into a function? I think it’s fairly hard to read

File: util/src/main/scala/com/scalableminds/util/io/ZipIO.scala [hunk 3]
```diff
@@ -169,30 +165,35 @@ object ZipIO extends LazyLogging {
...
+        case -1 => path
+        // subpath(0, 0) is forbidden, therefore we handle this special case ourselves
+        case 0 => Paths.get("")
+        case i => path.subpath(0, i)
+      }
     }
 
     val zipEntries = zip.entries.asScala.filter(e => !e.isDirectory && (includeHiddenFiles || !isFileHidden(e))).toList
 
     //color, mask, segmentation are the values for dataSet layer categories and a folder only has one category
```
Comment (fm3) [inline util/src/main/scala/com/scalableminds/util/io/ZipIO.scala:188]: While we’re here, could you remove this comment? I don’t see what it’s good for in this place

File: webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/UploadService.scala (hunk 1 above)
Comment (fm3) [reply webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/UploadService.scala]: Cool that you looked into that already :) I think atually deleting is indeed too aggressive, as we may not be 100% certain that this is never wrongly triggered. I’d suggest moving to `.trash` instead (but still double-checking that this really only happens in the error case).
The other ideas sound good to me too, but, as you say, let’s do all of that in a separate PR

File: util/src/main/scala/com/scalableminds/util/io/ZipIO.scala [hunk 4]
```diff
@@ -169,30 +165,35 @@ object ZipIO extends LazyLogging {
...
-        else if (path.subpath(i, i + 1).toString.contains(string)) //sample paths: "test/test/color_1", "segmentation"
-          if (i == 0) // path.subpath(0,0) is invalid and means that there is no commonPrefix which isn't started with a layer
-            Some(Paths.get(""))
-          else // this is the common prefix but stripped from the layer
-            Some(path.subpath(0, i))
-        else
-          stripPathHelper(i + 1)
-
-      stripPathHelper(0)
+    def stripPathFrom(path: Path, excludeFromPrefix: List[String]): Path = {
```
Comment (fm3) [inline util/src/main/scala/com/scalableminds/util/io/ZipIO.scala:168]: Maybe the function could have a more descriptive name now

**Review by fm3 — COMMENTED** [review]
Mostly LGTM, please see my minor comments

**Review by fm3 — APPROVED** [review]
