### PR TITLE
Fix display-planes-in-3d-view

### LINKED ISSUE #3854: Planes in 3D viewport are shown regardless of setting
[Link to Discuss](https://discuss.webknossos.org/t/planes-in-3d-viewport-are-shown-regardless-of-setting/1401)

### PR DESCRIPTION
**Pull request by philippotto**
### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- toggle "display planes in 3d viewport" and also make the viewports (dis)appear via tab management

### Issues:
- fixes #3854 

------
- [x] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)
- [x] Ready for review

### CODE REVIEW

File: frontend/javascripts/oxalis/controller/scene_controller.js [hunk 1]
```diff
@@ -316,12 +315,13 @@ class SceneController {
         }
       }
     } else {
+      const { tdViewDisplayPlanes } = Store.getState().userConfiguration;
```
Comment (daniel-wer) [inline frontend/javascripts/oxalis/controller/scene_controller.js]: Does changing the user setting trigger a render? Otherwise I would have expected that the setting change will only be applied after the user moved or so.

Comment (philippotto) [reply frontend/javascripts/oxalis/controller/scene_controller.js]: Yes, it still updates when just toggling the setting. I think store changes in general trigger a re-render.
