### PR TITLE
Dont crash job list for unknown jobs

### LINKED ISSUE #8066: Don't crash job list for unknown jobs and improve infer_with_model rendering
[Context](https://scm.slack.com/archives/C02H5T8Q08P/p1726048468858569?thread_ts=1726040192.550629&cid=C02H5T8Q08P)

### PR DESCRIPTION
**Pull request by knollengewaechs**
### Steps to test:
- Go to "Processing Jobs" page
- Make sure the test_me job (inserted in the code to mock a job of an unknown type) looks okay and does not crash the page
- Only unknown job types should have snake cased job descriptions -> look at train_model and infer_with_model jobs and make sure the new description is useful
- for train_model jobs, check clicking the training annotations

### TODOs:
- [x] improve wording for all job descriptions:
    - [x] maybe include "Show Training Data"
    - [x] use present tense everywhere
    - [x] infer_with_model: "AI segmentation"
    - [x] show "result" for unknown jobs if they have a result link

### Issues:
- fixes #8066

------
(Please delete unneeded items, merge only when none are left open)
- [x] :exclamation: Removed dev-only changes like prints and application.conf edits :exclamation: 
- [x] Updated [changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)
- [ ] Updated [migration guide](../blob/master/MIGRATIONS.unreleased.md#unreleased) if applicable
- [ ] Updated [documentation](../blob/master/docs) if applicable
- [ ] Adapted [wk-libs python client](https://github.com/scalableminds/webknossos-libs/tree/master/webknossos/webknossos/client) if relevant API parts change
- [ ] Considered [common edge cases](../blob/master/.github/common_edge_cases.md)
- [ ] Needs datastore update after deployment

### CODE REVIEW

File: frontend/javascripts/admin/api/jobs.ts [hunk 1]
```diff
@@ -42,14 +42,51 @@ function transformBackendJobToAPIJob(job: any): APIJob {
...
+        mag: [16, 16, 4],
+        annotationId: "6756bfe9b2a1008da7dfa218",
+        colorLayerName: "color",
+        segmentationLayerName: "segmentation",
+      },
+    ],
+    state: "SUCCESS",
+    manualState: null,
+    result: "This was such a huge success",
+    resultLink:
```
Comment (knollengewaechs) [inline frontend/javascripts/admin/api/jobs.ts:78]: remove me

Comment (knollengewaechs) [reply frontend/javascripts/admin/api/jobs.ts:78]: job.ts should not have any changes.

**Review by philippotto — APPROVED** [review]
cool, lgtm :) don't forget to remove the dev-related code.
