### PR TITLE
Re-enable continuous brush and fix perf + edge-case bugs

### LINKED ISSUE #4859: Re-enable continuous brushing
When I merged the code changes from the continuous brushing feature into the multiresolution pr (https://github.com/scalableminds/webknossos/pull/4755), I might have broken something. At least, the performance was considerably poorer (which I didn't notice on `master`). To reduce the complexity of the already quite big multi-res PR, I disabled that feature.

Let's re-enable it while doublechecking/debugging the performance

### LINKED ISSUE #4877: error when brushing into negative coordinates
if in a volume annotation I brush into negative coordinates, an error alert comes up:
```
Internal error.
Please reload the page to avoid losing data.

TypeError: k[e] is undefined S@main.js:1:380703
drawHorizontalLine2d
``'

### PR DESCRIPTION
**Pull request by philippotto**
I had disabled the continuous brushing feature after I merged it into the multi-res volume branch. One reason was performance and the other was an issue with the scale in higher mags (which was likely produced during the merge).
With this PR the continuous brush feature gets re-enabled. The scale-bug should be fixed now and I also fixed #4877. Additionally, I could greatly improve the performance by ensuring that the allocated buffer only covers the area from "min to max" (instead of from "0 to max"). This caused major problems for me since my dataset's origin wasn't at 0,0,0.

### URL of deployed dev instance (used for testing):
- https://fixcontinuousbrush.webknossos.xyz

### Steps to test:
- use the brush in a very quick manner
- brush in different mags

### Issues:
- fixes #4859 
- fixes #4877

------
- [x] Updated [(unreleased) changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)
- [ ] Updated [(unreleased) migration guide](../blob/master/MIGRATIONS.unreleased.md#unreleased) if applicable
- [ ] Updated [documentation](../blob/master/docs) if applicable
- [ ] Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes
- [ ] Needs datastore update after deployment
- [X] Ready for review

### CODE REVIEW

File: frontend/javascripts/oxalis/model/volumetracing/volumelayer.js [hunk 1]
```diff
@@ -289,17 +269,14 @@ class VolumeLayer {
     scale: Vector2,
   ): [number, number, number, number, number, number, number, number] {
     const normedPerpendicularVector = this.vector2PerpendicularVector(centre1, centre2);
-    const shiftVector = this.vector2WithScale(
-      this.vector2ScalarMultiplication(normedPerpendicularVector, radius),
-      scale,
-    );
-    const negShiftVector = this.vector2ScalarMultiplication(shiftVector, -1);
+    const shiftVector = V2.scale2(normedPerpendicularVector, V2.scale(scale, radius));
```
Comment (philippotto) [inline frontend/javascripts/oxalis/model/volumetracing/volumelayer.js:272]: This was the scale-related bug (the scale had to be applied to the radius).

File: frontend/javascripts/oxalis/model/volumetracing/volumelayer.js [hunk 2]
```diff
@@ -434,13 +416,13 @@ class VolumeLayer {
...
-          if (this.vector2DistanceWithScale(p1, p2, [scaleX, scaleY]) > 1.5 * radius) {
-            Drawing.fillRectangle(xa, ya, xb, yb, xc, yc, xd, yd, setMap);
-          }
+          // const [xa, ya, xb, yb, xc, yc, xd, yd] = this.getRectangleBetweenCircles(p1, p2, radius, [
+          //   scaleX / this.activeResolution[dimIndices[0]],
+          //   scaleY / this.activeResolution[dimIndices[1]],
+          // ]);
+          // if (this.vector2DistanceWithScale(p1, p2, [scaleX, scaleY]) > 1.5 * radius) {
+          //   Drawing.fillRectangle(xa, ya, xb, yb, xc, yc, xd, yd, setMap);
+          // }
```
Comment (philippotto) [inline frontend/javascripts/oxalis/model/volumetracing/volumelayer.js:425]: @daniel-wer At first I thought this code was wrong, since the rectangles should already have been drawn, but then I read that it's necessary for the implementation of the auto-fill-feature to work (since that code doesn't "know" about the rectangles which were drawn earlier?).
I'm a bit hesitant to keep this code here, as all rectangles are effectively drawn twice then. I wonder whether we should simply remove the auto-fill feature (especially, now that we have the paint-bucket-tool). What do you think? :see_no_evil:

**Review by philippotto — COMMENTED** [review]
By the way, I also experimented with a `BufferPool` to avoid frequent memory allocations. It looked somewhat like this:

```js
class BufferPool {
  unusedBuffers: Map<number, ArrayBuffer>;

  constructor() {
    this.unusedBuffers = new Map();
  }

  getUint8Array(size: number, fillValue: number = 0): { array: Uint8Array, release: () => void } {
    let buffer;
    // Divide size by 1024 and multiply from the outside with 1024, to make
    // one kiloByte the "smallest unit". Possible buffer sizes will be:
    // 1 kB, 2 kB, 4 kB, 8 kB, 16 kB etc.
    const roundedSize = 1024 * 2 ** Math.ceil(Math.log2(Math.ceil(size / 1024)));
    if (this.unusedBuffers.has(roundedSize)) {
      buffer = this.unusedBuffers.get(roundedSize);
      this.unusedBuffers.delete(roundedSize);
    } else {
      // console.log("Allocating buffer with", roundedSize);
      buffer = new ArrayBuffer(roundedSize);
    }

    const release = this._release.bind(this, buffer, roundedSize);

    return {
      array: new Uint8Array(buffer, 0, size).fill(fillValue),
      release,
    };
  }

  _release(buffer, roundedSize) {
    this.unusedBuffers.set(roundedSize, buffer);
  }
}
```

Unfortunately, I couldn't really measure any performance improvement or see less GC churn :man_shrugging: 

image

File: frontend/javascripts/oxalis/model/volumetracing/volumelayer.js (hunk 2 above)
Comment (daniel-wer) [reply frontend/javascripts/oxalis/model/volumetracing/volumelayer.js]: > At first I thought this code was wrong, since the rectangles should already have been drawn, but then I read that it's necessary for the implementation of the auto-fill-feature to work (since that code doesn't "know" about the rectangles which were drawn earlier?).

To explain the status quo: The key here is that only voxels that were drawn with _this_ brush stroke should affect whether an area is auto-filled or not. Therefore, the `contourList` which saves the coordinates of all brush events is used to recreate a map of the brushed voxels (and one cannot simply look up the voxels in the buckets). This map needs to mirror the brushed voxels exactly to allow for correct auto-fill which is why the circles and rectangles need to be redrawn from the `contourList`.

> I'm a bit hesitant to keep this code here, as all rectangles are effectively drawn twice then.

To avoid drawing twice, we could also remember the painted voxels for the current brush stroke (instead of only the coordinates of the brush events) and reuse these here for the auto-fill at the end of the brush stroke. I think you can estimate the best whether this would be easy/feasible with the current code, but I assume it's not that easy as we don't know the size of the map in advance :thinking:

> I wonder whether we should simply remove the auto-fill feature (especially, now that we have the paint-bucket-tool).

I probably wouldn't remove it for now, regardless of whether we change anything in this PR or did you notice performance problems related to the auto-fill?

File: frontend/javascripts/oxalis/model/volumetracing/volumelayer.js (hunk 1 above)
Comment (daniel-wer) [reply frontend/javascripts/oxalis/model/volumetracing/volumelayer.js:290]: Nice find!

File: frontend/javascripts/oxalis/model/volumetracing/volumelayer.js [hunk 3]
```diff
@@ -335,7 +335,7 @@ class VolumeLayer {
     );
     const minCoord2d = [Math.floor(Math.min(xa, xb, xc, xd)), Math.floor(Math.min(ya, yb, yc, yd))];
     const maxCoord2d = [Math.ceil(Math.max(xa, xb, xc, xd)), Math.ceil(Math.max(ya, yb, yc, yd))];
-    const [width, height] = maxCoord2d;
+    const [width, height] = V3.sub(maxCoord2d, minCoord2d);
```
Comment (daniel-wer) [inline frontend/javascripts/oxalis/model/volumetracing/volumelayer.js:338]: Also nice find! :open_mouth:

**Review by daniel-wer — APPROVED** [review]
Nice debugging and fixes! LGTM :+1:

**Comment by daniel-wer** [comment]
> By the way, I also experimented with a BufferPool to avoid frequent memory allocations.
Unfortunately, I couldn't really measure any performance improvement or see less GC churn man_shrugging

Hmm, interesting, could be that the browser already handles this efficiently for these kinds of (smaller?) allocations. Thinking about it, I would be somewhat surprised if a "general" buffer pooling strategy would outperform the memory management of the browser. I would expect it to be more performant if we use information that the browser does not have, though. For example when looking at our data buckets which for one layer all have the same size and where we know the maximum number of buffers that should be allocated, the pooling (we already do) probably has better performance than always allocating new buffers.
However, I am no expert in this and it could very well be that we can get rid of some of the gc pressure by re-using buffers cleverly. I would love to do a controlled deep-dive into the whole gc issue in the near future :)

File: frontend/javascripts/oxalis/model/volumetracing/volumelayer.js (hunk 2 above)
Comment (philippotto) [reply frontend/javascripts/oxalis/model/volumetracing/volumelayer.js]: Thank you for the summary! As we discussed in person, the current implementation of this PR restricts the auto-fill-feature by only kicking in if the start and end of the drawn "path" are so that the first and last brush circle are touching. The downside is that closing a circle and releasing the mouse somewhere else (e.g., when correcting some "bumps" in the outline or just when being a bit imprecise), won't trigger the auto-fill. However, the UI for that could also be improved by highlighting the start point and the "will perform auto-fill"-state.
In general, I think that the auto-fill-feature is not super crucial and would like to choose the more performant route. In case of negative feedback, we can re-think this :)

> did you notice performance problems related to the auto-fill?

Yes, when brushing a rather large area, there was a noticeable lag for me when releasing the brush :/ This felt especially weird to me, since everything was already brushed (the auto-fill-feature didn't fill anything) and no additional computation was necessary.

**Comment by philippotto** [comment]
> > By the way, I also experimented with a BufferPool to avoid frequent memory allocations.
> > Unfortunately, I couldn't really measure any performance improvement or see less GC churn man_shrugging
> 
> Hmm, interesting, could be that the browser already handles this efficiently for these kinds of (smaller?) allocations. Thinking about it, I would be somewhat surprised if a "general" buffer pooling strategy would outperform the memory management of the browser.

Yeah, that's probably the case. However, I thought that a very dumb pool might already help, since the typical usage pattern is very simple: acquire buffer, release buffer, acquire buffer, release buffer... Acquire and release should be super fast, since the same buffer is simply re-used in 99% of the cases. Therefore, I thought we could "buy" less GC pressure by reducing the memory efficiency (since the pool is very basic and potentially leaves lots of memory unused).

> [...], the pooling (we already do) probably has better performance than always allocating new buffers.

Which pooling are we already doing for bucket buffers?

> I would love to do a controlled deep-dive into the whole gc issue in the near future :)

Definitely, I'm all for that, too :)

**Comment by daniel-wer** [comment]
> Which pooling are we already doing for bucket buffers?

I mistakenly thought we were doing some kind of buffer reusing in the `data_cube.js:addBucketToGarbageCollection` function. However, this function only seems to ensure that a certain maximum number of buckets is never exceeded. I probably mixed this up with your proposal in https://github.com/scalableminds/webknossos/issues/3598 :)
