### PR TITLE
Communicate truncated 64 bit segmentation

### LINKED ISSUE #4492: Communicate to the user if 64 bit segmentation ids are truncated to 32 bit
If the user wants to pick ids in the segmentation tab, those IDs may be wrong if the segmentation was converted. This should be obvious to the user

### PR DESCRIPTION
**Pull request by youri-k**
### URL of deployed dev instance (used for testing):
- https://communicatetruncateduint.webknossos.xyz

### Steps to test:
- abc

### Issues:
- fixes #4492 

------
- [x] Updated [(unreleased) changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)
- ~~[ ] Updated [(unreleased) migration guide](../blob/master/MIGRATIONS.unreleased.md#unreleased) if applicable~~
- ~~[ ] Updated [documentation](../blob/master/docs) if applicable~~
- ~~[ ] Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes~~
- ~~[ ] Needs datastore update after deployment~~
- [x] Ready for review

### CODE REVIEW

**Comment by MichaelBuessemeyer** [comment]
@daniel-wer Would you please check the frontend part?

File: frontend/javascripts/oxalis/model_initialization.js [hunk 1]
```diff
@@ -433,10 +433,14 @@ function setupLayerForVolumeTracing(
   const fallbackLayerIndex = _.findIndex(layers, layer => layer.name === tracing.fallbackLayer);
   const fallbackLayer = layers[fallbackLayerIndex];
   const boundaries = getBoundaries(dataset);
+  // The frontend does not support uint64 data. Thus if the segmentation is uint64
+  // we treat it as uint32 and save that it originally has the element class uint64.
+  const isUint64Segmentation = tracing.elementClass === "uint64";
```
Comment (youri-k) [inline frontend/javascripts/oxalis/model_initialization.js:438]: What is `tracing.elementClass` referring to, the `elementClass` or the `originalElementClass`?
The backend converts an `elementClass` of `uint64` to `uint32`, so the `elementClass` value should never be `uint64`.
This is how we achieved the original cheap uint64 support [#4233](https://github.com/scalableminds/webknossos/pull/4233). If you want to, the backend can send the real `elementClass` to the frontend, which would mean we could rid of the `originalElementClass` in the backend.

Comment (fm3) [reply frontend/javascripts/oxalis/model_initialization.js:438]: this is in case of volume tracings (as opposed to view mode). the tracing still sends the uint64.
but yeah, feel free to unify this in whichever way seems best :)

Comment (fm3) [reply frontend/javascripts/oxalis/model_initialization.js:438]: I think we need to be extra careful before allowing 64 bit volume tracings, as they will probably mix 32 bit and 64 bit data. But this PR mainly deals with the view mode, right?

Comment (MichaelBuessemeyer) [reply frontend/javascripts/oxalis/model_initialization.js:438]: 1. I got no mail notification that youri posted this concern 😕.
> But this PR mainly deals with the view mode, right @MichaelBuessemeyer ?

No it doesn't This PR also enables 64-bit volume tracings in the frontend. If we do not what this behaviour (and that's what I think is your opinion) we just have to remove the changes in lines `436-438, 442`. Then the user will get a warning upon opening a volume tracing. 


@youri: When the user creates a volume tracing the backend creates an empty tracing (maybe including a fallback layer). At this point the backend seems inconsistent, because trying to create a volume tracing on a dataset with a uint64-bit segmentation layer will set the `elementClass` of the initial tracing to `elementClass`. At least that's what I remember and why I needed to add the lines `436-438, 442`.


According to the suggestion to always send the 64-bit element class as the property `elementClass` and getting rid of `originalElementClass`: This should be possible :).

Comment (fm3) [reply frontend/javascripts/oxalis/model_initialization.js:438]: I see, thank you for your reply!

We should extensively test the 64 bit volume tracing, especially with how fallback layer data is incorporated into the tracing, and if this works with https://github.com/scalableminds/webknossos/pull/4602
But yeah, let’s try it :)

Comment (fm3) [reply frontend/javascripts/oxalis/model_initialization.js:438]: I just had a conversation with Youri and we decided it would be preferrable **not** to allow 64-bit volume tracings yet. 

While the trouble with their data being in 32 bit and the fallback buckets being 64 bit is invisible in the wK frontend, since the fallback buckets will be truncated to 32 bit, the data will not *actually* be compatible, it will not actually be clear which ID should belong to which cell.

Additionally, saving 32 bit data labeled as 64 bit data can lead to incompatibilities in case the frontend in some future version using some future javascript features actually produces 64 bit data. Then our implicit knowledge becomes ambiguous.

Since no user has yet wished for volume tracings with 64 bit fallback layer, and this PR was originally only about the user notification about truncated data, please remove the changes you mentioned, @MichaelBuessemeyer , so that the user can not trace on 64 bit volume tracings. Additionally, @youri-k , please add an check in the back-end side *creation* of volume tracings, so that 64 bit volume tracings can not be created.

**Comment by MichaelBuessemeyer** [comment]
@daniel-wer Could you please review the frontend part of this PR?

I added the optional `originalElementClass` property to the segmentation layer type. This makes it possible to know that the original element class on the server is `unit64` and not the truncated `uint32` type.

The conversion of type `uint64` to `uint32` is not done for the segmentation layer if we have a volume tracing as volume tracings for `uint64` segmentation data is currently not allowed

File: frontend/javascripts/messages.js [hunk 2]
```diff
@@ -94,6 +94,8 @@ instead. Only enable this option if you understand its effect. All layers will n
     "You didn't add a node after jumping to this branchpoint, do you really want to jump again?",
   "tracing.segmentation_zoom_warning":
     "Segmentation data and volume annotation is only fully supported at a smaller zoom level.",
+  "tracing.uint64_segmentation_warning":
+    "This is an unsigned 64-bit segmentation. The displayed ids are truncated. Thus they might not match the ids on the server.",
```
Comment (daniel-wer) [inline frontend/javascripts/messages.js:98]:
```suggestion
    "This is an unsigned 64-bit segmentation. The displayed ids are truncated to 32-bit. Thus, they might not match the ids on the server.",
```

File: frontend/javascripts/oxalis/model_initialization.js [hunk 3]
```diff
@@ -295,6 +295,24 @@ function initializeDataset(
     dataSet: dataset.dataSource.id.name,
   });
 
+  // Here we add the originalElementClass property to the segmentation layer if it exists.
```
Comment (daniel-wer) [inline frontend/javascripts/oxalis/model_initialization.js:298]: Might be a matter of personal preference, but I think usually comments should short and concise, so `Add the original ...` instead of `Here we add the original ...`. Please drop the `we` from the other comments as well. Apart from that, the comments are written very well :+1:

File: frontend/javascripts/oxalis/model_initialization.js [hunk 4]
```diff
@@ -434,9 +452,13 @@ function setupLayerForVolumeTracing(
   const fallbackLayer = layers[fallbackLayerIndex];
   const boundaries = getBoundaries(dataset);
 
+  // We do not adjust the elementClass here if it is uint64, because uint64 volume tracings are not supported.
+  // Not adjusting the elementClass will cause the later check for supported layer element classes to fail
+  // if the segmentation of type uint64.
```
Comment (daniel-wer) [inline frontend/javascripts/oxalis/model_initialization.js:457]:
```suggestion
  // if the segmentation is of type uint64.
```

File: frontend/javascripts/oxalis/model_initialization.js [hunk 5]
```diff
@@ -434,9 +452,13 @@ function setupLayerForVolumeTracing(
...
   const tracingLayer = {
     name: tracing.id,
     elementClass: tracing.elementClass,
+    originalElementClass: tracing.elementClass,
```
Comment (daniel-wer) [inline frontend/javascripts/oxalis/model_initialization.js:461]: Does the `originalElementClass` need to be set here at all? In the type definition it's declared as optional.

File: frontend/javascripts/oxalis/view/right-menu/mapping_info_view.js [hunk 6]
```diff
@@ -262,12 +262,28 @@ class MappingInfoView extends React.Component<Props, State> {
...
       dataIndex,
     });
+    const showSegmentation64bitWarning =
+      segmentationLayer && segmentationLayer.originalElementClass === "uint64";
+    const maybeWithTooltipWarningTitle = title =>
+      showSegmentation64bitWarning ? (
+        <React.Fragment>
+          {title}{" "}
+          <Tooltip title={message["tracing.uint64_segmentation_warning"]}>
+            <Icon type="info-circle" style={{ color: "rgb(255, 155, 85)" }} />
```
Comment (daniel-wer) [inline frontend/javascripts/oxalis/view/right-menu/mapping_info_view.js:272]: Maybe use `warning` as the type instead. That would better fit with the color and the intention of this message to warn the user that the displayed ids may not be correct.

**Comment by daniel-wer** [comment]
Testing went well :+1: 

@youri-k How much effort would it be to make this error message a little more helpful and display the actual error message concerning the uint64 layer instead of the generic one in the top level? It's fine if it's not feasible, I just wanted to check :)

uint64_error

**Comment by fm3** [comment]
I think it should be relatively easy to move the “because you are not a memeber of a team that has access” down into the debug info chain (so that it only shows when it is actually true).
This way the top-level error stays the generic »failed to create annotation« but upon expanding the correct reason is available.
We could even consider renaming the expand button to »show more information« rather than just »debug« because I think there are a number of occasions where this info is also helpful to the user (or at least their team manager).

**Comment by youri-k** [comment]
I'll do the suggested changes and am also in favor of renaming the expand button.

File: frontend/javascripts/oxalis/model_initialization.js (hunk 3 above)
Comment (MichaelBuessemeyer) [reply frontend/javascripts/oxalis/model_initialization.js:298]: Ok, thanks for that feedback. I'll pay attention to that :slightly_smiling_face:

File: frontend/javascripts/oxalis/model_initialization.js (hunk 5 above)
Comment (MichaelBuessemeyer) [reply frontend/javascripts/oxalis/model_initialization.js:461]: Thanks, you are correct. I'll revert the changes here :+1:

File: frontend/javascripts/oxalis/view/right-menu/mapping_info_view.js (hunk 6 above)
Comment (MichaelBuessemeyer) [reply frontend/javascripts/oxalis/view/right-menu/mapping_info_view.js:272]: Sure, that makes sense :exploding_head:

**Comment by MichaelBuessemeyer** [comment]
@daniel-wer Could you please check the few changes I pushed?

**Comment by youri-k** [comment]
This should be good to go, or @MichaelBuessemeyer?

**Comment by MichaelBuessemeyer** [comment]
If the backend part is also approved then sure :tada:

**Comment by MichaelBuessemeyer** [comment]
@youri-k Is the backend part also approved?
