### PR TITLE
Show fallback data for missing buckets

### LINKED ISSUE #3148: Show fallback data when buckets of better magnification do not exist
https://discuss.webknossos.org/t/magnification-2-visible-at-high-zoom-levels-when-magnification-1-does-not-exist/1072

I think, this should already work in theory, but the back-end seems to deliver black data if it doesn't find the requested buckets if the position is within the bbox?

To reproduce: I copied a dataset and removed some cubes from the best mag level. When opening the tracing, I can see at zoom step 2 that all data is there. If I zoom in, I can see a "hole" in the data (corresponding to the cubes I deleted). If I zoom into this hole, so that the viewport is black, and refresh the page, the network tab only shows successful requests. The front-end cannot know about these holes, which is why the back-end seems to deliver valid responses (i.e., black data). This would need to change so that the request simply fails (saying "data was not found" to avoid retries).

Can you have a look at this, @fm3, or delegate this to somebody else from the back-end team?

### PR DESCRIPTION
**Pull request by rschwanhold**
### Steps to test:
- copy a dataset and remove some cubes from the best mag level
- open a tracing
   - you should see at zoom step 2 that all data is there. 
   - If you zoom in, you should see that the data is missing
- go into the dataset settings and disable "Render Missing Data Black"
- reload the page
- if you zoom in, you should still see data (from a different zoom-step)

### Issues:
- fixes #3148

------
- ~~[ ] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)~~
- ~~[ ] Updated [migration guide](../blob/master/MIGRATIONS.md#unreleased) if applicable~~
- ~~[ ] Updated [documentation](../blob/master/docs) if applicable~~
- [x] Needs datastore update after deployment
- [x] Ready for review

### CODE REVIEW

**Comment by rschwanhold** [comment]
@philippotto can you do the frontend changes?

**Comment by rschwanhold** [comment]
@philippotto What name do you suggest for the header-field? Currently it looks like this: `BUCKETS: 0, 1, 2`. This means that we have data for all of the three requested buckets. `BUCKETS: 0, 2` means we have no data for Bucket 1. Is this layout ok?

**Comment by philippotto** [comment]
> @philippotto What name do you suggest for the header-field? Currently it looks like this: BUCKETS: 0, 1, 2. This means that we have data for all of the three requested buckets. BUCKETS: 0, 2 means we have no data for Bucket 1. Is this layout ok?

On a second thought, I'd invert the semantics and rename it to `MISSING-BUCKETS`. So, usually (if all buckets are found), the header is empty (and can be omitted probably). The actual value being a list is fine by me. I'd prefer square brackets around it, though, (like that `[1]`) so it's conform with a JSON array.

**Comment by philippotto** [comment]
The front-end part is ready now. I assigned @daniel-wer for the front-end review and @fm3 for the back-end. I assume back end was finished, right @rschwanhold ?

File: app/assets/javascripts/messages.js [hunk 1]
```diff
@@ -26,6 +26,12 @@ In order to restore the current window, a reload is necessary.`,
   "download.wait": "Please wait...",
   "download.close_window": "You may close this window after the download has started.",
   "add_script.confirm_change": "This will replace the code you have written. Continue?",
+  "data.enabled_render_missing_data_black":
+    "You just enabled the option to render missing data black. Please refresh this page so that the changes can take effect.",
+  "data.disabled_render_missing_data_black": `You just disabled the option to render missing
+  data black. This means that in case of missing data, data of lower quality is rendered
+  instead. Only enable this option if you are understand its effect. Please refresh
```
Comment (daniel-wer) [inline app/assets/javascripts/messages.js]: There is a superfluous `are` in front of understand.

File: app/assets/javascripts/oxalis/model/bucket_data_handling/pullqueue.js [hunk 2]
```diff
@@ -93,56 +93,70 @@ class PullQueue {
     // Measuring the time until response arrives to select appropriate preloading strategy
     const roundTripBeginTime = new Date();
     const layerInfo = getLayerByName(dataset, this.layerName);
+
+    const handleBucket = (bucketAddress, bucketData, resolutions) => {
```
Comment (daniel-wer) [inline app/assets/javascripts/oxalis/model/bucket_data_handling/pullqueue.js]: As the `pullBatch` method already was pretty long and got even longer now, can you make `handleBucket` an instance method of the pullqueue instead of defining it here, locally?

File: app/assets/javascripts/oxalis/model/bucket_data_handling/pullqueue.js [hunk 3]
```diff
@@ -93,56 +93,70 @@ class PullQueue {
...
-                layerInfo.category === "segmentation",
-              );
-            }
-          }
+        if (isMissing && !renderMissingDataBlack) {
+          bucket.pullFailed(true);
+        } else {
+          const bucketData = isMissing
+            ? new Uint8Array(bucket.BUCKET_LENGTH)
+            : responseBuffer.subarray(offset, (offset += this.cube.BUCKET_LENGTH));
```
Comment (daniel-wer) [inline app/assets/javascripts/oxalis/model/bucket_data_handling/pullqueue.js]: Is there a difference between `bucket.BUCKET_LENGTH` (previous line) and `this.cube.BUCKET_LENGTH`? If not, I would use only one of the two variants.

File: app/assets/javascripts/oxalis/view/settings/dataset_settings_view.js [hunk 4]
```diff
@@ -76,6 +78,15 @@ class DatasetSettings extends React.PureComponent<DatasetSettingsProps> {
     this.props.onChange(propertyName, parseInt(value));
   };
 
+  onChangeRenderMissingDataBlack = (value: boolean): void => {
+    Toast.warning(
```
Comment (daniel-wer) [inline app/assets/javascripts/oxalis/view/settings/dataset_settings_view.js]: I didn't manage to read the longer of the two toast messages before it disappeared. I would double the amount of display time for the toast.

File: app/assets/javascripts/oxalis/view/settings/dataset_settings_view.js [hunk 5]
```diff
@@ -120,6 +131,11 @@ class DatasetSettings extends React.PureComponent<DatasetSettingsProps> {
             <Option value="1">medium</Option>
             <Option value="2">low</Option>
           </DropdownSetting>
+          <SwitchSetting
```
Comment (daniel-wer) [inline app/assets/javascripts/oxalis/view/settings/dataset_settings_view.js]: In my opinion, it's not clear what is going to happen when disabling this setting. We should point out that the alternative to "Render Missing Data Black" is (something like) "Upsample lower resolution data for missing higher resolution data". Maybe use an info tooltip next to the setting :)

File: app/assets/javascripts/oxalis/workers/fetch_buffer_with_headers.worker.js [hunk 6]
```diff
@@ -0,0 +1,26 @@
...
+  url: RequestInfo,
+  options?: RequestOptions,
+): Promise<{ buffer: ArrayBuffer, headers: Object }> {
+  return fetch(url, options)
+    .then(handleStatus)
+    .then(async response => {
+      const buffer = await response.arrayBuffer();
+      const { headers } = response;
+      const headerObject = {};
+      for (const [key, value] of headers.entries()) {
```
Comment (daniel-wer) [inline app/assets/javascripts/oxalis/workers/fetch_buffer_with_headers.worker.js]: So the `headersTransferHandler` that is used to transfer Headers TO a webworker does not work when transferring Headers the other way? Or would it be possible to reuse it? :)

Comment (philippotto) [reply app/assets/javascripts/oxalis/workers/fetch_buffer_with_headers.worker.js]: Yeah, it's a bit shitty. I think the problem is that the header attribute is nested within the actual transferred data. I didn't feel like going into this further, but we should keep an eye on that in the feature.

**Comment by philippotto** [comment]
@rschwanhold Could have a look at the merge conflict? :)
