### PR TITLE
Fix timeline chart by explicitly setting start and end time

### LINKED ISSUE #3771: Time tracking chart rendering breaks if the timespan is too short
If the user worked for less than a second in the selected time frame, the chart rendering lib throws an error.

`Cannot read property 'v' of undefined`

### PR DESCRIPTION
**Pull request by daniel-wer**
Users with only a single sub-second timerange triggered this bug: https://github.com/google/google-visualization-issues/issues/2269

I fixed it by explicitly setting a start and end time for the timeline start (the range the user selected), which is better than the adaptive start/end from before anyways imo. This way it is easier to see which days the selected tracer actually worked and which not.

I also upgraded the charts lib to v2 (v3 didn't work) to get rid of an old version of react that was included specifically for this lib.

Single Day (which triggered the bug before):
single-day

Range:
timeranges

### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- Open a task and set a single node, then close it again.
- Open the timeline view and select today's date - the chart should render and not crash.

### Issues:
- fixes #3771 

------
- [x] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)
- [x] Ready for review

### CODE REVIEW

File: frontend/javascripts/admin/time/time_line_view.js [hunk 1]
```diff
@@ -201,7 +202,13 @@ class TimeLineView extends React.PureComponent<*, State> {
               chartType="Timeline"
               columns={columns}
               rows={rows}
-              options={{ timeline: { singleColor: "#108ee9" } }}
+              options={{
+                timeline: { singleColor: "#108ee9" },
+                hAxis: {
```
Comment (philippotto) [inline frontend/javascripts/admin/time/time_line_view.js]: Maybe add a comment here with a reference to this PR? Otherwise, we might forget about it and re-introduce the bug again at some point :see_no_evil:
