### PR TITLE
Fix creating/editing a volume task type

### LINKED ISSUE #5531: Creating/editing a volume task type fails
Creating/editing a volume task type fails with "invalid JSON format".

Also see https://discuss.webknossos.org/t/unable-to-edit-task-type/1671/1.

### PR DESCRIPTION
**Pull request by philippotto**
This PR fixes a regression which was introduced in 61d3bee93. Even though, a volume task type doesn't really need settings, such as for soma clicking, the task type format still requires this (according to front-end as well as back-end types). In earlier versions, we simply hid the form fields but still maintained their values. I restored this behavior with this PR.

### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- create a volume task type (didn't work before)
- edit a volume task type and save (even without doing any changes, this failed)

### Issues:
- fixes #5531

------
- [x] Updated [(unreleased) changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)
- [ ] Updated [(unreleased) migration guide](../blob/master/MIGRATIONS.unreleased.md#unreleased) if applicable
- [ ] Updated [documentation](../blob/master/docs) if applicable
- [ ] Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes
- [ ] Needs datastore update after deployment
- [X] Ready for review

### CODE REVIEW

File: frontend/javascripts/admin/tasktype/task_type_create_view.js [hunk 1]
```diff
@@ -290,27 +290,29 @@ class TaskTypeCreateView extends React.PureComponent<Props, State> {
...
-
-                    <FormItem name={["settings", "mergerMode"]} valuePropName="checked">
-                      <Checkbox>Merger Mode</Checkbox>
-                    </FormItem>
-                  </React.Fragment>
-                ) : null
-              }
+              {({ getFieldValue }) => (
+                <div
+                  style={{
```
Comment (daniel-wer) [inline frontend/javascripts/admin/tasktype/task_type_create_view.js:295]: I'd propose to add a comment so that this doesn't happen again in the future

**Review by daniel-wer — APPROVED** [review]
Thank you for investigating and fixing this. :+1:

File: frontend/javascripts/admin/tasktype/task_type_create_view.js (hunk 1 above)
Comment (philippotto) [reply frontend/javascripts/admin/tasktype/task_type_create_view.js:295]: Very good point :+1:
