### PR TITLE
Fix task creation alignment

### LINKED ISSUE #8037: Fix button alignment in task creation view
## Context

The buttons to assign experience domain, create a new task type and so on look a bit misaligned. They are vertically lower than the other items in the row.

## Expected Behavior

All items should be properly aligned / centered in the row.

## Current Behavior

image

## Steps to Reproduce the bug
 Just open the task creation view

### PR DESCRIPTION
**Pull request by hotzenklotz**
This PR fixes the alignment of the button in the task creation form. Additionally, it replaces some of the custom CSS with standard antd components for consistency.

### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- Navigate to Admin > Task
- Click on "Add Task"
- Verify that the form works
- Verify that the button alignment is fixed

### Issues:
- fixes #8037

------
(Please delete unneeded items, merge only when none are left open)
- [x] Added changelog entry (create a `$PR_NUMBER.md` file in `unreleased_changes` or use `./tools/create-changelog-entry.py`)
- [ ] Added migration guide entry if applicable (edit the same file as for the changelog)
- [ ] Updated [documentation](../blob/master/docs) if applicable
- [ ] Adapted [wk-libs python client](https://github.com/scalableminds/webknossos-libs/tree/master/webknossos/webknossos/client) if relevant API parts change
- [ ] Removed dev-only changes like prints and application.conf edits
- [ ] Considered [common edge cases](../blob/master/.github/common_edge_cases.md)
- [ ] Needs datastore update after deployment

### CODE REVIEW

File: frontend/javascripts/admin/task/task_create_form_view.tsx [hunk 1]
```diff
@@ -159,73 +164,64 @@ export function handleTaskCreationResponse(
...
-          style={{
-            whiteSpace: "pre-line",
-          }}
-        >
-          {warnings.join("\n")}
-        </div>
+        <Alert
+          showIcon
+          type="warning"
+          title="There were warnings during task creation"
```
Comment (hotzenklotz) [inline frontend/javascripts/admin/task/task_create_form_view.tsx]: `title` prop is already antd v6. Should be `message` for v5.

**Review by knollengewaechs — APPROVED** [review]
nice, thank you!
