### PR TITLE
Fix loading ad-hoc meshes for transformed layers

### LINKED ISSUE #8913: Fix Ad Hoc meshing for Transformed layers
Ad Hoc meshing is broken for transformed layers. Noticed for a dataset with a configured rotation for all layers: https://webknossos.org/datasets/l4_sample4-65ca4f14010000b2087f2c78/view#3729,3247,1024,0,0.467

## Context

Ad hoc meshing should work for such transformed layers instead of silently failing to load the mesh

## Expected Behavior

The mesh should be properly loaded.

## Current Behavior

Nothing happes. The backend replies to the mesh request with no mesh as there is non at the transformed position and then the frontend stops requesting further mesh chunks. To the user is seems like the request does nothing.

## Steps to Reproduce the bug

- [ ] Cannot reproduce the bug anymore / needs deeper investigation.

1. Go to https://webknossos.org/datasets/l4_sample4-65ca4f14010000b2087f2c78/view#3729,3247,1024,0,0.467
2. Make sure the transforms are turned on
3. Load ad hoc mesh for centered segment (id: 58624)
4. Notice the mesh not loading

## Your Environment for bug

- shouldn't matter

### PR DESCRIPTION
**Pull request by knollengewaechs**
### URL of deployed dev instance (used for testing):
- https://fixadhocmeshesfortransformedlayers.webknossos.xyz/

### Steps to test:
- Test this with multiple datasets: one where all layers are transformed, and one where not all layers are transformed
- make sure the datasets have a segmentation layer

- register segments, load ad hoc meshes, and load precomputed meshes:
    - register some segments, scroll within the viewport, and then click on some segments in the segment list on the right. the viewport sshould jump to the right segment. do this with and without rendered transformations, and also toggle transformation rendering after registering the segments in the list
    - load some ad hoc meshes by selecting this option...
    - a) from the context menu in the segment list
    - b) from the context menu in the viewport
    - same for precomputed meshes
    -> again, this should be working with and without rendered transformations

### To do
- [x] I think I found another bug (reproduced on wk.org): click segment with transformed layers, scroll away, turn rendering with transformations off, click segment in segment list -> wrong place is focused
- [x] testing!!!

### Issues:
- fixes #8913 
- contributes to #9012 

------
(Please delete unneeded items, merge only when none are left open)
- [x] Added changelog entry (create a `$PR_NUMBER.md` file in `unreleased_changes` or use `./tools/create-changelog-entry.py`)
- [ ] Added migration guide entry if applicable (edit the same file as for the changelog)
- [ ] Updated [documentation](../blob/master/docs) if applicable
- [ ] Adapted [wk-libs python client](https://github.com/scalableminds/webknossos-libs/tree/master/webknossos/webknossos/client) if relevant API parts change
- [ ] Removed dev-only changes like prints and application.conf edits
- [x] Considered [common edge cases](../blob/master/.github/common_edge_cases.md)
- [ ] Needs datastore update after deployment

### CODE REVIEW

File: frontend/javascripts/viewer/controller/combinations/skeleton_handlers.ts [hunk 1]
```diff
@@ -158,7 +172,7 @@ export function handleOpenContextMenu(
           event.pageY,
           nodeId,
           clickedBoundingBoxId,
-          globalPosition?.rounded,
+          globalPosition,
```
Comment (knollengewaechs) [inline frontend/javascripts/viewer/controller/combinations/skeleton_handlers.ts]: todo

File: frontend/javascripts/viewer/view/context_menu.tsx [hunk 2]
```diff
@@ -1055,12 +1056,27 @@ function getNoNodeContextMenuOptions(props: NoNodeContextMenuProps): ItemType[]
...
+      !currentMeshFile ||
+      !visibleSegmentationLayer ||
+      globalPosition == null ||
+      positionInLayerSpace == null
+    )
+      return;
     // Ensure that the segment ID is loaded, since a mapping might have been activated
     // shortly before
-    const segmentId = await getSegmentIdForPositionAsync(globalPosition);
+    const segmentId = await getSegmentIdForPositionAsync(positionInLayerSpace);
```
Comment (knollengewaechs) [inline frontend/javascripts/viewer/view/context_menu.tsx]: find out why this is needed.

**Review by philippotto — APPROVED** [review]
awesome, thanks for fixing 🙏
