### PR TITLE
Fix displayed segment

### LINKED ISSUE #4431: "Segment ID at position" can be wrong in certain conditions
[Link to Discuss](https://discuss.webknossos.org/t/segment-id-at-position-is-wrong-when-disabling-render-missing-data-black/1572)

- disable “render missing data black”
- have segmentation in mag2
- zoom into mag1
- hovering over a segment does say "null"

### PR DESCRIPTION
**Pull request by MichaelBuessemeyer**
This PR adds looking for segmentation ids in higher resolutions when the current resolution has no data and render missing data black is disabled for the `segmentation tab`/`mapping_info_view`.

### URL of deployed dev instance (used for testing):
- _.webknossos.xyz

### Steps to test:
- It is best to test this on a local machine as manipulating datasets is easier.
- Create a dataset 
   - with at least one color layer with the resolutions 1-1-1, 2-2-2, 4-4-4 and so on
   - and with one segmentation layer that does not have the resolution 1-1-1.
- Open the dataset in view mode, disable render missing data black and open the segmentation tab
- Now zoom into mag 1
- The shown segmentation should be the segmentation from mag 2.
- The displayed segment ids in the segmentation tab should match the displayed data as well as there should be a new entry in the table of the tab displaying the resolution that is used to determine the segmentation ids.

### Issues:
- fixes #4431

------
- [x] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)
- ~~[ ] Updated [migration guide](../blob/master/MIGRATIONS.md#unreleased) if applicable~~
- ~~[ ] Updated [documentation](../blob/master/docs) if applicable~~
- ~~[ ] Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes~~
- ~~[ ] Needs datastore update after deployment~~
- [x] Ready for review

### CODE REVIEW

**Comment by MichaelBuessemeyer** [comment]
@philippotto I would like to make the solution a bit more fancy:
 I want to add an error message in case no valid segment ids could be found. I would position the error text right below the table.

My problem is that I cannot determine when there actually is no data when render missing data black is turned on. The reason is, that for the missing resolutions buckets filled with `0`'s are created which actually have data, but only fake data. Do you know why do determine whether a bucket is filled with fake data or with real data? Other than the "hasData" method from the bucket?

**Comment by philippotto** [comment]
> @philippotto I would like to make the solution a bit more fancy:
> I want to add an error message in case no valid segment ids could be found. I would position the error text right below the table.

I'm not sure whether that's really necessary. What would be the usecase? For normal EM data, we don't show any information like that either. I'm afraid this makes the code and UI more convoluted without adding much value :see_no_evil: But maybe I'm not understanding the usecase yet. So, feel free to argue back :D

**Comment by MichaelBuessemeyer** [comment]
> But maybe I'm not understanding the usecase yet.

My idea was to simply inform the user with a warning that the display segment id (0) is wrong and also tell why that might be the case. I especially had the dataset layer settings in mind. In the settings tab, a warning info icon is rendered when not all layers are visible. That is what I am thinking about here.

But on the other hand, the warning might not be necessary when we follow the rule "what you see is what you get". Because the warning would only be shown if no segmentation data can be found and rendered. Thus it might be obvious that the displayed 0 as segment id is wrong.

Leaving this point aside, I would be grateful if you would review the current code :smile:

File: frontend/javascripts/oxalis/view/right-menu/mapping_info_view.js [hunk 1]
```diff
@@ -126,24 +127,57 @@ class MappingInfoView extends React.Component<Props, State> {
...
+    let usableZoomStep = zoomStep;
+    const flycamPosition = position;
+    const resolutions = getResolutions(dataset);
+    // While render missing data black is not active and there is no segmentation for the current zoom step,
+    // the segmentation of a higher zoom step is shown.
+    // Here we determine the the next zoom step of the displayed segmentation data to get the correct segment ids.
+    while (
+      !renderMissingDataBlack &&
+      usableZoomStep < resolutions.length - 1 &&
+      !cube.hasDataAtPositionAndZoomStep(flycamPosition, usableZoomStep)
```
Comment (philippotto) [inline frontend/javascripts/oxalis/view/right-menu/mapping_info_view.js]: The same has to be done for the mouse position, since that could differ in theory. This means, the "Segmentation resolution" has to be rendered in each cell (or as an additional column maybe). Also, I'd use "Magnification" as a label in the UI, since this fits better, I think. Our usages of `resolution` in the code are a bit unfortunate, I think, but since it's spread all over the place, I wouldn't change it now.

**Comment by MichaelBuessemeyer** [comment]
@philippotto Thanks for paying attention and finding my mistake :+1:. I implemented your feedback. Could you please review the newest changes again :D?

Now the resolution/magnification has its own column and the zoom step for the mouse position is determined on its own. I tried to keep the code as understandable as possible. If you have any suggestions on how to improve it, I'll be glad to implement them.
