### PR TITLE
Store position in layer space when double-clicking segment

### LINKED ISSUE #9012: Store segment positions in layer space
## Context
I suspect the problem lies in how the segment position is stored. The **global** position seems to be simply used and stored in the segment. When switching the coordinate system, the position is no longer correct.
To fix this, the segment positions should always be stored in layer space and transformed when necessary.

## Expected Behavior
The segment position should remain correct regardless of the coordinate system. When switching coordinate systems, the position should be properly transformed.

## Current Behavior
When switching the coordinate system, the segment in the list points to an incorrect position. It seems that the global position is stored instead of the one in layer space.

## Steps to Reproduce the bug
1. Register a segment.  
2. Switch the coordinate system.  
3. Click the segment in the list.  
4. → The displayed position is incorrect.

## Your Environment for bug
- Browser name and version: e.g. Chrome 39  
- Operating System and version: e.g. Windows 10  
- Version of WEBKNOSSOS (Release or Commit):  
- [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)  
- [ ] Specific to webknossos.org (set `isDemoInstance=true` in `application.conf`)

### PR DESCRIPTION
**Pull request by knollengewaechs**
### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- brush or register a segment
- toggle coordinate system so that the volume layer has active transforms
- double click the segment in the data viewport (this stores the clicked position in the segment)
- click the segment in the sidebar list --> jumps to the incorrect position

### Issues:
- fixes #9012
- follow-up for #8992 

------
(Please delete unneeded items, merge only when none are left open)
- [x] Added changelog entry (create a `$PR_NUMBER.md` file in `unreleased_changes` or use `./tools/create-changelog-entry.py`)
- [ ] Added migration guide entry if applicable (edit the same file as for the changelog)
- [ ] Updated [documentation](../blob/master/docs) if applicable
- [ ] Adapted [wk-libs python client](https://github.com/scalableminds/webknossos-libs/tree/master/webknossos/webknossos/client) if relevant API parts change
- [ ] Removed dev-only changes like prints and application.conf edits
- [ ] Considered [common edge cases](../blob/master/.github/common_edge_cases.md)
- [ ] Needs datastore update after deployment

### CODE REVIEW

File: frontend/javascripts/viewer/controller/combinations/volume_handlers.ts [hunk 1]
```diff
@@ -137,9 +137,22 @@ export function handlePickCellFromGlobalPosition(
...
-  Store.dispatch(setActiveCellAction(segmentId, globalPos, additionalCoordinates));
-
   const visibleSegmentationLayer = getVisibleSegmentationLayer(Store.getState());
+
+  const positionInLayerSpace =
+    visibleSegmentationLayer != null
+      ? globalToLayerTransformedPosition(
+          globalPos,
+          visibleSegmentationLayer.name,
+          "segmentation",
```
Comment (MichaelBuessemeyer) [inline frontend/javascripts/viewer/controller/combinations/volume_handlers.ts:147]: I was a little confused by the plain string "segmentation" here at first. @philippotto Do we maybe want to refactor this into an enum, so we can write something like `LayerType.Segmentation` or so? This would have made this upon first read easier to understand / not stumble upon.

=> But this refacoring shouldn't be done here.

Comment (philippotto) [reply frontend/javascripts/viewer/controller/combinations/volume_handlers.ts:147]: sorry, this comment slipped through in my mail box. yes, sounds like a good idea. we should be careful about the naming though. I think, it's often called "category".

Comment (MichaelBuessemeyer) [reply frontend/javascripts/viewer/controller/combinations/volume_handlers.ts:147]: ok I opened a short issue fore this: #9035
