### PR TITLE
Fix select components

### LINKED ISSUE #5393: “No Data” in search field at Administration>>Tasks
[Link to Discuss](https://discuss.webknossos.org/t/no-data-in-search-field-at-administration-tasks/1659)

regression from #4576

### PR DESCRIPTION
**Pull request by philippotto**
### URL of deployed dev instance (used for testing):
- https://fixselectui.webknossos.xyz

### Steps to test:
- go to `/tasks` and type into the "User" select-input to see that the filtering works correctly

### Issues:
- fixes #5393

------
- [x] Updated [(unreleased) changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)
- [ ] Updated [(unreleased) migration guide](../blob/master/MIGRATIONS.unreleased.md#unreleased) if applicable
- [ ] Updated [documentation](../blob/master/docs) if applicable
- [ ] Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes
- [ ] Needs datastore update after deployment
- [X] Ready for review

### CODE REVIEW

File: frontend/javascripts/admin/dataset/dataset_components.js [hunk 1]
```diff
@@ -82,7 +82,7 @@ export function DatastoreFormItem({
       <Select
         showSearch
         placeholder="Select a Datastore"
-        optionFilterProp="children"
+        optionFilterProp="label"
```
Comment (philippotto) [inline frontend/javascripts/admin/dataset/dataset_components.js:85]: according to the antd docs, `label` should be passed here if the `options` prop is used. this also explains the breakage since we used to pass JSX children to the `select` components prior to the antd upgrade.

**Review by fm3 — APPROVED** [review]
Works for me :) 🎉

File: frontend/javascripts/admin/task/task_list_view.js [hunk 2]
```diff
@@ -190,7 +190,7 @@ class TaskListView extends React.PureComponent<Props, State> {
         <h3>Tasks</h3>
         <div className="clearfix" style={{ margin: "20px 0px" }} />
 
-        <Card title="Search for Tasks">
+        <Card title="Search for TaskSearchForm">
```
Comment (daniel-wer) [inline frontend/javascripts/admin/task/task_list_view.js:193]: This looks unintended

**Review by daniel-wer — APPROVED** [review]
One small comment :)

File: frontend/javascripts/admin/task/task_list_view.js (hunk 2 above)
Comment (philippotto) [reply frontend/javascripts/admin/task/task_list_view.js:193]: whoops, good catch!
