### PR TITLE
Fix rendering bug in oblique (and probably flight) mode

### LINKED ISSUE #5288: Missing buckets in oblique mode
In some cases, the oblique mode shows black spots.

### PR DESCRIPTION
**Pull request by philippotto**
### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- I had a "problematic" rendering at http://localhost:9000/datasets/sample_organization/ROI2017_wkw/view#507,622,474,2,8.141,0.00,51.11,0.00
- with this PR, the data renders properly (in oblique)

### Issues:
- fixes #5288

------
- [x] Updated [(unreleased) changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)
- [ ] Updated [(unreleased) migration guide](../blob/master/MIGRATIONS.unreleased.md#unreleased) if applicable
- [ ] Updated [documentation](../blob/master/docs) if applicable
- [ ] Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes
- [ ] Needs datastore update after deployment
- [X] Ready for review

### CODE REVIEW

File: frontend/javascripts/oxalis/controller/scene_controller.js [hunk 1]
```diff
@@ -128,6 +128,29 @@ class SceneController {
...
+      this.rootNode.add(line);
+      renderedLines.push(line);
+    };
+
+    window.removeLines = () => {
+      for (const line of renderedLines) {
+        this.rootNode.remove(line);
+      }
+      renderedLines = [];
+    };
```
Comment (philippotto) [inline frontend/javascripts/oxalis/controller/scene_controller.js:152]: I used that code to visualize the scan lines which the oblique bucket picker casts. Might be useful in the future, too, which is why I left it here (next to the debugging visualization of buckets).

Comment (normanrz) [reply frontend/javascripts/oxalis/controller/scene_controller.js:152]: out-of-scope for this PR, but maybe it would makes sense to put these debug helpers in an object (e.g. `window.__debug`) to not clutter the window object?

**Review by normanrz — APPROVED** [review]
lgtm!

File: frontend/javascripts/oxalis/controller/scene_controller.js (hunk 1 above)
Comment (philippotto) [reply frontend/javascripts/oxalis/controller/scene_controller.js:152]: Good point. I created https://github.com/scalableminds/webknossos/issues/5290

File: CHANGELOG.unreleased.md [hunk 2]
```diff
@@ -23,6 +23,7 @@ For upgrade instructions, please check the [migration guide](MIGRATIONS.released
 
 ### Fixed
 - Fixed a regression in the task search which could lead to a frontend crash. [#5267](https://github.com/scalableminds/webknossos/pull/5267)
+- Fixed a rendering bug in oblique mode. [#5267](https://github.com/scalableminds/webknossos/pull/5289)
```
Comment (daniel-wer) [inline CHANGELOG.unreleased.md:26]: Just noticed this, maybe you can slip it into another PR :)

```suggestion
- Fixed a rendering bug in oblique mode. [#5289](https://github.com/scalableminds/webknossos/pull/5289)
```
