### PR TITLE
make bool2Fox always explicit

### LINKED ISSUE #2941: remove implicit Boolean to Fox conversion
Conceptionally `false` is a valid value that can be checked for. Converting this implicitly to a failed Fox makes some expressions to magical (e.g. resolving assertions via the Fox `?~>` statement [here](https://github.com/scalableminds/webknossos/blob/25befc04b17281492b219355d98ef9720e4f9fc7/app/controllers/UserController.scala#L38).
Let's have a look how often this is used and if it makes sense to remove it / convert it to explicit conversions.

### PR DESCRIPTION
**Pull request by fm3**
### URL of deployed dev instance (used for testing):
- https://booltofoxexplicit.webknossos.xyz

### Steps to test:
- create/edit project
- create task, trace some, finish
- view compound project

### Issues:
- fixes #2941

------
- ~~[ ] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)~~
- ~~[ ] Updated [migration guide](../blob/master/MIGRATIONS.md#unreleased) if applicable~~
- [x] Ready for review

### CODE REVIEW

File: app/controllers/Authentication.scala [hunk 1]
```diff
@@ -408,8 +408,8 @@ class Authentication @Inject()(
 
   private def creatingOrganizationsIsAllowed(requestingUser: Option[User]) = {
     val noOrganizationPresent = InitialDataService.assertNoOrganizationsPresent
-    val configurationFlagSet = Play.configuration.getBoolean("application.allowOrganzationCreation").getOrElse(false) ?~> "allowOrganzationCreation.notEnabled"
-    val userIsSuperUser = requestingUser.exists(_.isSuperUser).toFox
```
Comment (rschwanhold) [inline app/controllers/Authentication.scala]: Is it correct that `.toFox` and `bool2Fox` have the same behavior? The only difference is that Boolean does not have a method called `.toFox` thats why it is implicitly converted to a Fox and then returns itself, while `bool2Fox` converts it explicitly?

File: util/src/main/scala/com/scalableminds/util/tools/Fox.scala [hunk 2]
```diff
@@ -42,6 +38,11 @@ trait FoxImplicits {
 
   implicit def fox2FutureBox[T](f: Fox[T])(implicit ec: ExecutionContext): Future[Box[T]] =
     f.futureBox
+
+  // This one is no longer implicit since that has lead to confusion. Should always be used explicitly.
```
Comment (rschwanhold) [inline util/src/main/scala/com/scalableminds/util/tools/Fox.scala]: Is it wanted that it still belongs to `FoxImplicits`?

Comment (fm3) [reply util/src/main/scala/com/scalableminds/util/tools/Fox.scala]: Yeah, that way it is available to all the classes inheriting from that Trait

File: app/controllers/Authentication.scala (hunk 1 above)
Comment (fm3) [reply app/controllers/Authentication.scala]: `.toFox` is actually a method of Fox. This way, if called on any type _that has an implicit conversion to Fox_, that conversion will be triggered. This will now no longer work for booleans (as is intended).
