### PR TITLE
Restrict data rendering to layer's bbox in shader

### LINKED ISSUE #9041: Buckets outside of layer bbox can hide other layer's data
## Context
dataset with multiple layers

## Expected Behavior
data outside of a layers bbox should not hide other layer's data.

## Current Behavior
black data is shown outside of a layer's bbox.

## Steps to Reproduce the bug

- [ ] Cannot reproduce the bug anymore / needs deeper investigation.

1. see this DS: https://scm.slack.com/archives/C5AKLAV0B/p1762173800091719

### PR DESCRIPTION
**Pull request by philippotto**
### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
I constructed this dataset with two overlapping layers and restricted the bbox auf one layer. Also, I changed the blend mode to "cover". I think there is no need to test this exact scenario again. I'd suggest to just monkey test a bit with other datasets.

Before this PR:
image

With this PR:
image

### TODOs:
- [x] check segmentation layers

### Issues:
- fixes #9041

------
(Please delete unneeded items, merge only when none are left open)
- [x] Added changelog entry (create a `$PR_NUMBER.md` file in `unreleased_changes` or use `./tools/create-changelog-entry.py`)
- [ ] Added migration guide entry if applicable (edit the same file as for the changelog)
- [ ] Updated [documentation](../blob/master/docs) if applicable
- [ ] Adapted [wk-libs python client](https://github.com/scalableminds/webknossos-libs/tree/master/webknossos/webknossos/client) if relevant API parts change
- [ ] Removed dev-only changes like prints and application.conf edits
- [ ] Considered [common edge cases](../blob/master/.github/common_edge_cases.md)
- [ ] Needs datastore update after deployment

### CODE REVIEW

File: frontend/javascripts/viewer/geometries/materials/plane_material_factory.ts [hunk 1]
```diff
@@ -570,15 +570,6 @@ class PlaneMaterialFactory {
         },
         true,
       ),
-      listenToStoreProperty(
```
Comment (philippotto) [inline frontend/javascripts/viewer/geometries/materials/plane_material_factory.ts:573]: @MichaelBuessemeyer I didn't add a listener for the layer's bboxes because I don't know when the layer's bboxes could change 🤔 I think this cannot happen right now. Or can you can up with a case (that exists right now) which contradicts my assumption?

Comment (MichaelBuessemeyer) [reply frontend/javascripts/viewer/geometries/materials/plane_material_factory.ts:573]: just thinking out loud without looking at the code: 
What if a dataset has a volume layer smaller than the color data and then a user starts annotating outside the volume bbox and thus enlarges it? Not sure whether that allowed by wk though.

Moreover, if this code here (not look at closely yet) only is important for color layers, then this shouldn't matter.

No other case currently comes into my mind

Comment (philippotto) [reply frontend/javascripts/viewer/geometries/materials/plane_material_factory.ts:573]: > What if a dataset has a volume layer smaller than the color data and then a user starts annotating outside the volume bbox and thus enlarges it? Not sure whether that allowed by wk though.

good idea! however, painting outside of a layer's bbox is not allowed (it will be cropped). so, this case should not be relevant :) thanks for giving this a thought, anyway!

**Review by MichaelBuessemeyer — APPROVED** [review]
Awesome. thanks. Works great
