### PR TITLE
fix exit-codes for postgres-scripts

### LINKED ISSUE #4392: ensure_schema.sh should fail if psql fails
ensure_schema.sh destroyed the db contents because the already-exists check somehow returned false while db name resolution failed. Then the script executed refresh_schema, which somehow could reach the db again.
The check should not return false in case of psql not reaching the db, instead the script should exit immediately.

### PR DESCRIPTION
**Pull request by jstriebel**
This fixes the early exit of `ensure_db.sh` & `ensure_schema.sh`. Before, the exit code of the command in the if-clause was hidden. A failure of the command did not cause the early exit of the script as usual through `set -e`. Using an assignment fixes this, this triggers the early exit as expected.

- fixes #4392 
- [x] Ready for review

### CODE REVIEW

File: tools/postgres/ensure_schema.sh [hunk 1]
```diff
@@ -8,7 +8,8 @@ dbHost="$("$scriptdir"/db_host.sh)"
 
 schemaPath="$scriptdir/schema.sql"
 
-if [ "$(PGPASSWORD=postgres psql -U postgres -h  $dbHost --dbname=$dbName -tAc "SELECT schema_name FROM information_schema.schemata WHERE schema_name = 'webknossos';")" = 'webknossos' ]
+SCHEMA_EXISTENCE="$(PGPASSWORD=postgres psql -U postgres -h  $dbHost --dbname=$dbName -tAc "SELECT schema_name FROM information_schema.schemata WHERE schema_name = 'webknossos';")"
```
Comment (fm3) [inline tools/postgres/ensure_schema.sh]: How about schemaName ? the variable does not really contain the existence, right? Also, the other vars are not all-caps.

Comment (jstriebel) [reply tools/postgres/ensure_schema.sh]:
```suggestion
schemaName="$(PGPASSWORD=postgres psql -U postgres -h  $dbHost --dbname=$dbName -tAc "SELECT schema_name FROM information_schema.schemata WHERE schema_name = 'webknossos';")"
```

File: tools/postgres/ensure_schema.sh [hunk 2]
```diff
@@ -8,7 +8,8 @@ dbHost="$("$scriptdir"/db_host.sh)"
...
+if [ "$SCHEMA_EXISTENCE" = 'webknossos' ]
```
Comment (jstriebel) [inline tools/postgres/ensure_schema.sh]:
```suggestion
if [ "$schemaName" = 'webknossos' ]
```

File: tools/postgres/ensure_db.sh [hunk 3]
```diff
@@ -6,7 +6,8 @@ scriptdir="$(dirname "$0")"
 dbName="$("$scriptdir"/db_name.sh)"
 dbHost="$("$scriptdir"/db_host.sh)"
 
-if [ "$(PGPASSWORD=postgres psql -U postgres -h $dbHost -tAc "SELECT 1 FROM pg_database WHERE datname='$dbName'" )" = '1' ]
+DATABASE_EXISTENCE="$(PGPASSWORD=postgres psql -U postgres -h $dbHost -tAc "SELECT 1 FROM pg_database WHERE datname='$dbName'" )"
```
Comment (jstriebel) [inline tools/postgres/ensure_db.sh]:
```suggestion
dbExistence="$(PGPASSWORD=postgres psql -U postgres -h $dbHost -tAc "SELECT 1 FROM pg_database WHERE datname='$dbName'" )"
```

File: tools/postgres/ensure_db.sh [hunk 4]
```diff
@@ -6,7 +6,8 @@ scriptdir="$(dirname "$0")"
...
+if [ "$DATABASE_EXISTENCE" = '1' ]
```
Comment (jstriebel) [inline tools/postgres/ensure_db.sh]:
```suggestion
if [ "$dbExistence" = '1' ]
```
