### PR TITLE
Await Server Replies When Updating User

### LINKED ISSUE #4988: “email has been changed” toast shows even if request has failed
If you edit a user’s email address in the Users admin view, a failed request leads to both an error toast and a success toast. The success message should not be shown, and the value should not be updated in the list.

### PR DESCRIPTION
**Pull request by fm3**
### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- Create second user
- In admin view, activate, deactivate, change email, should work
- try deactivating yourself, should fail, and not show as succeeded
- insert `          _ <- Fox.failure("nope")` in line 319 of UserController.scala
- subsequent user email/activation updates should fail, and should not seem successful in frontend

### Issues:
- fixes #4988 

------
- [x] Updated [(unreleased) changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)
- [x] Ready for review

### CODE REVIEW

File: frontend/javascripts/admin/user/user_list_view.js [hunk 1]
```diff
@@ -107,48 +107,57 @@ class UserListView extends React.PureComponent<PropsWithRouter, State> {
...
-        isTeamRoleModalVisible: isActive,
-      };
+  activateUser = async (selectedUser: APIUser, isActive: boolean = true) => {
+    const newUserPromises = this.state.users.map(user => {
+      if (selectedUser.id === user.id) {
+        const newUser = Object.assign({}, user, { isActive });
+        return updateUser(newUser).then(
+          serverUser => Promise.resolve(serverUser),
+          () => Promise.reject(user),
+        );
```
Comment (philippotto) [inline frontend/javascripts/admin/user/user_list_view.js:117]:
```suggestion
        return updateUser(newUser);
```

I think this should be equivalent for the success case and semantically "better" for the reject case. The argument to `reject` should be the "reason" for why the promise was rejected. It's recommended to use an error instance for that and I think that error instance is passed as the first parameter to the arrow-function (swallowed since you didn't list parameters for the error-handler). If the latter was changed, the entire `then` invocation becomes a no-op, if I'm not mistaken (hence, the above suggestion).

File: frontend/javascripts/admin/user/user_list_view.js [hunk 2]
```diff
@@ -107,48 +107,57 @@ class UserListView extends React.PureComponent<PropsWithRouter, State> {
...
-
-      return {
-        users: newUsers,
-        selectedUserIds: [selectedUser.id],
-      };
+  changeEmail = async (selectedUser: APIUser, newEmail: string) => {
+    const newUserPromises = this.state.users.map(user => {
+      if (selectedUser.id === user.id) {
+        const newUser = Object.assign({}, user, { email: newEmail });
+        return updateUser(newUser).then(
```
Comment (philippotto) [inline frontend/javascripts/admin/user/user_list_view.js:142]: same here.

**Review by philippotto — APPROVED** [review]
Awesome! Works great & elegant solution :+1: I just added one small suggestion.
