### PR TITLE
Fix regression which caused buckets not to load sometimes in view mode 

### LINKED ISSUE #3114: Not loading data is rendered grey in view mode for certain zoomstep
When uploading a dataset that only has one magnification step (zoom level 1), the initial view is so far zoomed out that the data is not visible. Unfortunately, the data is presented as grey (loading indicating), but no requests are made (which is correct b/c there is no data at that zoom level).

I think the data shouldn't be zoomed to a level that does not exist in the first place.
And unloadable data shouldn't be grey.

### PR DESCRIPTION
**Pull request by philippotto**
### URL of deployed dev instance (used for testing):
- https://fetchbucketsfordownsamplingregression.webknossos.xyz

### Steps to test:
- view dataset which only has one mag at zoom step 1.3 (should be the default). the data should show

### Issues:
- fixes #3114 

------
- [x] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)
- [X] Ready for review

### CODE REVIEW

File: app/assets/javascripts/oxalis/model/bucket_data_handling/prefetch_strategy_plane.js [hunk 1]
```diff
@@ -21,20 +21,8 @@ export class AbstractPrefetchStrategy {
   u: number;
   v: number;
 
-  forContentType(contentTypes: { skeleton: boolean, volume: boolean }): boolean {
-    if (_.isEmpty(this.contentTypes)) {
```
Comment (daniel-wer) [inline app/assets/javascripts/oxalis/model/bucket_data_handling/prefetch_strategy_plane.js]: I think we still need this check (I misinterpreted it while talking to you earlier) as the arbitrary prefetch strategy doesn't define any content types. If a prefetch strategy doesn't define any content types, it should be used for all content types - at least that was the original behavior.
Alternatively, we could also add `contentTypes = ["skeleton", "readOnly"];` to the arbitrary prefetch strategy.

Comment (philippotto) [reply app/assets/javascripts/oxalis/model/bucket_data_handling/prefetch_strategy_plane.js]: Very good point! I re-added the missing check and also renamed the variables a bit, since our initial misinterpretation was probably (at least partly) due to the confusing `contentTypes` and `this.contentTypes` naming.
