### PR TITLE
Fix scala linter errors in util,datastore,tracingstore, lint them in CI

### LINKED ISSUE #9390: Fix scala linting issues in datastore+tracingstore, run linter for everything in CI
Turns out scapegoat is only called for the webknossos module in the CI. The other modules have some offending code. Should be fixed, and then the linter be run for everything in the CI.

We should also see if we can configure scapegoat to be faster (avoid writing reports?)

### PR DESCRIPTION
**Pull request by fm3**
Previously, the linter only ran for the main sbt project (webknossos), but not for util,datastore,tracingstore.

### Issues:
- fixes #9390

### CODE REVIEW

File: webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/FindDataService.scala [hunk 1]
```diff
@@ -199,7 +199,7 @@ class FindDataService @Inject()(dataServicesHolder: BinaryDataServiceHolder)(imp
             case ((currMin, currMax), e) => (math.min(currMin, e), math.max(currMax, e))
           }
           val binSize = (max - min) / 255
-          val finalBinSize = if (binSize == 0f) 1f else binSize
+          val finalBinSize = if (math.abs(binSize) < 1e-7f) 1f else binSize
```
Comment (MichaelBuessemeyer) [inline webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/FindDataService.scala:202]: if `1e-7f` is now used in multiple places maybe define it as a `zeroEpsilon` `closeToZero` `epsilon` or so? But I'd prefert to have zero or so in the name.

Although, while thinking about this: the term `1e-7f` is already very expressiv imo and might be better & easier to understand than some protential cryptic name as `zeroEpsilon`. 

So do what you prefer (no need to reply). 
On second thought reusing `1e-7f` might be better :+1:

**Review by MichaelBuessemeyer — APPROVED** [review]
Awesome 💪 . Thanks for noticing this and improving the code 👍
