### PR TITLE
In recent conversions banner, skip jobs for deleted datasets

### LINKED ISSUE #8953: “recent conversions” banner shouldn’t link to deleted datasets
Often users delete datasets after uploading and noticing that something went wrong.

They are, then, still listed and linked in the “recent conversions” banner. That should be removed.

I’m unsure how to integrate that into the current code. The frontend only looks at the list of jobs, the info if the dataset still exists isn’t available in this context. We need to join this either in the frontend or in the backend and consider how to design the protocol.

Maybe a query param for the job list view to skip jobs of inactive datasets?

Or maybe we want the job still listed but the dataset deletion marked there?

### PR DESCRIPTION
**Pull request by fm3**
The dashboard “recent conversions” banner now does not show jobs whose result datasets have since been deleted.

### Steps to test:
- Set up local worker
- Upload some tif datasets
- Delete the results of some
- check “recent conversions” banner in dashboard
- job list view should still list all jobs.

### Issues:
- fixes #8953

------
- [x] Added changelog entry (create a `$PR_NUMBER.md` file in `unreleased_changes` or use `./tools/create-changelog-entry.py`)
- [x] Removed dev-only changes like prints and application.conf edits
- [x] Considered [common edge cases](../blob/master/.github/common_edge_cases.md)

### CODE REVIEW

**Comment by fm3** [comment]
@philippotto I implemented the backend part as discussed in https://github.com/scalableminds/webknossos/issues/8953#issuecomment-3852882044

When you have some time, could you maybe adapt the frontend? The job list route now supports two new optional arguments: `command` (e.g. `convert_to_wkw`) and `skipForDeletedDatasets` (bool).

The frontend could set those parameters when requesting jobs for this banner, and skip them otherwise.

File: frontend/javascripts/dashboard/dataset_view.tsx [hunk 1]
```diff
@@ -123,22 +129,27 @@ function DatasetView({
...
+        });
+      poll();
+      interval = setInterval(poll, CONVERSION_JOBS_REFRESH_INTERVAL);
     }
 
-    return () => (interval != null ? clearInterval(interval) : undefined);
+    return () => {
+      cancelled = true;
+      return interval != null ? clearInterval(interval) : undefined;
+    };
```
Comment (MichaelBuessemeyer) [inline frontend/javascripts/dashboard/dataset_view.tsx:152]: Maybe instead use `useInterval` from https://github.com/antonioru/beautiful-react-hooks/blob/HEAD/docs/useInterval.md. I am pretty sure that we already have this dependency. This might make the code easier to read

**Review by MichaelBuessemeyer — APPROVED** [review]
Awesome, thanks for the improvement 👍 

works perfectly.

I found one potential improvement for the FE code. But might also be optional. So already approving 🟢

File: frontend/javascripts/dashboard/dataset_view.tsx (hunk 1 above)
Comment (philippotto) [reply frontend/javascripts/dashboard/dataset_view.tsx:152]: I also briefly thought about it, but then we cannot have the `cancelled` boolean anymore. that's why I decided against it.
