### PR TITLE
Fix rendering artifacts for some anisotropic scenarios by making zoom step and bucketsPerDim dynamic

### LINKED ISSUE #3593: Incomplete image data along third dimension
[Link to Discuss](https://discuss.webknossos.org/t/incomplete-image-data-along-third-dimension/1297/2)

### PR DESCRIPTION
**Pull request by philippotto**
This PR refactors and improves how buckets are determined, estimated (the counts) and addressed for rendering. It should fix #3593.

More precisely, the following was changed:

- The calculation of the appropriate magnification was rewritten to better take into account anisotropic datasets. Before, we calculated how far we can zoom into while still being able to render mag 0. This factor was assumed to also work for mag 1 to mag 2, mag 2 to mag 4 etc. However, in case of anisotropic datasets, this doesn't work necessarily. For example, a dataset could be 1-1-1, 2-2-1, 4-4-1, 8-8-1. While zooming out, the amount of buckets necessary per x and y dimension, will be halved (compensating zooming out). However, per z it will stay the same (thus, the amount of buckets will increase).
Now, we determine per magnification the maximum zoom factor (instead of linearly calculating this factor). When determining the suitable magnification for a zoom factor, we go through the list of maximum factors and determine the correct index accordingly.
- Before, the maximum necessary amount of buckets per dimension (e.g. 17 in X, 17 in Y and 8 in Z) was computed **once** for mag 0 and then assumed for all magnifications. These `bucketsPerDim` are used to address buckets on the GPU. Since `bucketsPerDim` can change between mags (due to anisotropic data), this led to wrong addresses. This PR changes `bucketsPerDim` to depend on the used magnification level.

Notes regarding the implementation:
- The two functions in the ortho bucket picker allow to calculate how many buckets are necessary for a given magnification **and** zoom level (arbitrary). These functions are only used by the flycam accessor to determine suitable values to map between zoom value and magnification. Also it is used to calculate the correct `bucketsPerDim` values which are necessary for addressing buckets.
- The flycam accessors define a handful of functions (naming is hard) which are quite similar to each other. The two main use cases are:
  - getting the maximum zoom level for a magnification (e.g. 1.3 for mag0)
  - getting the bucketsPerDim value for a magnification (for non-fallback and fallback rendering)
  There are multiple variants which are non-memoized, memoized, per resolution or for all resolutions (the functions which determine the values for all resolutions are mainly defined to allow the easy memoization with memoizeOne).
  The `export` gives a good insight over whether they are helper functions or not.

### URL of deployed dev instance (used for testing):
- https://dynamicbucketsperdim.webknossos.xyz

### Steps to test:
- open different (anisotropic) datasets, zoom, move through data etc.

### Issues:
- fixes #3593

------
- [ ] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)
- [X] Ready for review

### CODE REVIEW

**Comment by philippotto** [comment]
I also added a dataset which makes it easy to reproduce the original rendering bug to our dev instances.  just pushed the corresponding screenshot test for that.

Here's the before/after screenshot (note the left side of the second viewport):
image

**Comment by philippotto** [comment]
Unfortunately, I noticed that there is a bug within the fallback renderin logic.

- [ ] When being in "uneven" bucket regions, the fallback rendering moves buckets to the GPU which are offset by one bucket in w dimension. Not sure what the actual logic error in the code is.

File: app/assets/javascripts/oxalis/model/bucket_data_handling/bucket.js [hunk 1]
```diff
@@ -357,7 +358,8 @@ export class DataBucket {
     if (this.visualizedMesh != null) {
       return;
     }
-    if (this.zoomedAddress[3] === 0 || this.zoomedAddress[3] === 1) {
+    const zoomStep = getRequestLogZoomStep(Store.getState());
+    if (true || this.zoomedAddress[3] === zoomStep) {
```
Comment (daniel-wer) [inline app/assets/javascripts/oxalis/model/bucket_data_handling/bucket.js]: You probably forgot to remove the `true ||`.

File: app/assets/javascripts/oxalis/model/bucket_data_handling/bucket_picker_strategies/orthogonal_bucket_picker.js [hunk 2]
```diff
@@ -20,41 +22,81 @@ import constants, {
...
     // As an example, even if the viewport width corresponds to exactly
     // 16 buckets, a slight offset can mean that we need one additional bucket,
     // from which we render only a small fraction. That's why 1 is added.
     // Math.ceil is important since a raw viewport width ~ 15.8 bucket should also
     // result in 17 buckets.
-    v => 1 + Math.ceil((zoomFactor * fallbackFactor * v) / constants.BUCKET_WIDTH),
+    (v, dim) => 1 + Math.ceil((zoomFactor * v) / (resolutionFactor[dim] * constants.BUCKET_WIDTH)),
+    necessaryVoxelsPerDim,
   );
-  return ((unzoomedBucketCountPerDim: any): Vector3);
```
Comment (daniel-wer) [inline app/assets/javascripts/oxalis/model/bucket_data_handling/bucket_picker_strategies/orthogonal_bucket_picker.js]: Nice!

File: app/assets/javascripts/oxalis/model/bucket_data_handling/bucket_picker_strategies/orthogonal_bucket_picker.js [hunk 3]
```diff
@@ -20,41 +22,81 @@ import constants, {
...
+    dataSetScale,
+    resolutionIndex,
+    resolutions,
+    zoomFactor,
+  );
+
+  const fallbackBucketsPerDim =
+    resolutionIndex + 1 < resolutions.length
+      ? calculateBucketCountPerDim(dataSetScale, resolutionIndex + 1, resolutions, zoomFactor)
+      : [0, 0, 0];
```
Comment (daniel-wer) [inline app/assets/javascripts/oxalis/model/bucket_data_handling/bucket_picker_strategies/orthogonal_bucket_picker.js]: Good job finding this! :tada:

File: app/assets/javascripts/oxalis/model/bucket_data_handling/texture_bucket_manager.js [hunk 4]
```diff
@@ -298,7 +300,15 @@ export default class TextureBucketManager {
     const y = bucketPosition[1] - anchorPoint[1];
     const z = bucketPosition[2] - anchorPoint[2];
 
-    const [sx, sy, sz] = this.bucketsPerDim;
+    if (x < 0) console.warn("x should be greater than 0. is currently:", x);
+    if (y < 0) console.warn("y should be greater than 0. is currently:", y);
+    if (z < 0) console.warn("z should be greater than 0. is currently:", z);
+
+    // Even though, bucketsPerDim might be different in the fallback case,
+    // it's save to assume that the values would only be smaller (since
```
Comment (daniel-wer) [inline app/assets/javascripts/oxalis/model/bucket_data_handling/texture_bucket_manager.js]:
```suggestion
    // it's safe to assume that the values would only be smaller (since
```

File: app/assets/javascripts/test/puppeteer/dataset_rendering.screenshot.js [hunk 5]
```diff
@@ -69,19 +69,30 @@ const datasetNames = [
...
   "fluro-rgb_knossos",
   "dsA_2",
+  "2017-05-31_mSEM_scMS109_bk_100um_v01-aniso",
+  "ROI2017_wkw_fallback",
 ];
 
 const viewOverrides: { [key: string]: string } = {
   e2006_knossos: "4736,4992,2176,0,1.0",
+  "2017-05-31_mSEM_scMS109_bk_100um_v01-aniso": "4608,4543,386,0,4.00",
+  ROI2017_wkw_fallback: "#535,536,600,0,1.18",
```
Comment (daniel-wer) [inline app/assets/javascripts/test/puppeteer/dataset_rendering.screenshot.js]: Not sure whether that is important, but in the other viewOverrides the `#` was left out.

**Comment by philippotto** [comment]
@daniel-wer Thanks for your review :) I applied all your comments. The CI build passes now (and I finalized the new regression test). So, feel free to test the deployed branch!

**Comment by daniel-wer** [comment]
Works well apart from a zooming issue I encountered:

- [ ] When zooming out as far as possible, buckets from a very high resolution seem to be loaded suddenly. They are very small and the viewport is not filled completely as a result of that.

zoom_bug
