### PR TITLE
Don't let toast elapse in background in some browsers

### LINKED ISSUE #4719: Ensure toast timeout doesn't elapse when tab is in background
NML Upload for large NMLs can take several minutes. Users leave the tab and when they return, the error toast is gone and they don’t get to know what was wrong with their NML or the server.

Maybe we should do this only for large NMLs? Any opinions?

### PR DESCRIPTION
**Pull request by knollengewaechs**
### URL of deployed dev instance (used for testing):
- https://timeouttabnotinbackground.webknossos.xyz/

### Steps to test:
- Use Chrome or sth. Chromium based
- Do anything that takes a bit of time and where toasts are shown in the process, such as:
      - upload a larger dataset and switch the tab
      - wait until the upload is done for a while
      - go back to the WK tab and make sure both toasts are shown at least for a very short time (there should be at least two toasts after switching back)
- create scenarios where error toasts and warning toasts are shown. Make sure that their content is printed to the console, except if the toast content is a more complex react node (containing a link, for example).

### Issues:
- fixes #4719

------
(Please delete unneeded items, merge only when none are left open)
- [x] Updated [changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)

### CODE REVIEW

File: frontend/javascripts/oxalis/model_initialization.ts [hunk 1]
```diff
@@ -700,11 +700,11 @@ async function applyLayerState(stateByLayer: UrlStateByLayer) {
       // The name of the layer could have changed if a volume tracing was created from a viewed annotation
       effectiveLayerName = getLayerByName(dataset, layerName, true).name;
     } catch (e) {
-      console.error(e);
```
Comment (dieknolle3333) [inline frontend/javascripts/oxalis/model_initialization.ts:703]: In cases like this I didnt omit the separate log because Error not only has a message, but also a type, and I didnt want that to be omitted. Let me know if you think I should change that :)

File: frontend/javascripts/libs/toast.tsx [hunk 2]
```diff
@@ -112,13 +112,29 @@ const Toast = {
     }
 
     notification[type](toastConfig);
+
+    // Make sure that toasts don't just dissapear while user has WK in background tab (e.g. while uploading large dataset).
```
Comment (philippotto) [inline frontend/javascripts/libs/toast.tsx:116]:
```suggestion
    // Make sure that toasts don't just disappear while user has WK in background tab (e.g. while uploading large dataset).
```

File: frontend/javascripts/libs/toast.tsx [hunk 3]
```diff
@@ -112,13 +112,29 @@ const Toast = {
...
+    // Most browsers pause requestAnimationFrame() if the current tab is not active, but Firefox does not seem to do that.
+    if (!sticky && key != null) {
+      requestAnimationFrame(async () => {
+        // ensure tab is active
+        const timeoutAfterTabSwitch = timeout >= 1000 ? 1000 : 0;
+        await sleep(timeout - timeoutAfterTabSwitch);
```
Comment (philippotto) [inline frontend/javascripts/libs/toast.tsx:122]: how about:

```suggestion
        const timeoutAfterTabSwitch = timeout / 2; // todo: maybe another var name would make more sense now
        await sleep(timeoutAfterTabSwitch);
```

this effectively splits the sleep into two equally long phases which can only start when the animation frame is fulfilled each. I find that conceptionally more intuitive.

File: frontend/javascripts/libs/toast.tsx [hunk 4]
```diff
@@ -112,13 +112,29 @@ const Toast = {
     }
 
     notification[type](toastConfig);
+
+    // Make sure that toasts don't just dissapear while user has WK in background tab (e.g. while uploading large dataset).
+    // Most browsers pause requestAnimationFrame() if the current tab is not active, but Firefox does not seem to do that.
+    if (!sticky && key != null) {
+      requestAnimationFrame(async () => {
```
Comment (philippotto) [inline frontend/javascripts/libs/toast.tsx:119]: You can use `await animationFrame();` to avoid the callback style. `animationFrame` is a helper in libs/utils.ts.

**Review by philippotto — COMMENTED** [review]
nice :) I left two small suggestions.

**Review by philippotto — APPROVED** [review]
sweet :)
