### PR TITLE
Fix unrestricted 2D floodfilling

### LINKED ISSUE #8496: 2d floodfill tool is broken in xz viewport
## Context

When using the 2d floodfill tool in the xz viewport the fill tool only floods along the x axis or so and not in the other direction. This should be fixed 👯 .

## Expected Behavior

The whole area should be filled in both directions. Not just in a single direction.

## Current Behavior

Only a single "slice along the x axis" is filled and not the whole xz "plane".

## Steps to Reproduce the bug
See this report: https://scm.slack.com/archives/C5AKLAV0B/p1743606559524839

## Your Environment for bug
- Linux & chrome, nothing specific. Shouldn't matter

### PR DESCRIPTION
**Pull request by knollengewaechs**
### Steps to test:
- Test that unrestricted 2D floodfilling works in all viewport planes, especially XZ and YZ. Make sure its still 2D though and that the maximum bounding box boundary cant be overstepped.

### Issues:
- fixes #8496

------
(Please delete unneeded items, merge only when none are left open)
- [x] Added changelog entry (create a `$PR_NUMBER.md` file in `unreleased_changes` or use `./tools/create-changelog-entry.py`)
- [ ] Added migration guide entry if applicable (edit the same file as for the changelog)
- [ ] Updated [documentation](../blob/master/docs) if applicable
- [ ] Adapted [wk-libs python client](https://github.com/scalableminds/webknossos-libs/tree/master/webknossos/webknossos/client) if relevant API parts change
- [ ] Removed dev-only changes like prints and application.conf edits
- [ ] Considered [common edge cases](../blob/master/.github/common_edge_cases.md)
- [ ] Needs datastore update after deployment

### CODE REVIEW

**Comment by MichaelBuessemeyer** [comment]
Unassigning my review as @hotzenklotz offered to help :pray:

File: frontend/javascripts/viewer/constants.ts [hunk 1]
```diff
@@ -334,7 +334,7 @@ const Constants = {
   // Maximum of how many buckets will be held in RAM (per layer)
   MAXIMUM_BUCKET_COUNT_PER_LAYER: 5000,
   FLOOD_FILL_EXTENTS: {
-    _2D: (process.env.IS_TESTING ? [512, 512, 1] : [768, 768, 1]) as Vector3,
+    _2D: (process.env.IS_TESTING ? [512, 512, 512] : [768, 768, 768]) as Vector3,
```
Comment (hotzenklotz) [inline frontend/javascripts/viewer/constants.ts:338]: The fix makes sense to me. Can you please add a comment/reference, that in 2D mode, the third axis will be set to one later anyway. So we can avoid this in the future.
