### PR TITLE
Omit mag slider in TIFF export if only one mag is available

### LINKED ISSUE #8002: Disallow selecting mag in tiff export modal in case there is only one mag
## Context

When exporting a layer as tiff one can select the mag to export. However, when there is only one mag, a draggable slider is still rendered but the user cannot slide it. Therefore I suggest to hide this slider setting in case the current selected layer only has one mag.

## Expected Behavior

IT should either be possible to interact with the slider when it is rendered or when its not don't render it.

## Current Behavior

The slider is also rendered when a layer is selected that only has a single mag.

## Steps to Reproduce the bug

- [ ] Cannot reproduce the bug anymore / needs deeper investigation.

1. Create a dataset with a layer with only one mag
2. Opent the download modal and go to the tiff export tab
3. Try to mode the mag slider. This should not work

### PR DESCRIPTION
**Pull request by knollengewaechs**
image

### URL of deployed dev instance (used for testing):
- https://tiffexporthidesliderforonlyonemag.webknossos.xyz/

### Steps to test:
- Open an annotation with a layer that has more than one mag and a layer with only one mag
- Go to Menu > Download and open the TIFF download
- If you select a layer with one mag, there should not be a mag slider and only the current mag should be displayed
- If you select a layer with more than one mag, the mag slider should still be displayed
- Next to that, only annotations with actual additional coordinates should show a section about the chosen additional coords 

### TODOs:
- [x] ...

### Issues:
- fixes #8002

------
(Please delete unneeded items, merge only when none are left open)
- [x] Updated [changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)
- [ ] Updated [migration guide](../blob/master/MIGRATIONS.unreleased.md#unreleased) if applicable
- [ ] Updated [documentation](../blob/master/docs) if applicable
- [ ] Adapted [wk-libs python client](https://github.com/scalableminds/webknossos-libs/tree/master/webknossos/webknossos/client) if relevant API parts change
- [ ] Removed dev-only changes like prints and application.conf edits
- [ ] Considered [common edge cases](../blob/master/.github/common_edge_cases.md)
- [ ] Needs datastore update after deployment

### CODE REVIEW

File: frontend/javascripts/oxalis/view/action-bar/download_modal_view.tsx [hunk 1]
```diff
@@ -670,23 +672,27 @@ function _DownloadModalView({
...
+            </Row>
+          )}
           <Text
             style={{
               margin: "0 6px 12px",
               display: "block",
             }}
           >
+            {onlyOneMagAvailable && mag.join("-")}
+            <br />
```
Comment (MichaelBuessemeyer) [inline frontend/javascripts/oxalis/view/action-bar/download_modal_view.tsx:695]: This added `<br>` also adds a newline after the slides which leads to additional vertical spacing which is not needed imo.
E.g. using 
```suggestion
            {onlyOneMagAvailable && <div>{mag.join("-")}</div>}

```
would avoid this.

**Review by MichaelBuessemeyer — APPROVED** [review]
Awesome, thanks for solving this. I only found a very minor nitpick.

Should be ready to be shipped :shipit:

File: frontend/javascripts/oxalis/view/action-bar/download_modal_view.tsx (hunk 1 above)
Comment (knollengewaechs) [reply frontend/javascripts/oxalis/view/action-bar/download_modal_view.tsx:695]: nice, thanks for catching this!
