### PR TITLE
Better diffs

### LINKED ISSUE #1857: Better update action diffing
Adapt our diffing algorithm to detect tree merges and splits to:

  - avoid possibly humongous JSON requests to the server (that fail if too big)
  - avoid broken tracings due to those big requests
  - increase overall tree merge/split performance, which takes a couple of minutes currently for a 30000 node tree

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1857/create?referer=github" target="_blank">Log Time</a>

### PR DESCRIPTION
**Pull request by daniel-wer**
Adapt our diffing algorithm (or better the compactUpdateActions function) to detect tree merges and splits to:

  - avoid  extremely large JSON requests to the server (that fail if too big)
  - avoid broken tracings due to those big requests
  - increase overall tree merge/split performance, which takes a couple of minutes currently for a 30000 node tree

As I've written in the issue, merging a 30000 node tree is now down from >5m to <5s.

I'm not entirely happy with this currently as I think the code is kind of complicated and may be error prone. I've added comments where appropriate, but the code is not really polished. If you have improvement suggestions, please tell me!

Also this is very important code and should be thoroughly tested, otherwise we'll have to deal with broken tracings!

### Steps to test:
- Run the tests
- Open a tracing (try with a big nml if you have one), split and merge trees, reload the page -> everything should still be there and work
- Time to split/merge big trees (>10000 nodes) should not be bigger than a couple seconds

### Issues:
- fixes #1857 and the broken tracings issue that comes up from time to time

------
- [ ] Ready for review

[4500nodes.nml.zip](https://github.com/scalableminds/webknossos/files/1052466/4500nodes.nml.zip)
[30000_nodes.nml.zip](https://github.com/scalableminds/webknossos/files/1052467/30000_nodes.nml.zip)

### CODE REVIEW

File: app/assets/javascripts/oxalis/model/reducers/save_reducer.js [hunk 1]
```diff
@@ -11,7 +11,7 @@ function SaveReducer(state: OxalisState, action: ActionType): OxalisState {
   switch (action.type) {
     case "PUSH_SAVE_QUEUE": {
       return update(state, {
-        save: { queue: { $push: action.items } },
+        save: { queue: { $push: action.items.length ? [action.items] : [] } },
```
Comment (daniel-wer) [inline app/assets/javascripts/oxalis/model/reducers/save_reducer.js]: No you're not missing something and you're correct. However, there is a test that does the following:
```
  const items = [];
  const pushAction = SaveActions.pushSaveQueueAction(items);
  const newState = SaveReducer(initialState, pushAction);

  t.deepEqual(newState.save.queue, []);
```
So the test executes the pushSaveQueueAction without the check you mentioned and pushes an empty array.
One could argue that this test is good, because a developer could do the same and forget to do the `if (items.length > 0)` check and then we end up with an empty array in our save queue (that's what caused me to commit this change).

I have no strong opinion on whether we should include this change or not.

**Comment by normanrz** [comment]
Do you think of any way, we could test this on a large scale without risking data loss?

**Comment by daniel-wer** [comment]
Well we could of course let some HiWi test this (and specifically instruct to do tree splits and merges), but that's not really large scale.
We could also think about whether it would be hard to write a piece of code that checks whether the compacted update actions result in the same modifications to a tracing as the original ones. Not sure how much work this would be.
I'll think some more about it.

I'm also currently incorporating the PR feedback,

File: app/assets/javascripts/oxalis/model/reducers/save_reducer.js (hunk 1 above)
Comment (philippotto) [inline app/assets/javascripts/oxalis/model/reducers/save_reducer.js]: Sounds reasonable, let's keep it then :)

**Comment by philippotto** [comment]
> We could also think about whether it would be hard to write a piece of code that checks whether the compacted update actions result in the same modifications to a tracing as the original ones. Not sure how much work this would be.

I like this idea. If it is not a performance problem, it could be constantly checked whether `updateActions` and `compact(updateActions)` cause the same changes to the last `state`. This way we could also be more confident that we didn't miss subtle bugs when testing this.

**Comment by daniel-wer** [comment]
I implemented exactly that, a reducer for update actions.
If the compactification of the update actions results in a different tracing, the original update actions are sent to the server and an airbrake error containing the tracing version is logged.
The tests are still running through and I also manually tested the airbrake notification.

Unfortunately the performance impact is very big and I don't think we can deploy this in production.
The main problem as I see it is to compare the two resulting tracings. Each tree has an edges array and during the comparison the order of the array elements should not be considered. Because of this, we cannot use _.isEqual to compare the two tracings, but have to use _.isMatch which is much slower. Doing this after every action a user executes on a very large tracing is wayyyyyyyyyy to slow and not usable. (understandably imo - I cannot think of a clever algorithm to do an unordered deep comparison of two very large arrays that contain complex objects)
The update actions reducer itself also is slow on big tracing splits/merges as it needs to apply both the original update actions as well as the compacted update actions.
I'm sure there is potential to optimize this, but I'm not sure whether this is a good investment of time.

I would suggest we leave this code in there and test it thoroughly on a feature branch. Then before merging we remove the update action reducer and tracing comparison code again. What do you think?

Please have a look at my last two commits and do some manual testing on the deployed http://better-diffs.oxalis.at branch.

**Comment by philippotto** [comment]
> I would suggest we leave this code in there and test it thoroughly on a feature branch. Then before merging we remove the update action reducer and tracing comparison code again. What do you think?

I agree! I also did some manual testing and think we should give it to the lab for testing further, so that we can merge it soon.

**Comment by daniel-wer** [comment]
We should tell the lab that they should not test with tracings larger than ~1000 nodes or so as otherwise the performance will be too bad. They should instead test different split/merge scenarios in smaller tracings and monitor whether a Toast error appears that notifies them of a diffing mismatch.

Then we can remove the test code and could do another small testing round with larger tracings, focused on performance.

**Comment by daniel-wer** [comment]
I've completed my systematic test of the compactUpdateActions function and couldn't find any errors.
I call it systematic, because I've refactored the code so that the save queue contains arrays of update actions. Each of these arrays is the result of one diff between an old tracing and a new tracing. A diff is triggered because of a store change and a store change happens because of an action the user executes in webknossos.
compactUpdateActions maps the save queue and only compacts one of those arrays from the save queue at a time (so one diff resulting from one webknossos action).
What I want to say is that the order in which actions are executed is not important. It's irrelevant for compactUpdateActions whether the user executes two merges and then a split or deletes a Tree and then deletes a branchpoint, as the function only compacts the result of one action at a time.
So by executing all possible actions that modify the tracing somehow, I can be pretty sure that the functions works as expected.
I've done this and experienced no errors.

I hope this was understandable, otherwise I'll go into more detail.

I've therefore reverted the assertions I built in earlier and did a last performance test. During the test I noticed that repeated calls to array.find slowed down compactUpdateActions. I got rid of those by building a map (object) beforehand using _.keyBy. The change from O(n²) to O(n) is quite noticeable using one of the large nmls and saving is now even faster.
@philippotto could you please review my last commit and make sure I didn't do sth. stupid :)

If everything is ok, I'd target Friday to merge this.

**Comment by hotzenklotz** [comment]
Great. Thanks for the extensive testing. :+1:

**Comment by daniel-wer** [comment]
@philippotto Can you have a look at the last commit, if possible I'd like to merge today :)

**Comment by philippotto** [comment]
@daniel-wer Sorry, I forgot about that. Everything looks fine and I also tested the last commit again :) Feel free to merge!
