### PR TITLE
Prevent dragging tree while renaming

### LINKED ISSUE #8701: Text selection with mouse does not work while renaming a tree
Drag and drop of trees (and maybe segments?) interferes with the text selection while editing the name.

Steps to reproduce:
- create an annotation
- create a tree
- doubleclick the tree name
- try to select a part of the tree name with the mouse (does not work)

### PR DESCRIPTION
**Pull request by knollengewaechs**
### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- From the bug report:
    create an annotation
    create a tree
    doubleclick the tree name
    try to select a part of the tree name with the mouse (~~does not work~~ should now work :wink:)
- check that dragging & dropping works as before when not currently renaming a tree
- check the same for tree groups :)

### TODOs:
- [x] trees
- [x] tree groups

### Issues:
- fixes #8701

------
(Please delete unneeded items, merge only when none are left open)
- [x] Added changelog entry (create a `$PR_NUMBER.md` file in `unreleased_changes` or use `./tools/create-changelog-entry.py`)
- [ ] Added migration guide entry if applicable (edit the same file as for the changelog)
- [ ] Updated [documentation](../blob/master/docs) if applicable
- [ ] Adapted [wk-libs python client](https://github.com/scalableminds/webknossos-libs/tree/master/webknossos/webknossos/client) if relevant API parts change
- [ ] Removed dev-only changes like prints and application.conf edits
- [x] Considered [common edge cases](../blob/master/.github/common_edge_cases.md)
- [ ] Needs datastore update after deployment

### CODE REVIEW

File: frontend/javascripts/viewer/view/right-border-tabs/trees_tab/tree_hierarchy_view.tsx [hunk 1]
```diff
@@ -67,6 +67,10 @@ function TreeHierarchyView(props: Props) {
   const [contextMenuPosition, setContextMenuPosition] = useState<[number, number] | null>(null);
   const [menu, setMenu] = useState<MenuProps | null>(null);
 
+  const [renamingCounter, setRenamingCounter] = useState(0);
+  const increaseRenamingCounter = () => setRenamingCounter((prev) => prev + 1);
+  const decreaseRenamingCounter = () => setRenamingCounter((prev) => Math.max(prev - 1, 0));
```
Comment (MichaelBuessemeyer) [inline frontend/javascripts/viewer/view/right-border-tabs/trees_tab/tree_hierarchy_view.tsx:73]: Not sure, whether it is necessary to keep track of how many are edited at once. At least I did not manage to get into a state where I was editing multiple names at the same time. So a simple boolean might be enough, but not 100% sure.

But anyways, very nice fix / enabling to select parts of the name with the mouse :)

Comment (knollengewaechs) [reply frontend/javascripts/viewer/view/right-border-tabs/trees_tab/tree_hierarchy_view.tsx:73]: I totally understand what you mean and this is how I did it in the first place! But then I had a look at the segments_view and there it is handled with a counter. I agree that at least 99% of the time the counter is not needed, but I thought that if the component reacted extra slow and first realized the new edit before recognizing the one before was done then maybe there could be a sort of race condition. My thought was that it doesnt hurt but let me know if you think that this is unneeded complexity
