### PR TITLE
Edit transform in DS settings

### LINKED ISSUE #8985: No longer possible to do advanced editing of dataset to remove transform
## Context
I have data stored in OME-Zarr 0.4 format, that I've imported to webknossos. The original data contains transformations at each multiscale level to make sure each downsampled level matches the correct coordinates of the other levels.

I want to annotate this data in Webknossos, but it is not possible to use the quick select tool on a dataset that has a transformation. So I would like to remove the transformation from the dataset after importing, and in the past I have been advised by Webknossos support to do this in by editing the dataset settings.

In the dataset settings page (e.g., https://webknossos.org/datasets/C6colonoverview-68e659780100007f01ca6eb5/edit/data) there is no longer an "Advanced" toggle to allow this however.

## Expected Behavior
There should be the option to edit the JSON metadata of the dataset, like there used to. Or some other way to remove the transformation so it's possible to do quick select annotations on datasets that are imported with transformations.

## Current Behavior
No way to remove transformation.

## Steps to Reproduce the bug

- [ ] Cannot reproduce the bug anymore / needs deeper investigation.

1.
2.
3.
4.

## Your Environment for bug

- Browser name and version: e.g. Chrome 39
- Operating System and version: e.g. Windows 10
- Version of WEBKNOSSOS (Release or Commit):
- [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
- [ ] Specific to webknossos.org (set `isDemoInstance=true` in `application.conf`)

### PR DESCRIPTION
**Pull request by knollengewaechs**
### URL of deployed dev instance (used for testing):
- https://edittransforms.webknossos.xyz (not up2date)

### Steps to test:
- Open the dataset settings for any dataset. Edit the transformations in Simple or Advanced mode, save, and check that was successful.
- Take a DS with transformations and remove them by 
     - setting the transform mode to `None`, 
     - setting all sliders in simple mode to 0 and removing all mirroring
     - removing the input in the advanced settings
- Test adding remote datasets with and without transformations
- In advanced transformation mode, test the json validation
- Make sure the last open settings were saved. Test this by editing advanced settings, then switching to simple settings (no edit), and saving -> the simple settings should be saved.

### TODOs:
- [x] save JSON
- [x] test for all cases where this form is shown
- [x] docs
- [x] transforms vs transformations? -> both is fine. went for transformation here. https://english.stackexchange.com/questions/5454/transform-or-transformation, https://dictionary.cambridge.org/dictionary/essential-british-english/transform
- [x] wrong layer name in json? -> e.g. wrongfully changing layername in advanced mode. transformation of original layer will be removed. this seems okay to me, because no transformation is provided for the given layer and the transformation of the non-existing layer (wrong name) will be ignored and not saved.
- [x] null-checks

### Issues:
- fixes #8985

### Context:
https://scm.slack.com/archives/C5AKLAV0B/p1769702720135759

------
(Please delete unneeded items, merge only when none are left open)
- [x] Added changelog entry (create a `$PR_NUMBER.md` file in `unreleased_changes` or use `./tools/create-changelog-entry.py`)
- [x] Updated [documentation](../blob/master/docs) if applicable
- [x] Removed dev-only changes like prints and application.conf edits
- [x] Considered [common edge cases](../blob/master/.github/common_edge_cases.md)

### CODE REVIEW

File: frontend/javascripts/dashboard/dataset/dataset_rotation_form_item.tsx [hunk 1]
```diff
@@ -180,12 +180,7 @@ export type DatasetRotationAndMirroringSettings = {
...
   form,
 }: AxisRotationSettingForDatasetProps) => {
-  // form -> dataSource -> dataLayers can be undefined in case of the add remote dataset form which is initially empty.
-  const dataLayers: APIDataLayer[] | undefined = form?.getFieldValue(["dataSource", "dataLayers"]);
-  const isRotationOnly = useMemo(
-    () => (dataLayers ? doAllLayersHaveTheSameRotation(dataLayers) : false),
-    [dataLayers],
-  );
+  const isRotationOnly: boolean = form?.getFieldValue(["isRotationOnly"]) || false;
   if (!isRotationOnly) {
```
[the remark this answers is not in the document]
Comment (knollengewaechs) [reply frontend/javascripts/dashboard/dataset/dataset_rotation_form_item.tsx:186]: it should not update

File: frontend/javascripts/dashboard/dataset/dataset_settings_data_tab.tsx [hunk 2]
```diff
@@ -77,15 +113,78 @@ function SimpleDatasetForm({
...
+          (ct) => ct.name === layer.name,
+        );
+        return {
+          ...layer,
+          coordinateTransformations: coordinateTransformation?.coordinateTransformations || [],
+        };
+      });
+      form.setFieldValue(["dataSource", "dataLayers"], dataLayersWithUpdatedTransforms);
+    }
+  }, [coordinateTransformationsJSON, form, dataSource, transformationsMode]);
```
[the remark this answers is not in the document]
Comment (knollengewaechs) [reply frontend/javascripts/dashboard/dataset/dataset_settings_data_tab.tsx]: good catch

**Review by knollengewaechs — COMMENTED** [review]
couldnt stop review otherwise, obvs didnt want to review my own PR.

ah damn, missed the "discard" button below. next time

File: frontend/javascripts/types/schemas/datasource.types.ts [hunk 3]
```diff
@@ -32,7 +33,19 @@ type BaseRemoteLayer = {
     index: number;
     bounds: Vector2;
   }>;
+  coordinateTransformations?: Array<AffineTransformation | ThinPlateSplineTransformation>;
```
Comment (philippotto) [inline frontend/javascripts/types/schemas/datasource.types.ts:36]: @fm3 do you know whether remote layers (e.g., zarr) can also have these transformations? I'd assume yes?

File: docs/datasets/settings.md [hunk 4]
```diff
@@ -17,9 +17,77 @@ The `Data Source` tab contains the core settings for your dataset.
 - **Voxel Size:** The physical size of a voxel in the configured unit (e.g., `11, 11, 24`).
 - **Unit:** The unit of the voxel size (e.g., `nm`).
 
-### Axis Rotation
+### Transformations
+
+Transformations are a way of rotating, mirroring or projecting dataset layers, among others. There are three modes for dataset transformation: `None`, `Simple`, and `Advanced`.
```
Comment (philippotto) [inline docs/datasets/settings.md]: not sure what projecting means in this context? I'd rephrase like this:

Transformations can be applied to individual layers or entire datasets to create effects such as rotation, mirroring, or aligning one layer with another.

File: docs/datasets/settings.md [hunk 5]
```diff
@@ -17,9 +17,77 @@ The `Data Source` tab contains the core settings for your dataset.
...
+      {
+        "type": "affine",
+        "matrix": [[1, 0, 0, 10], [0, 1, 0, 20], [0, 0, 1, 30], [0, 0, 0, 1]]
+      }
+    ]
+  }
+]
+```
+
+Please note that transformations in `Advanced` mode can only be defined for a specific layer. For transformations that should be applied to the whole dataset, either use the `Simple` mode or define the wanted transformation for each layer individually.
```
Comment (philippotto) [inline docs/datasets/settings.md]:
```suggestion
Please note that transformations in `Advanced` mode need to be defined per layer. For transformations that should be applied to the whole dataset, either use the `Simple` mode or duplicate the desired transformation for each layer individually.
```

File: frontend/javascripts/admin/dataset/dataset_add_remote_view.tsx [hunk 6]
```diff
@@ -103,6 +108,39 @@ function DatasetAddRemoteView(props: Props) {
     );
   };
 
+  const setEmptyTransformations = (mergedConfig: DatasourceConfiguration) => {
```
Comment (philippotto) [inline frontend/javascripts/admin/dataset/dataset_add_remote_view.tsx]: I'd omit `merged` in the var name

File: frontend/javascripts/dashboard/dataset/dataset_settings_data_tab.tsx [hunk 7]
```diff
@@ -55,13 +54,50 @@ function copyDatasetID(datasetId: string | null | undefined) {
 
 const LEFT_COLUMN_ITEMS_WIDTH = 408;
 const COPY_ICON_BUTTON_WIDTH = 32;
+const MARGIN_BOTTOM: React.CSSProperties = {
+  marginBottom: 24,
+};
+
+function DatasetTransformationsModeCard() {
```
Comment (philippotto) [inline frontend/javascripts/dashboard/dataset/dataset_settings_data_tab.tsx]: the name should at least contain JSON or advanced to make clear that it's only used for the third case.

File: frontend/javascripts/dashboard/dataset/dataset_settings_data_tab.tsx [hunk 8]
```diff
@@ -77,15 +113,85 @@ function SimpleDatasetForm({
...
+    if (transformationsMode === TransformationsMode.NONE) {
+      const dataLayersWithUpdatedTransforms = currentDataSource.dataLayers.map(
+        (layer: DataLayer) => {
+          return {
+            ...layer,
+            coordinateTransformations: [],
+          };
+        },
+      );
+      form.setFieldValue(["dataSource", "dataLayers"], dataLayersWithUpdatedTransforms);
```
Comment (philippotto) [inline frontend/javascripts/dashboard/dataset/dataset_settings_data_tab.tsx:181]: maybe add a `return` below this line. this might make the flow a bit easier to parse for humans.

File: frontend/javascripts/dashboard/dataset/dataset_settings_data_tab.tsx [hunk 9]
```diff
@@ -77,15 +113,85 @@ function SimpleDatasetForm({
...
+    { value: TransformationsMode.NONE, label: "None" },
+    { value: TransformationsMode.SIMPLE, label: "Simple" },
+    { value: TransformationsMode.ADVANCED, label: "Advanced" },
+  ];
+
+  const dataSource: Record<string, any> = Form.useWatch("dataSource", { form, preserve: true });
+  const transformationsMode: TransformationsMode = Form.useWatch(["transformationsMode"], form);
+  const coordinateTransformationsJSON: string = Form.useWatch(["coordinateTransformations"], form);
+
+  useEffect(() => {
```
Comment (philippotto) [inline frontend/javascripts/dashboard/dataset/dataset_settings_data_tab.tsx:167]: please add comment to this useEffect to explain its high-level purpose.

File: frontend/javascripts/dashboard/dataset/dataset_settings_data_tab.tsx [hunk 10]
```diff
@@ -77,15 +113,85 @@ function SimpleDatasetForm({
...
+            title="Axis Rotation"
+            style={MARGIN_BOTTOM}
+            content={
+              <Row gutter={[24, 24]}>
+                <Col span={24}>
+                  <AxisRotationSettingForDataset form={form} />
+                </Col>
+              </Row>
+            }
+          />
```
Comment (philippotto) [inline frontend/javascripts/dashboard/dataset/dataset_settings_data_tab.tsx]: maybe extract this into an own component next to `DatasetTransformationsModeCard`.

File: frontend/javascripts/dashboard/dataset/dataset_settings_data_tab.tsx [hunk 11]
```diff
@@ -77,15 +113,85 @@ function SimpleDatasetForm({
...
+          };
+        },
+      );
+      form.setFieldValue(["dataSource", "dataLayers"], dataLayersWithUpdatedTransforms);
+    }
+  }, [coordinateTransformationsJSON, form, transformationsMode]);
+
+  const getTransformationSettings = () => {
+    switch (transformationsMode) {
+      case TransformationsMode.NONE:
```
Comment (philippotto) [inline frontend/javascripts/dashboard/dataset/dataset_settings_data_tab.tsx]: either remove this case or move it below so that it's together with the default case:

```
      case TransformationsMode.NONE:
      default:
        return null;
```

**Review by philippotto — CHANGES_REQUESTED** [review]
UI looks nice 😃

during testing, I found the following things weird:

- open settings for a new DS
- set transforms to advanced, e.g.:
```
[
  {
    "name": "color",
    "coordinateTransformations": [
      {
        "type": "thin_plate_spline",
        "correspondences": {"source": [], "target": []}
      }
    ]
  },
  {
    "name": "segmentation",
    "coordinateTransformations": []
  }
]
```
- don't save but instead switch to "simple"
- set some rotations
- switch back to advanced and then back again to "simple" (don't touch sliders again)
- hit save and open settings again -> advanced settings were stored

-----------
also, if I set transforms to none, hit save and reload, the settings default to "simple". can you check whether the transforms for all layers are empty and then switch to "none"?

File: frontend/javascripts/dashboard/dataset/dataset_rotation_form_item.tsx [hunk 12]
```diff
@@ -180,12 +180,7 @@ export type DatasetRotationAndMirroringSettings = {
 export const AxisRotationSettingForDataset: React.FC<AxisRotationSettingForDatasetProps> = ({
   form,
 }: AxisRotationSettingForDatasetProps) => {
-  // form -> dataSource -> dataLayers can be undefined in case of the add remote dataset form which is initially empty.
-  const dataLayers: APIDataLayer[] | undefined = form?.getFieldValue(["dataSource", "dataLayers"]);
-  const isRotationOnly = useMemo(
-    () => (dataLayers ? doAllLayersHaveTheSameRotation(dataLayers) : false),
-    [dataLayers],
-  );
+  const isRotationOnly: boolean = form?.getFieldValue(["isRotationOnly"]) || false;
```
Comment (philippotto) [inline frontend/javascripts/dashboard/dataset/dataset_rotation_form_item.tsx:185]: this is the only place where `isRotationOnly` is read. the other usages merely set it (and I think there need to be more setting calls to avoid bugs).
what was wrong about the old approach to simply compute the info ad-hoc?

File: frontend/javascripts/dashboard/dataset/dataset_settings_data_tab.tsx (hunk 8 above)
Comment (knollengewaechs) [reply frontend/javascripts/dashboard/dataset/dataset_settings_data_tab.tsx:181]: 🤖 👍

File: frontend/javascripts/dashboard/dataset/dataset_rotation_form_item.tsx (hunk 12 above)
Comment (knollengewaechs) [reply frontend/javascripts/dashboard/dataset/dataset_rotation_form_item.tsx:185]: It led to unwanted behaviour: Having the advanced transforms open, every edit (e.g. deleting one number) would lead to a change in the datasource datalayers, causing a rerender in this component, and the input of the advanced field would lose focus. Next to that the datalayers here were only used to compute the isRotation info.

Comment (knollengewaechs) [reply frontend/javascripts/dashboard/dataset/dataset_rotation_form_item.tsx:185]: I *thought* it caused too many rerenders causing the advanced component to lose focus but apperently I was wrong.

Comment (knollengewaechs) [reply frontend/javascripts/dashboard/dataset/dataset_rotation_form_item.tsx:185]: Uff sorry. I remember now. The reason was that I dont want the overlay to be updated if the datasource layers, that are saved in the form, change. I only want it to show if there are transformations on disk. If I leave it like this, the modes will become a little bit dependent on each other again.
Given that the internal datasource layers are now properly updated, this problem almost disappears, but the overlay still glitches up for a second before disappearing. Thats why I am inclined to write it once, in the settings provider, only for the initial settings. 
> (and I think there need to be more setting calls to avoid bugs).

Alright! I didnt notice any more bugs during testing and in my mental model it makes sense like it is, so could you give me a hint where this needs to be set additionally?

File: frontend/javascripts/types/schemas/datasource.types.ts (hunk 3 above)
Comment (knollengewaechs) [reply frontend/javascripts/types/schemas/datasource.types.ts:36]: @fm3 small reminder :)

Comment (fm3) [reply frontend/javascripts/types/schemas/datasource.types.ts:36]: Whoops, sorry, this slipped through the cracks. The answer is yes!

File: frontend/javascripts/dashboard/dataset/dataset_rotation_form_item.tsx (hunk 12 above)
Comment (philippotto) [reply frontend/javascripts/dashboard/dataset/dataset_rotation_form_item.tsx:185]: let's have a quick call about this when you have some time :)

File: frontend/javascripts/dashboard/dataset/dataset_settings_provider.tsx [hunk 13]
```diff
@@ -44,7 +46,13 @@ type DatasetSettingsProviderProps = {
   form?: FormInstance<DatasetSettingsFormData>;
 };
 
-function getRotationFromCoordinateTransformations(
+const NULLED_AXIS_ROTATION_SETTING = { rotationInDegrees: 0, isMirrored: false };
+const INITIAL_DS_ROTATION_SETTINGS = {
```
Comment (philippotto) [inline frontend/javascripts/dashboard/dataset/dataset_settings_provider.tsx]: `NULLED_DS_ROTATION_SETTINGS`

File: frontend/javascripts/dashboard/dataset/dataset_settings_provider.tsx [hunk 14]
```diff
@@ -129,10 +136,36 @@ export const DatasetSettingsProvider: React.FC<DatasetSettingsProviderProps> = (
...
       form.setFieldsValue({
-        datasetRotation: getRotationFromCoordinateTransformations(dataSource),
+        coordinateTransformations: layersWithCoordTransformationsJSON,
       });
 
+      let initialTransformationsMode =
+        initialRotationSettings == null ? TransformationsMode.ADVANCED : TransformationsMode.SIMPLE;
+      if (initialRotationSettings === INITIAL_DS_ROTATION_SETTINGS) {
+        initialTransformationsMode = TransformationsMode.NONE;
+      }
```
Comment (philippotto) [inline frontend/javascripts/dashboard/dataset/dataset_settings_provider.tsx]:
```
let initialTransformationsMode;
if (initialRotationSettings === NULLED_DS_ROTATION_SETTINGS) {
  initialTransformationsMode = TransformationsMode.NONE;
} else if (initialRotationSettings != null) {
  initialTransformationsMode = TransformationsMode.SIMPLE;
} else {
  // When the existing transforms can't be expressed as a
  // rotational setting, we assume advanced.
  initialTransformationsMode = TransformationsMode.ADVANCED;
}
```

**Review by philippotto — CHANGES_REQUESTED** [review]
Code looks good and testing went mostly well, too. However, I noticed this problem:

https://github.com/user-attachments/assets/847564c1-ef1b-4457-a4fc-edfd717f735b

The basic steps to reproduce are: edit the sliders, switch to advanced mode and back to the sliders and then save --> re-opening the settings shows "None"

Can you have a look at this?

**Review by philippotto — APPROVED** [review]
🎉
