### PR TITLE
fix dataset upload if there's only one layer

### LINKED ISSUE #2408: dataset upload truncates layer directory if there is only one layer
in `DataSourceService`/`handleUpload`, unzip is called with `truncateCommonPrefix = true`, which creates invalid dataset directory structure if there is just one layer (making the layer directory a part of the common prefix).

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2408/create?referer=github" target="_blank">Log Time</a>

### PR DESCRIPTION
**Pull request by youri-k**
- upload of a dataset with one layer now works
- previously the layer folder got truncated as a common prefix

### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- upload a dataset zip which only contains one layer and no properties.json

### Issues:
- fixes #2408 

------
- [x] Ready for review

### CODE REVIEW

File: util/src/main/scala/com/scalableminds/util/io/ZipIO.scala [hunk 1]
```diff
@@ -100,11 +100,24 @@ object ZipIO {
...
+      if(path.toString.contains(string))
+        Some(path.toString.substring(0, path.toString.indexOf(string)))
+      else
+        None
+    }
+
     import collection.JavaConverters._
     val zipEntries = zip.entries.asScala.filter(e => !e.isDirectory && (includeHiddenFiles || !isFileHidden(e))).toList
 
+    //color, mask, segmentation
```
Comment (jstriebel) [inline util/src/main/scala/com/scalableminds/util/io/ZipIO.scala]: Please expand this comment to explain why this is needed.

File: util/src/main/scala/com/scalableminds/util/io/ZipIO.scala [hunk 2]
```diff
@@ -100,11 +100,24 @@ object ZipIO {
 
     def isFileHidden(e: ZipEntry): Boolean = new File(e.getName).isHidden || e.getName.startsWith("__MACOSX")
 
+    def stripPathFrom(path: Path, string: String): Option[String] = {
+      if(path.toString.contains(string))
```
Comment (jstriebel) [inline util/src/main/scala/com/scalableminds/util/io/ZipIO.scala]: Could this directly operate on the path?

File: util/src/main/scala/com/scalableminds/util/io/ZipIO.scala [hunk 3]
```diff
@@ -100,11 +100,24 @@ object ZipIO {
...
+    }
+
     import collection.JavaConverters._
     val zipEntries = zip.entries.asScala.filter(e => !e.isDirectory && (includeHiddenFiles || !isFileHidden(e))).toList
 
+    //color, mask, segmentation
     val commonPrefix = if (truncateCommonPrefix) {
-      PathUtils.commonPrefix(zipEntries.map(e => Paths.get(e.getName)))
+      val commonPrefixNotFixed = PathUtils.commonPrefix(zipEntries.map(e => Paths.get(e.getName)))
+      val strippedPaths = List("color", "mask", "segmentation").flatMap(stripPathFrom(commonPrefixNotFixed, _))
```
Comment (jstriebel) [inline util/src/main/scala/com/scalableminds/util/io/ZipIO.scala]: Why is it correct to strip either `color` or `mask` or `segmentation`? Why never all?

File: util/src/main/scala/com/scalableminds/util/io/ZipIO.scala (hunk 2 above)
Comment (jstriebel) [reply util/src/main/scala/com/scalableminds/util/io/ZipIO.scala]: Could it happen that string is just a substring of a directory? That looks dangerous to me then.

Comment (youri-k) [reply util/src/main/scala/com/scalableminds/util/io/ZipIO.scala]: You're right I'm looking into it

File: util/src/main/scala/com/scalableminds/util/io/ZipIO.scala (hunk 3 above)
Comment (youri-k) [reply util/src/main/scala/com/scalableminds/util/io/ZipIO.scala]: Because a dataLayer only has one category it belongs to.
Norman just confirmed this

Comment (jstriebel) [reply util/src/main/scala/com/scalableminds/util/io/ZipIO.scala]: Ok, perfect. Maybe add a comment about it then, it's not super obvious at first sight.

File: util/src/main/scala/com/scalableminds/util/io/ZipIO.scala [hunk 4]
```diff
@@ -100,22 +100,27 @@ object ZipIO {
 
     def isFileHidden(e: ZipEntry): Boolean = new File(e.getName).isHidden || e.getName.startsWith("__MACOSX")
 
-    def stripPathFrom(path: Path, string: String): Option[String] = {
-      if(path.toString.contains(string))
-        Some(path.toString.substring(0, path.toString.indexOf(string)))
-      else
-        None
+    def stripPathFrom(path: Path, string: String): Option[Path] = {
+      for (i <- 0 until path.getNameCount) {
```
Comment (jstriebel) [inline util/src/main/scala/com/scalableminds/util/io/ZipIO.scala]: I would prefer this to be recursive, but I think it's still fine

File: util/src/main/scala/com/scalableminds/util/io/ZipIO.scala [hunk 5]
```diff
@@ -100,22 +100,27 @@ object ZipIO {
...
+
+        if (path.subpath(i, i + 1).toString.contains(string))
```
Comment (jstriebel) [inline util/src/main/scala/com/scalableminds/util/io/ZipIO.scala]: Couldn't we use `== string` now?

Comment (youri-k) [reply util/src/main/scala/com/scalableminds/util/io/ZipIO.scala]: No because if there are multiple layers of the same category which are named e.g. `color_1`, `color_2`...
So in the case that one of those layers gets copied and is the only layer in the new dataset, this wouldn't get stripped.

File: util/src/main/scala/com/scalableminds/util/io/ZipIO.scala (hunk 4 above)
Comment (youri-k) [reply util/src/main/scala/com/scalableminds/util/io/ZipIO.scala]: Sounds good I'll do it later

File: util/src/main/scala/com/scalableminds/util/io/ZipIO.scala (hunk 5 above)
Comment (jstriebel) [reply util/src/main/scala/com/scalableminds/util/io/ZipIO.scala]: Maybe just add a comment that shows the possible problematic folder-structures. I think there's quite some invisible knowledge in those lines, that can only be figured out by looking at several datasets.

**Comment by jstriebel** [comment]
@youri-k : Please add a change note to [ ] the [changelog](CHANGELOG.md#unreleased)
