### PR TITLE
maybe-fix: loading already closed bucket file

### LINKED ISSUE #2781: bucket loading: Error processing WKW file. File is already closed
see https://discuss.webknossos.org/t/error-processing-wkw-file/950

### LINKED ISSUE #2976: Cube access counters do not need to be atomic anymore
follow-up to #2974 – since they are now only used in synchronized blocks, they should not have to be atomic anymore, so we should reduce the overhead there.

### PR DESCRIPTION
**Pull request by jstriebel**
This PR
* makes Cube aware that it's removed
* and makes the cache open a new file, if that is the case.

### URL of deployed dev instance (used for testing):
- https://cubecacherespectclosed.webknossos.xyz

### Steps to test:
- only testable under high load --> in production

### Issues:
- maybefixes #2781 / [discuss-entry](https://discuss.webknossos.org/t/error-processing-wkw-file/950)
- fixes #2976

------
- [ ] ~~Updated [changelog](../blob/master/CHANGELOG.md#unreleased)~~
- [ ] ~~Updated [migration guide](../blob/master/MIGRATIONS.md#unreleased) if applicable~~
- [x] Needs datastore update after deployment
- [x] Ready for review

### CODE REVIEW

File: webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/Cube.scala [hunk 1]
```diff
@@ -3,41 +3,48 @@
...
 
   def cutOutBucket(dataLayer: DataLayer, bucket: BucketPosition): Box[Array[Byte]]
 
-  def startAccess(): Unit = {
+  def tryAccess(): Boolean = {
     this.synchronized {
-      accessCounter.incrementAndGet()
+      if (isRemoved) {
+        NewRelic.noticeError("Tried to access cube which is already removed.")
+        return false
```
Comment (fm3) [inline webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/Cube.scala]: please remove all `return` statements, the scala-y way would be just 
```
if (isRemoved) {
  …
  false
}
else {
  accessCounter+=1
  true
}
```

**Comment by fm3** [comment]
Yes, I agree that this loop is not necessary. I think it’s good to go now. To test that, you can reduce the cache size in application.conf and add debug output to the onFinalize methods, then zoom around datasets until you hit the case :)
