### PR TITLE
AI Plans for organizations

### LINKED ISSUE #9233: Add a page for Activity logs for an organisation
## Detailed Description
Add new sub pages/tabs to the organization view to inform a orga admin about recent credits & subscriptions activities and events. ("Audit log")

All events should include date, time and a description.

Credits Events:
- new credits were added
  - monthly free credits
  - purchased credits
- credits were spent
  -  job, user and amount
- credits were refunded
  -  job crashed

Subscription Events:
- subscription plan changed
  - upgrades from lower to higher tier
  - downgraded from high to lower tier
- AI module was enabled/disabled
- additional user seat were added/removed to/from organization
- additional storage space was added/removed to/from organization

## Context

* [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
* [x] Specific to webknossos.org (set `isDemoInstance=true` in `application.conf`)

### LINKED ISSUE #9246: AI Plans for organizations
AI plans (additional orga field, nullable)

Team AI, Power AI, both bring training flatrate (superusers can always train)

Also adapt plan update request

### PR DESCRIPTION
**Pull request by fm3**
New optional organization property `aiPlan`, possible values `Team_AI`, `Power_AI` (or None).
Organizations without an aiPlan cannot start training jobs.
Can be set in `POST /pricing/updatePlan` along the other plan updates.

### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- Verify that:
1. **Personal plan**: “Unlock more features” shows Team/Power cards only; no AI Add‑on card/action.  
2. **Team plan, no AI add‑on (admin/owner)**:  
   - Settings: AI Add‑on card has action button.  
   - “Unlock more features”: Power + AI Add‑on cards side‑by‑side.  
   - AI Jobs drawer: Training tab shows add‑on notice + AI Add‑on card; action opens AI Add‑on modal.  
3. **Team plan, no AI add‑on (non‑admin)**: Same views, but no AI Add‑on action button.  
4. **Power plan, no AI add‑on (admin/owner)**:  
   - “Unlock more features” shows only AI Add‑on card.  
   - AI Add‑on action available.  
5. **Any plan with AI add‑on booked**:  
   - No AI Add‑on card in “Unlock more features”.  
   - AI Jobs drawer shows training UI (no notice).  
6. **Super user**: Training UI always available even without AI Add‑on.

### TODOs:
- [x] organization fields
- [x] plan updates
- [x] Forbid starting AI training jobs unless AiPlan is present or user is superuser
  - [x] backend
  - [x] frontend
- [x] frontend: show current ai plan in organization overview

### Issues:
- fixes #9246
- fixes #9233 (together with the already merged #9269 and #9264)

------
- [x] Added changelog entry (create a `$PR_NUMBER.md` file in `unreleased_changes` or use `./tools/create-changelog-entry.py`)
- [x] Added migration guide entry if applicable (edit the same file as for the changelog)
- [x] Removed dev-only changes like prints and application.conf edits
- [x] Considered [common edge cases](../blob/master/.github/common_edge_cases.md)

### CODE REVIEW

**Comment by knollengewaechs** [comment]
First my notes on testing: It went as described above in the description. The drawings add a really nice touch. In the team plan, the expected behaviour depends on the exact user role, but I think everything is working as expected!

**Comment by knollengewaechs** [comment]
The frontend code looks good, too! I will have another quick look once the upgrades table was adjusted and approve!

File: app/mail/DefaultMails.scala [hunk 1]
```diff
@@ -152,6 +152,19 @@ class DefaultMails @Inject()(conf: WkConf) {
...
     )
 
+  def upgradeAiAddonMail(user: User,
+                         userEmail: String,
+                         organizationName: String,
+                         aiPlan: String,
+                         pricingPlan: String): Mail =
+    Mail(
+      from = defaultSender,
+      subject = s"WEBKNOSSOS Upgrade: AI Add-on ($aiPlan)",
```
Comment (MichaelBuessemeyer) [inline app/mail/DefaultMails.scala:162]: In case the orga has no paid plan, the label will be "AI Add-on" -> Thus, the subject will be `WEBKNOSSOS Upgrade: AI Add-on AI Add-on` which might be a bit confusing at first sight 🤔

Comment (MichaelBuessemeyer) [reply app/mail/DefaultMails.scala:162]: Ah I see. " AI Add-on" is a filler value that should never occur. So never mind then

File: app/models/organization/Organization.scala [hunk 2]
```diff
@@ -334,6 +341,7 @@ class OrganizationDAO @Inject()(sqlClient: SqlClient)(implicit ec: ExecutionCont
                    )
                    VALUES(
                      $organizationId, ${planUpdate.description}, ${planUpdate.pricingPlan},
+                     ${planUpdate.aiPlanFlat}, ${planUpdate.aiPlanChanged},
```
Comment (MichaelBuessemeyer) [inline app/models/organization/Organization.scala:345]: The table `organization_plan_updates` is new to me. Is this a way of logging changes to orga plans? So now ai plan changes are included in this persisted logging in the db? Kinda similar to credit transactions?

Comment (fm3) [reply app/models/organization/Organization.scala:345]: Yes, correct, it was introduced in #9129 and since #9264 its content is also display on the organization settings page.

File: frontend/javascripts/admin/organization/pricing_plan_utils.ts [hunk 3]
```diff
@@ -84,6 +104,25 @@ export function hasSomePaidPlan(organization: APIOrganization | null) {
...
+    pricingPlan === PricingPlanEnum.Team ||
+    pricingPlan === PricingPlanEnum.TeamTrial ||
+    pricingPlan === PricingPlanEnum.Power ||
+    pricingPlan === PricingPlanEnum.PowerTrial ||
+    pricingPlan === PricingPlanEnum.Custom
+  );
+}
+
+export function formatAiPlanLabel(aiPlan: AiPlanEnum | null | undefined): string {
+  if (!aiPlan) return "Upgrade to Team or Power plan for advanced AI features";
```
Comment (knollengewaechs) [inline frontend/javascripts/admin/organization/pricing_plan_utils.ts]: as @MichaelBuessemeyer pointed out, maybe it makes sense to distinguish between existing plans in this message, so that users with orgas on the power plan know how to get the AI features?

Comment (hotzenklotz) [reply frontend/javascripts/admin/organization/pricing_plan_utils.ts]: Good catch. Done

File: frontend/javascripts/admin/organization/organization_plan_activity_view.tsx [hunk 4]
```diff
@@ -104,6 +104,13 @@ export function OrganizationPlanActivityView() {
           return Number.isFinite(value) ? formatCountToDataAmountUnit(value, true) : "∞";
         },
       },
+      {
+        title: "AI Plan",
+        dataIndex: "aiPlan",
+        key: "aiPlan",
+        width: 140,
+        render: (value: APIOrganizationPricingPlanUpdate["aiPlan"]) => value ?? UNCHANGED_LABEL,
```
Comment (knollengewaechs) [inline frontend/javascripts/admin/organization/organization_plan_activity_view.tsx:112]: maybe use `formatAiPlanLabel(value) ` here?
