### PR TITLE
Reduce hardware utilization after WebGL crash

### LINKED ISSUE #8141: Add functionallity allowing to recover from too high hardware utilization setting
The newly added hardware utilization modes are awesome, but the setting is saved across devices. Therefore, when switching the client device the previously set high hardware utilization might be too high for the device making wk crash.

## Detailed Description

Let's develop a feature that allows the user to recover from such a WebGL context loss error, by adding e.g. a button to the error toast that auto reduces the hardware utilization and then reloads wk. Other user interactions could be implemented as well. The toast interaction was just my initial idea.

## Context

* [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
* [ ] Specific to webknossos.org (set `isDemoInstance=true` in `application.conf`)

- See eg. this bug report: https://discuss.webknossos.org/t/gpu-error-on-ipad/1864/6

### PR DESCRIPTION
**Pull request by hotzenklotz**
This PR adds a functionality to recover from WebGL crashes by using a lower hardware utilization setting.

### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
1. Open annotation
2. Crash WebGL
   - e.g. in your browser console run: 
      ``` 
      const canvas = document.getElementById("render-canvas");
      const ext = canvas.getContext("webgl2")?.getExtension("WEBGL_lose_context")
            || canvas.getContext("webgl")?.getExtension("WEBGL_lose_context");
       ext.loseContext();
     ```   
3. Use error toast to downgrade hardware settings and reload
4. Validate, that the hardware settings were used.

### Issues:
- fixes #8141

------
(Please delete unneeded items, merge only when none are left open)
- [x] Added changelog entry (create a `$PR_NUMBER.md` file in `unreleased_changes` or use `./tools/create-changelog-entry.py`)
- [ ] Added migration guide entry if applicable (edit the same file as for the changelog)
- [ ] Updated [documentation](../blob/master/docs) if applicable
- [ ] Adapted [wk-libs python client](https://github.com/scalableminds/webknossos-libs/tree/master/webknossos/webknossos/client) if relevant API parts change
- [ ] Removed dev-only changes like prints and application.conf edits
- [ ] Considered [common edge cases](../blob/master/.github/common_edge_cases.md)
- [ ] Needs datastore update after deployment

### CODE REVIEW

File: frontend/javascripts/viewer/view/tracing_view.tsx [hunk 1]
```diff
@@ -23,13 +27,47 @@ const registerWebGlCrashHandler = (canvas) => {
...
+        ([factorStr]) => Number(factorStr) < currentGpuFactor,
+      );
+
+      const handleReduceAndReload = async () => {
+        Toast.close(WEBGL_CONTEXT_LOST_KEY);
+        if (lowerUtilizationEntry) {
+          const lowerGpuFactor = Number(lowerUtilizationEntry[0]);
+          Store.dispatch(updateUserSettingAction("gpuMemoryFactor", lowerGpuFactor));
+        }
+        location.reload();
```
Comment (philippotto) [inline frontend/javascripts/viewer/view/tracing_view.tsx:57]: this is not guaranteed to be saved properly to the server as it doesn't await the save request. currently, there is no nice way to await that, though (Model.ensureSavedState only cares about annotation state).

a heuristic solution would be to simply wait a bit. in settings_saga.ts, there is this code `debounce(2500, "UPDATE_USER_SETTING", pushUserSettingsAsync)` which is responsible for listening to setting updates. you could extract the 2500 into a variable (e.g., `SETTING_SAVE_DEBOUNCE_MS`) and import it here. e.g.;

```
          Store.dispatch(updateUserSettingAction("gpuMemoryFactor", lowerGpuFactor));
        }
        await sleep(2 * SETTING_SAVE_DEBOUNCE_MS); 
        location.reload();
```

alternatively, one could do some saga magic (dispatch a special action that gets buffered into a channel and call a callback generated by the action creator). we already do some similar stuff elsewhere, but I think it would be overkill here.

Comment (hotzenklotz) [reply frontend/javascripts/viewer/view/tracing_view.tsx:57]: Ok, i applied that suggestion. But `2 * SETTING_SAVE_DEBOUNCE_MS)` is a 5 seconds delay - which makes the whole reload button feel very sluggish.

Comment (philippotto) [reply frontend/javascripts/viewer/view/tracing_view.tsx:57]: I think, the delay can only be reduced a bit, unless we use a more complex waiting approach. since this scenario is quite edge-casey and a crash did occur, anyway, I think, it's acceptable. maybe use 1.5 instead of 2 to reduce to 3.75 s?

**Review by philippotto — APPROVED** [review]
