### PR TITLE
Fix mouse input after layout reset

### LINKED ISSUE #3879: Reset Layout breaks inputcatcher mouse handling
After resetting the layout, inputcatcher mouse handling is broken. Setting a node, using right-click, will place the node at a wrong position, zooming in the 3D view is also not working as intended.
I investigated this and it seems to happen because the `domSelector` reference in the `input.js` - `InputMouse` is obsolete after resetting the layout (`this.domElement.getBoundingClientRect()` always returns 0s).

One way to fix this would be to always use `document.getElementById(...)` instead of caching the reference. According to https://stackoverflow.com/questions/12514970/is-getelementbyid-efficient this is fairly efficient.

### PR DESCRIPTION
**Pull request by MichaelBuessemeyer**
This PR reworks the `InputMouse` to not cache the input target anymore. It only caches its id and requests the input target on demand. This also means that `querySelector` can be replaced by `getElementById`. (This might already solve #4030)
### URL of deployed dev instance (used for testing):
- [https://fixinputafterlayoutreset.webknossos.xyz](https://fixinputafterlayoutreset.webknossos.xyz)

### Steps to test:
- Open a tracing (e.g. skeleton) and trace a bit. Then reset the layout.
- In the previous version, this should break the mouse input. This should be fixed by with this PR :slightly_smiling_face: 

### Issues:
- fixes #3879

------
- ~~[ ] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)~~
- ~~[ ] Updated [migration guide](../blob/master/MIGRATIONS.md#unreleased) if applicable~~
- ~~[ ] Updated [documentation](../blob/master/docs) if applicable~~
- ~~[ ] Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes~~
- ~~[ ] Needs datastore update after deployment~~
- [x] Ready for review

### CODE REVIEW

File: frontend/javascripts/oxalis/controller/viewmodes/plane_controller.js [hunk 1]
```diff
@@ -137,16 +138,16 @@ class PlaneController extends React.PureComponent<Props> {
     // newest input catchers. We should refactor the
     // InputMouse handling so that this is not necessary anymore.
     // See: https://github.com/scalableminds/webknossos/issues/3475
-    const tdSelector = `#inputcatcher_${OrthoViews.TDView}`;
-    Utils.waitForSelector(tdSelector).then(() => {
+    const tdSelector = `inputcatcher_${OrthoViews.TDView}`;
```
Comment (daniel-wer) [inline frontend/javascripts/oxalis/controller/viewmodes/plane_controller.js]: Looking at the above comment, could it be that this is no longer an issue now? If so, we could remove the code waiting for the td view (line 142) and the comment :)

File: frontend/javascripts/libs/utils.js [hunk 2]
```diff
@@ -554,9 +554,9 @@ export function waitForCondition(pred: () => boolean): Promise<void> {
   return new Promise(tryToResolve);
 }
 
-export function waitForSelector(selector: string): Promise<*> {
+export function waitForElementWithId(selector: string): Promise<*> {
```
Comment (daniel-wer) [inline frontend/javascripts/libs/utils.js]: I'd rename `selector` to `id` or `elementId` now

File: frontend/javascripts/libs/input.js [hunk 3]
```diff
@@ -340,61 +339,32 @@ export class InputMouse {
...
-        this.mouseWheel,
-        { passive: false },
-      ),
+      Utils.addEventListenerWithDelegation(document, "wheel", targetSelector, this.mouseWheel, {
+        passive: false,
+      }),
     );
 
-    this.hammerManager = new Hammer(this.domElement, {
+    this.hammerManager = new Hammer(domElement, {
```
Comment (daniel-wer) [inline frontend/javascripts/libs/input.js]: Could you add a comment referencing issue #3879 here, because I think this is still a problem for the touch handling. HammerJS binds to the specific element and doesn't support event delegation via a selector. Fixing this has low priority imo, so the comment should be sufficient :)

**Comment by MichaelBuessemeyer** [comment]
@ #3879 This PR only fixes the input bug for mouse users. Touch systems still might break because HammerJS keeps a fixed reference of the input catchers and does not support the event delegation.
