### PR TITLE
Always make wheel listeners not passive to allow preventDefault

### LINKED ISSUE #3938: preventDefault for wheel events does not work for new chrome version
See https://developers.google.com/web/updates/2019/02/scrolling-intervention (or as I'd name the article: "Breaking wheel scrolling by default") for details.

### PR DESCRIPTION
**Pull request by philippotto**
### URL of deployed dev instance (used for testing):
- https://fixpassivewheellistener.webknossos.xyz

### Steps to test:
- used chrome v73 and scrolled in viewport with k/l scrolling > 1

### Issues:
- fixes #3938

------
- [x] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)
- [X] Ready for review

### CODE REVIEW

File: frontend/javascripts/libs/utils.js [hunk 1]
```diff
@@ -453,7 +475,11 @@ export function addEventListenerWithDelegation(
       }
     }
   };
-  element.addEventListener(eventName, wrapperFunc, false);
+  element.addEventListener(
+    eventName,
+    wrapperFunc,
+    arePassiveEventsSupported() ? { passive: false } : false,
```
Comment (daniel-wer) [inline frontend/javascripts/libs/utils.js]: Now every event listener attached with `addEventListenerWithDelegation` is passive, shouldn't we only do this for `wheel` events? I'd suggest adding another optional parameter `options` which is the same as the parameter to `addEventListener`. When attaching the `wheel` handler we can set passive to false there.

**Comment by philippotto** [comment]
@daniel-wer Thanks for your feedback :) Done! If you approve, I'll merge this once the build succeeded.
