### PR TITLE
Fix download of public annotation, include access ctx in user cache key

### LINKED ISSUE #7016: Sometimes, api/annotation/download, called by libs, returns 404
…and an ambiguous “this resource could not be found”. We should find a way to reliably reproduce and debug this. Possibly with more error chaining in production.

### PR DESCRIPTION
**Pull request by fm3**
Fetching the user object to write the NML failed for logged-out users, since it was missing the GlobalAccessContext modifier. However, the user cache was independent of the access context, making this work sometimes nonetheless (except if the cache was expired). Instead, the user cache should take the access context as cache key, avoiding leaking user info in unexpected contexts.

### Steps to test:
- Set annotation and its dataset to public
- Download route should work even when logged out and no other requests have been sent in the past 3 minutes (use wget directly on `/api/annotations/:id/download`

### Issues:
- fixes #7016

------
- [x] Updated [changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)

### CODE REVIEW

File: app/models/user/UserService.scala [hunk 1]
```diff
@@ -249,12 +257,12 @@ class UserService @Inject()(conf: WkConf,
...
   def updateLastTaskTypeId(user: User, lastTaskTypeId: Option[String])(implicit ctx: DBAccessContext): Fox[Unit] =
     userDAO.updateLastTaskTypeId(user._id, lastTaskTypeId).map { result =>
-      userCache.remove(user._id)
+      removeUserFromCache(user._id)
       result
     }
 
   def retrieve(loginInfo: LoginInfo): Future[Option[User]] =
-    userDAO.findOne(ObjectId(loginInfo.providerKey))(GlobalAccessContext).futureBox.map(_.toOption)
+    findOneCached(ObjectId(loginInfo.providerKey))(GlobalAccessContext).futureBox.map(_.toOption)
```
Comment (fm3) [inline app/models/user/UserService.scala:265]: I noticed that this didn’t use the cache. I think it is safe for it to do so now. This method is used by silhouette when authenticating requests. This change may save us quite a few database queries

**Comment by fm3** [comment]
note to self: change cache key from whole access context to its toStringAnonymous representation to avoid cache invalidation when the requesting user is mutated

File: app/controllers/AnnotationIOController.scala [hunk 2]
```diff
@@ -411,7 +411,7 @@ Expects:
           skeletonAnnotationLayer =>
             tracingStoreClient.getSkeletonTracing(skeletonAnnotationLayer, skeletonVersion)
         } ?~> "annotation.download.fetchSkeletonLayer.failed"
-        user <- userService.findOneCached(annotation._user) ?~> "annotation.download.findUser.failed"
+        user <- userService.findOneCached(annotation._user)(GlobalAccessContext) ?~> "annotation.download.findUser.failed"
```
Comment (philippotto) [inline app/controllers/AnnotationIOController.scala:414]: So, this failed before (ignoring the caching issue) because the requesting user didn't have access to the owning user?
Does this mean that an annotation owned by user A can be downloaded by user B (if B has access to it) even though user B might not be allowed to "read" user A? Because user A needs to be serialized into the annotation?
I'm wondering whether this circumvents the permission system a bit?

Comment (fm3) [reply app/controllers/AnnotationIOController.scala:414]: Yes, that’s true. However, not all info about user A is serialized into the annotation. I believe we had a discussion about this some time ago and decided that it would be fair to say that a user publishing an annotation publishes their name with it. I’m open to having that discussion again, though. Also it might be worth double-checking what info is really needed for wk to show an annotation. The download only includes the name, but i think the annotation info request (which already works in the same way before this PR) also includes the email address.

Comment (philippotto) [reply app/controllers/AnnotationIOController.scala:414]: Ok, fair enough :+1:

> Also it might be worth double-checking what info is really needed for wk to show an annotation.

Yes, this is a good idea. One could also put in a dummy email value à la `anonymous`.

Comment (fm3) [reply app/controllers/AnnotationIOController.scala:414]: https://github.com/scalableminds/webknossos/issues/7029

**Review by philippotto — APPROVED** [review]
Works great :+1:
