### PR TITLE
Fix ad-hoc mesh closing edges on layer borders

### LINKED ISSUE #9069: Ad-Hoc mesh is half-open at dataset bbox
I think we already added some padding there in the past to get a surface at the layer bbox. 

Image

Worth checking if this also happens without segment index

### PR DESCRIPTION
**Pull request by fm3**
Ad-hoc meshing showed some open edges
 - with segment index: at layer topleft borders and layer bottomright borders
 - without segment index: only at layer topleft borders

The topleft problem was caused because the backend didn’t like negative requested coordinates, leading to crash fixes which shifted the toplefts into the layer bbox. This PR fixes this in the backend and undoes this change in the frontend, so negative coordinates are again sent, giving a clean upper edge.

The bottomright problem was caused because the segment index doesn’t indicate anything below the layer bbox. The neighbors case would add a cube outside of the layer, providing the outer edge, but the segment index case would skip that. Now the frontend embiggens the cubes to request if they align with the bottomright edges.

### URL of deployed dev instance (used for testing):
- https://adhocmeshedges.webknossos.xyz

### Steps to test:
- Request some ad-hoc meshes that touch the layer borders with and without segment index
- test also with a dataset that starts at 0,0,0 so you can test that the backend now handles the negative-coordinate requests. l4_sample doesn’t test this.

### Issues:
- fixes #9069

------
- [x] Added changelog entry (create a `$PR_NUMBER.md` file in `unreleased_changes` or use `./tools/create-changelog-entry.py`)
- [x] Removed dev-only changes like prints and application.conf edits
- [x] Considered [common edge cases](../blob/master/.github/common_edge_cases.md)
- [x] Needs datastore update after deployment

### CODE REVIEW

File: frontend/javascripts/admin/rest_api.ts [hunk 1]
```diff
@@ -1965,7 +1964,7 @@ export function computeAdHocMesh(
           // is added here to the position and bbox size.
           position: positionWithPadding, // position is in mag1
           additionalCoordinates,
-          cubeSize: V3.toArray(V3.add(cubeSize, [1, 1, 1])), //cubeSize is in target mag
+          cubeSize: cubeSize, // cubeSize is in target mag
```
Comment (philippotto) [inline frontend/javascripts/admin/rest_api.ts]:
```suggestion
          cubeSize, // cubeSize is in target mag
```

File: frontend/javascripts/admin/rest_api.ts [hunk 2]
```diff
@@ -1965,7 +1964,7 @@ export function computeAdHocMesh(
           // is added here to the position and bbox size.
```
Comment (philippotto) [inline frontend/javascripts/admin/rest_api.ts:1964]: #8901 moved the padding code of `position` to the caller. your pr moves the padding code of `cubeSize` to the caller, too. now the above comment is a bit out of place. can you tweaken it to explain that the caller is responsible for appropriate padding. bonus points if you explain that negative coords are not a problem and what's special about the no-segment-index-border case.

Comment (philippotto) [reply frontend/javascripts/admin/rest_api.ts:1964]: now that I think about it, maybe it would be nicer to move both padding code back here (the function will additionally require the layer boundingBox but that shouldn't be a problem).

File: frontend/javascripts/viewer/model/sagas/meshes/ad_hoc_mesh_saga.ts [hunk 3]
```diff
@@ -469,11 +470,12 @@ function* maybeLoadMeshChunk(
   const additionalCoordinates = yield* select((state) => state.flycam.additionalCoordinates);
   const threeDMap = getOrAddMapForSegment(layer.name, segmentId, additionalCoordinates);
   const mag = magInfo.getMagByIndexOrThrow(zoomStep);
+
+  // Move position by -1,-1,-1 in mag to get a closing edge at the topleft layer border
+  // and to fill grid gaps (cube size will be increased by 1,1,1 accordingly)
   const paddedPosition = V3.toArray(V3.sub(clippedPosition, mag));
-  const paddedPositionWithinLayer =
```
Comment (philippotto) [inline frontend/javascripts/viewer/model/sagas/meshes/ad_hoc_mesh_saga.ts:473]: the method `clipPositionIntoBoundingBox` has no usages now. I'd vote to remove it again (was only added in one of the bugfix prs).

File: frontend/javascripts/viewer/model/sagas/meshes/ad_hoc_mesh_saga.ts [hunk 4]
```diff
@@ -495,7 +497,13 @@ function* maybeLoadMeshChunk(
 
   const { segmentMeshController } = getSceneController();
 
-  const cubeSize = marchingCubeSizeInTargetMag();
+  let cubeSize = marchingCubeSizeInTargetMag();
+  cubeSize = V3.toArray(V3.add(cubeSize, [1, 1, 1]));
+  if (cubePreciselyTouchesBottomRightLayerEdge(paddedPosition, mag, cubeSize, layer)) {
+    // cube ends precisely at layer bbox,
+    // increase size by 1,1,1 again to get a closing edge
+    cubeSize = V3.toArray(V3.add(cubeSize, [1, 1, 1]));
```
Comment (philippotto) [inline frontend/javascripts/viewer/model/sagas/meshes/ad_hoc_mesh_saga.ts]: in the pr description you explained that this is only necessary for the segment-index-case. I assume it doesn't cause problems in the no-segment-index-case which is why you didn't extend the conditional?

File: frontend/javascripts/viewer/model/sagas/meshes/ad_hoc_mesh_saga.ts [hunk 5]
```diff
@@ -495,7 +497,13 @@ function* maybeLoadMeshChunk(
 
   const { segmentMeshController } = getSceneController();
 
-  const cubeSize = marchingCubeSizeInTargetMag();
+  let cubeSize = marchingCubeSizeInTargetMag();
+  cubeSize = V3.toArray(V3.add(cubeSize, [1, 1, 1]));
```
Comment (philippotto) [inline frontend/javascripts/viewer/model/sagas/meshes/ad_hoc_mesh_saga.ts]: `V3.toArray` here and in the other spots should not be necessary anymore thanks to #9059. the result of V3 operations is an array, anyway. prior to #9059 it could be a float32array which was mostly fine but strictly needed conversion for the REST api call. due to the bugfixes the toArray code got moved into the sagas (which was already not ideal) and now it's completely obsolete :tada:

File: frontend/javascripts/viewer/model/sagas/meshes/ad_hoc_mesh_saga.ts [hunk 6]
```diff
@@ -495,7 +497,13 @@ function* maybeLoadMeshChunk(
...
+  if (cubePreciselyTouchesBottomRightLayerEdge(paddedPosition, mag, cubeSize, layer)) {
```
Comment (philippotto) [inline frontend/javascripts/viewer/model/sagas/meshes/ad_hoc_mesh_saga.ts]: are you sure that the same cannot happen for the top left case? the following:

> The bottomright problem was caused because the segment index doesn’t indicate anything below the layer bbox. The neighbors case would add a cube outside of the layer, providing the outer edge, but the segment index case would skip that. Now the frontend embiggens the cubes to request if they align with the bottomright edges.

reads like it could happen for top-left, too (probably more relevant for bboxes that dont start at 0,0,0).

File: frontend/javascripts/admin/rest_api.ts (hunk 2 above)
Comment (philippotto) [reply frontend/javascripts/admin/rest_api.ts:1964]: (I can also push a commit for that if you agree and don't feel like doing even more frontend.)

Comment (fm3) [reply frontend/javascripts/admin/rest_api.ts:1964]: tbh I’m not sure if I agree. In my head, the rest_api.ts is just passing on arguments to the routes, responsible for knowing the routes and the api formats. This padding is not a special format for the request but rather an important part of puzzling together the right pieces. I would have expected this to happen in the adhoc mesh saga.

However, since I’m only rarely editing these files, I will go with your preference if you say I should.

On explaining comments, of course, I’m happy to add more detail :)

What do you think?

File: frontend/javascripts/viewer/model/sagas/meshes/ad_hoc_mesh_saga.ts (hunk 4 above)
Comment (fm3) [reply frontend/javascripts/viewer/model/sagas/meshes/ad_hoc_mesh_saga.ts]: If my understanding is correct, it even improves the no-segment-index-case. Because if the lower-right box is now a little bigger, and already includes the voxel next to the dataset edge, no neighbors will be returned there, resulting in fewer requests. The final output should be the same.

File: frontend/javascripts/viewer/model/sagas/meshes/ad_hoc_mesh_saga.ts (hunk 6 above)
Comment (fm3) [reply frontend/javascripts/viewer/model/sagas/meshes/ad_hoc_mesh_saga.ts]: The top-left case is already covered because *all* cube positions will be shifted by -1,-1,-1 as mentioned in line 476, and cube sizes enlarged by 1,1,1 in line 501.

I’ll expand the comments.
